### ISSUE TITLE
License matters, clarification on usage, and GPL violations

### ISSUE THREAD

**Issue by sorpaas** [casper-network/casper-node#1136]
I've been following CasperLabs' work since I heard a talk about it in DevCon V. I really like the CBC protocol and its designs. However, on license matters, I think there's something I must bring up, as I couldn't find discussions on this elsewhere. There are things that have to be fixed (GPL violations), and things that many developers and me would really appreciate clarifications, so that we can properly utilize the codebase, and avoid any "misuse" defined in your license terms.

## License matters

If you knew MongoDB, you know that "open source" is a somewhat sensitive word -- as people expect codebases under an "open source" license would comply with the open source definition. [OSI reviews](https://opensource.org/LicenseReview122019) provided some reasons why they think the current license is not appropriately "open source". While that's only according to their OSI's definitions, I couldn't find any responses from CasperLabs on how those critics are addressed, and what's CasperLabs' definition of open source. Without this, the word "open source" in the license title "CapserLabs Open Source License" is going to be a source of trouble when the software is made aware by the wider open source community.

The license also contains some reference to "FLOSS", which is supposed to mean free/libre and open source software. The current license also heavily deviates from what the community commonly understand it is.

A recommendation from mine would be if the term "open source" can be removed from the license title and preamble. Why not simply call it "free and open"? No one will question that whether the license is "free and open" at all, but many will question whether the license is "open source" or "FLOSS".

## Clarification on usage

I also hope if there can be a more concrete summary page on what is allowed and what is not allowed under the current license terms, as after reading the whole license, I still find it quiet confusing. Not only does this benefit developers like me, but also ecosystems and enterprises heavily.

## GPL violations

The license this codebase use (COSLv1) is an open-codebase license. As it's not compatible with GPL, no code in this codebase shall depend on it. However, currently there's one violation of it:

* [colour](https://crates.io/crates/colour), licensed under GPL-3.0.

That dependency has to be removed from the current codebase to avoid the violation. Given it's only a simple dependency, I think this would be relatively easy to do.

**Comment by Fraser999** [comment]
Hi @sorpaas 

Thanks for raising this issue.  I can't personally speak to your first two sections, but I will address the issue of GPL violation.  The `colour` crate happens to be my own, so this will be an easy fix.
