### ISSUE TITLE
Block Proposer Must Check Deploy Hashes Back to the Last TTL

### ISSUE THREAD

**Issue by piotr-dziubecki** [casper-network/casper-node#1421]
When the block proposer initializes, it currently gets all of the deploy hashes going back to genesis.  It must only get deploy hashes as far back as the TTL.

**Comment by piotr-dziubecki** [comment]
https://casperlabs.atlassian.net/browse/NDRS-1075

**Comment by fizyk20** [comment]
It turned out that the code already does this as it is.
