### ISSUE TITLE
Use different namespaces for different networks.

### ISSUE THREAD

**Issue by piotr-dziubecki** [casper-network/casper-node#1424]
Currently a node uses a single directory to hold its LMDB database files and various "unit" files created by consensus.  To avoid problems if a node is run against e.g. the testnet and later the mainnet, we need to create a subdirectory in the storage folder which is named as per the given network, i.e. it will use the [`chainspec.network.name`](https://github.com/casper-network/casper-node/blob/85a7c37793d2bee48931f89e3b6dc216a700935d/resources/production/chainspec.toml#L22) value for the subdir name.

There are a few aspects to this task:

* need to pass the network name in via [`Storage::new()`](https://github.com/casper-network/casper-node/blob/85a7c37793d2bee48931f89e3b6dc216a700935d/node/src/components/storage.rs#L250-L255).  This will be done similarly to the `protocol_version`: it's also specified in the chainspec, and the initializer reactor (which constructs the `Storage` component) [accesses the chainspec by calling the `ChainspecLoader` component](https://github.com/casper-network/casper-node/blob/85a7c37793d2bee48931f89e3b6dc216a700935d/node/src/reactor/initializer.rs#L197).
* the [`ContractRuntime` component's constructor](https://github.com/casper-network/casper-node/blob/85a7c37793d2bee48931f89e3b6dc216a700935d/node/src/components/contract_runtime.rs#L655-L662) should be changed.  Currently it takes a copy of the Storage component's config (`storage_config: WithDir<StorageConfig>`), but only needs that to deduce the path in which to create its own LMDB files.  We should replace that variable with a simple `PathBuf` or `&Path` which will provided via a new getter on the `Storage` component.  The initializer reactor has access to the newly-constructed `Storage` just before it constructs the `ContractRuntime`.
* We need to ensure when nodes upgrade from the current version to this new one that they move their existing database files.  This code should only need to exist while we're transitioning from the currently running version of node to the next one, so the simplest way to achieve this is to have the the `Storage` component move the 4 relevant files in its constructor.  The files are `data.lmdb`, `data.lmdb-lock`, `storage.lmdb` and `storage.lmdb-lock`.  They just need to be moved from what is currently [`root`](https://github.com/casper-network/casper-node/blob/85a7c37793d2bee48931f89e3b6dc216a700935d/node/src/components/storage.rs#L259) to the new subdir of `root`.  That code should have a TODO added to help remind us to remove it after the next version is published, as we don't want this behaviour to persist after the upgrade in which this change is introduced.
* All existing tests should be updated if required.
* Should add a new test to the existing suite of Storage unit tests to exercise the behaviour of moving the LMDB files.  Note that the `data.lmdb` and `data.lmdb-lock` files need not be actual LMDB files for the purposes of this test.  They're the DB files backing global state (owned by `ContractRuntime`), but the test only needs to ensure they're moved appropriately - they won't be actually read as DB files.  We tend to use `tempfile::tempdir()` for testing such filesystem-related things.

**Comment by EdHastingsCasperLabs** [comment]
Given that we don't have a strong use case for this, and that it will take a fair amount of specialized testing, I don't think this is worth doing right now. Recommend moving to backlog and revisit in Q3.

**Comment by EdHastingsCasperLabs** [comment]
@Fraser999 might this be a good task for Austin when he comes on board?

**Comment by goral09** [comment]
I think we should create subdirs named after _genesis hash_ and not network name. Network name doesn't need to be unique – there can be two networks with the same name and different genesis hashes that would be incompatible.
