### ISSUE TITLE
hasn't downloaded any blocks in expected time window

### ISSUE THREAD

**Issue by XxxxYxxx** [casper-network/casper-node#1431]
![截图录屏_选择区域_20210511153951](https://user-images.githubusercontent.com/81127922/117777538-48f40e00-b26f-11eb-93c0-13cfedf211dc.png)
![截图录屏_选择区域_20210511153921](https://user-images.githubusercontent.com/81127922/117777550-4b566800-b26f-11eb-9707-6a07d076295e.png)
![截图录屏_选择区域_20210511153939](https://user-images.githubusercontent.com/81127922/117777553-4beefe80-b26f-11eb-9143-892877b86bb9.png)

**Comment by goral09** [comment]
@XxxxYxxx Can you confirm that your node is connected to others? It will shut down with this particular error message if it hasn't received any traffic in 5 minutes.
