### ISSUE TITLE
Enhance deploy acceptor to validate associated keys

### ISSUE THREAD

**Issue by piotr-dziubecki** [casper-network/casper-node#1441]

**Comment by EdHastingsCasperLabs** [comment]
Running a day behind on this due to schedule pressure, but in prog.

**Comment by EdHastingsCasperLabs** [comment]
After talking w/ Fraser, we're moving this to 1.4 as there are no tests on the deploy_acceptor, and we want to add some before releasing this or other changes to the deploy_acceptor.
