### ISSUE TITLE
system::transfer_to_account fails with a surprisingly low transfer amount

### ISSUE THREAD

**Issue by AlexanderLimonov** [casper-network/casper-node#1444]
The largest U512 that system::transfer_to_account takes is 99_998_500_000_000_000 motes, or 99,998,500 CSPR. One mote more and it reverts.

To reproduce, follow instructions for running host-function-metrics here : https://github.com/casper-network/casper-node/tree/master/execution_engine_testing/tests/src/profiling

Note that the failing binary is the state-initializer, while the offending call is made in smart_contracts/contracts/profiling/state-initializer/src/main.rs

**Comment by cspramit** [comment]
spoke with @mpapierski this is more of internal use
