### ISSUE TITLE
EE: call_contract does not enforce Group access restriction or args type checking

### ISSUE THREAD

**Issue by zie1ony** [casper-network/casper-node#1470]
call_versioned_contract has the correct functionality, but call_contract does not

this is a serious userland security violation

change call_contract to enforce Group access and args type checking, exactly as call_versioned_contract

**Comment by EdHastingsCasperLabs** [comment]
something like this...

Index: execution_engine/src/core/runtime/mod.rs
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/execution_engine/src/core/runtime/mod.rs b/execution_engine/src/core/runtime/mod.rs
--- a/execution_engine/src/core/runtime/mod.rs	(revision da04b479901cc51af7df32210b66dae58b65fcb8)
+++ b/execution_engine/src/core/runtime/mod.rs	(date 1621619648159)
@@ -1800,16 +1800,17 @@
             .cloned()
             .ok_or_else(|| Error::NoSuchMethod(entry_point_name.to_owned()))?;
 
-        let context_key = self.get_context_key_for_contract_call(contract_hash, &entry_point)?;
+        let contract_package_hash = contract.contract_package_hash().into();
 
-        self.execute_contract(
-            key,
-            context_key,
-            contract,
-            args,
-            entry_point,
-            self.context.protocol_version(),
-        )
+        let contract_package = match self.context.read_gs(&key)? {
+            Some(StoredValue::ContractPackage(contract_package)) => contract_package,
+            Some(_) => {
+                return Err(Error::InvalidContractPackage(contract_package_hash));
+            }
+            None => return Err(Error::KeyNotFound(key)),
+        };
+
+        self.call_contract_checked(contract_package, contract, entry_point, args)
     }
 
     /// Calls `version` of the contract living at `key`, invoking `method` with
@@ -1827,10 +1828,7 @@
         let contract_package = match self.context.read_gs(&key)? {
             Some(StoredValue::ContractPackage(contract_package)) => contract_package,
             Some(_) => {
-                return Err(Error::FunctionNotFound(format!(
-                    "Value at {:?} is not a versioned contract",
-                    contract_package_hash
-                )));
+                return Err(Error::InvalidContractPackage(contract_package_hash));
             }
             None => return Err(Error::KeyNotFound(key)),
         };
@@ -1868,8 +1866,22 @@
             .cloned()
             .ok_or_else(|| Error::NoSuchMethod(entry_point_name.to_owned()))?;
 
+        self.call_contract_checked(contract_package, contract, entry_point, args)
+    }
+
+    /// Calls contract if caller has access, and args match entry point definition
+    fn call_contract_checked(
+        &mut self,
+        contract_package: ContractPackage,
+        contract: Contract,
+        entry_point: EntryPoint,
+        args: RuntimeArgs,
+    ) -> Result<CLValue, Error> {
+        // if public, allowed
+        // if not public, restricted to user group access
         self.validate_entry_point_access(&contract_package, entry_point.access())?;
 
+        // ensure args type(s) match defined args of entry point
         for (expected, found) in entry_point
             .args()
             .iter()
@@ -1877,11 +1889,14 @@
             .cloned()
             .zip(args.to_values().into_iter().map(|v| v.cl_type()).cloned())
         {
-            if expected != found {
-                return Err(Error::type_mismatch(expected, found));
-            }
+            if expected == found {
+                continue;
+            }
+            return Err(Error::type_mismatch(expected, found));
         }
 
+        // if session the caller's context
+        // else the called contract's context
         let context_key = self.get_context_key_for_contract_call(contract_hash, &entry_point)?;
 
         self.execute_contract(
Index: execution_engine/src/core/execution/error.rs
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/execution_engine/src/core/execution/error.rs b/execution_engine/src/core/execution/error.rs
--- a/execution_engine/src/core/execution/error.rs	(revision da04b479901cc51af7df32210b66dae58b65fcb8)
+++ b/execution_engine/src/core/execution/error.rs	(date 1621619648207)
@@ -92,6 +92,8 @@
     KeyIsNotAURef(Key),
     #[error("Unexpected variant of a stored value")]
     UnexpectedStoredValueVariant,
+    #[error("Invalid contract package: {}", _0)]
+    InvalidContractPackage(ContractPackageHash),
     #[error("A locked contract cannot be upgraded")]
     LockedContract(ContractPackageHash),
 }
