### ISSUE TITLE
Hide Transfer type's "gas" field from JSON representation

### ISSUE THREAD

**Issue by mpapierski** [casper-network/casper-node#1486]
May want to consider removing this field from the transfer type as we are now considering other designs.

Follow up for #1385 

As part of upgrade testing, @dwerner and I identified that the "Transfer" struct's derived Serialize/Deserialize is used both for client-facing APIs as well as a storage layer. Removing a "gas" field from the struct definition caused data corruption as the test was trying to deserialize records with an extra field missing in the new code.

In the current form, the code in #1385 still includes "gas" field in JSON representation but prepared the groundwork for removing it. This task is about removing the "gas" field from JSON representation by either changing derived Serialize into `impl Serialize for Transfer` or adding a separate struct for the usage of node's "transfer_db" storage.

**Comment by RitaMAllenCA** [comment]
Check with @mpapierski  - may not be relevant any longer in its current form

**Comment by devendran-m** [comment]
Won't do.
