### ISSUE TITLE
Add logic for finalizing blocks with finality signatures

### ISSUE THREAD

**Issue by fizyk20** [casper-network/casper-node#1490]
Currently, we only consider a block finalized if it's output by our Highway instance. However, it's a requirement for memory optimizations in Highway to also consider a block finalized if it has enough finality signatures. Hence, we need the following logic (from https://casperlabs.atlassian.net/browse/NDRS-950):

- Whenever we have 2/3 (or rather: 50% + FTT / 2 — let’s call that “fully signed”) signatures for the same hash in the current era, we request the signed block. Then we download all ancestors that we haven't executed yet, and their signatures.
- Once we have a fully signed block we haven't executed yet, we execute all blocks up to that one (even if Highway hasn’t finalized them yet).

**Comment by piotr-dziubecki** [comment]
@xcthulhu - is this still relevant?

**Comment by cspramit** [comment]
@fizyk20 @xcthulhu followup to @piotr-dziubecki question

**Comment by RitaMAllenCA** [comment]
We will close as Zug is replacing Highway, and this is no longer relevant for Zug
