### ISSUE TITLE
Block Body Must Support Secure Download Of Deploys Only

### ISSUE THREAD

**Issue by cspramit** [casper-network/casper-node#1497]
In order for fast sync to support replay attack mitigation, it must be able to securely download deploys.

However, the fast sync must also be extensible and not download the whole block (so that we can add additional functionality later).

The proposed solution is to change how block body hashes are computed.  The new way of hashing them would allow us to provide Merkle proofs when downloading fragments of a block body.

**Comment by fizyk20** [comment]
Should we consider this done, as it is on the `feat-fast-sync` branch and will get merged to `dev` together with the whole fast sync code? @cspramit @xcthulhu
