### ISSUE TITLE
Spurious nctl upgrade test failure

### ISSUE THREAD

**Issue by Fraser999** [casper-network/casper-node#1499]
While running the `upgrade_scenario_01.sh` nctl upgrade test via `ci/nctl_upgrade.sh`, it failed, exiting during [step 08](https://github.com/casper-network/casper-node/blob/9500e83aa9a88a35fff241d34b65e12f56daf406/utils/nctl/sh/scenarios-upgrades/upgrade_scenario_01.sh#L248) with the following output:

```
2021-05-26T15:33:59.885827 [INFO] [127865] NCTL :: ERROR :: protocol upgrade failure - >= nodes are not all at same root hash
2021-05-26T15:33:59.886857 [INFO] [127865] NCTL :: ERROR :: 4  :: HASH = null :: N1 HASH = 12d51116b53e93cbe4bb4902dc766ffbbc7436bcf33daa4352f4ad9fc12c3be2
```

However, the nctl network was still running, and after checking all nodes' statuses (via `nctl-view-node-status`) it seems that all 10 nodes were indeed running and healthy with node 4 not having stalled.

At the time of the failure, there was no log message stating which block hash was used to check the state root hash, but such a line has since been added.  If we see this failure again outside of CI, we should be able to query the running network for the specific block and get further info on the reason for the nctl test to have failed.

In the meantime, it might be worth considering capturing and adding further output to nctl in case this fails in CI.  E.g. before exiting, we might be able to first print the output of `get-block` for this block from all the nodes.

The most likely explanation seems to be that node-1 was somewhat ahead of node-4 in terms of chain progression, and when asked for its latest block, provided a block which node-4 had not yet processed and hence was briefly unable to provide.

**Comment by Fraser999** [comment]
I've been able replicate locally, and it does appear that the issue is simply that node-1 is 
a block ahead of at least one other node.  For the node which caused the test to fail, I was able to get the block and confirm the state root hash was as expected almost immediately after the test failed.

**Comment by TomVasile** [comment]
As discussed in the Testing Huddle, I wrapped the command in question in a retry in #1488.
