### ISSUE TITLE
Apply standstill alert only for joining nodes.

### ISSUE THREAD

**Issue by afck** [casper-network/casper-node#1501]
We addressed two scenarios with somewhat conflicting solutions:

**Scenario 1**: 34% of the validators go temporarily offline. During that time, the remaining nodes cannot finalize anything, so the units they add to the protocol state are not very useful.

**Solution 1**: If 34% haven't created a message for a while we go into "pause mode", where instead of new units we only send ping messages. As soon as we receive pings from 67% again, we resume creating units. That way the protocol state doesn't unnecessarily grow during the outage.

**Scenario 2**: A joining node is badly connected and fails syncing its protocol state.

**Solution 2**: We have a "standstill timeout" after which we once request our peers protocol states, and if after another timeout we still haven't added any new units, we shutdown: After a restart the connections may be better.

The problem is that solution 2 causes all nodes in the network to restart if the outage in scenario 1 takes too long. During the restart they lose their protocol state, so the only way to recover is an emergency restart.

Let's apply the standstill timeout only once, for a newly joining node, so that a long running node will never shutdown due to standstill.

**Comment by xcthulhu** [comment]
Closed by #1656
