### ISSUE TITLE
Stalled node after upgrade

### ISSUE THREAD

**Issue by Fraser999** [casper-network/casper-node#1509]
While running an nctl upgrade test, one of the nodes (node-2) stalled after being upgraded from `release-1.2` to the code in #1508.

This is likely the same issue as #1496.

[Logs of all 5 nodes attached along with the config files for node 1](https://app.zenhub.com/files/263892105/8fd7b3a2-e044-4075-bf15-60a6dd84d159/download).

**Comment by marc-casperlabs** [comment]
#1511 is the first attempt of fixing this issue.

**Comment by marc-casperlabs** [comment]
This should now be covered by upgrade tests run in the CI, so this is considered done until proven otherwise.
