### ISSUE TITLE
Investigate avoiding error log by warp

### ISSUE THREAD

**Issue by Fraser999** [casper-network/casper-node#1514]
If we send a JSON-RPC request to a node, under some circumstances that can trigger a slew of error lines in the log output, the source being the `warp` crate.

For example, after spinning up an nctl testnet locally, if I send the following request with an invalid `params` type

```json
curl -X POST -H 'Content-Type: application/json' -d '{"jsonrpc": "2.0","method": "chain_get_block","params": {1, 2},"id": 1}' 'localhost:40101/rpc'
```

then I get a correct response from the node, but the node adds 33 `request body already taken in previous filter` error lines in quick succession.

We should investigate whether there's a reasonable way to avoid triggering this `warp` error or not.

Note that this ticket is timeboxed as the log errors can be filtered out if required, and don't appear to indicate an actual problem with how the requests are currently handled.

**Comment by darthsiroftardis** [comment]
Did some initial investigation, I found the function resposible for generating the log messages: https://github.com/seanmonstar/warp/blob/5a5dba04053f7b1a04fee514797422c1c6214f81/src/filters/body.rs#L28-L35

I followed the trail, it gets called by the `warp_json_rpc` crate and is being used in here: https://github.com/AtsukiTak/warp-json-rpc/blob/0146c3e11c4ac37dc0f69b6e6865577b1d60b18e/src/filters.rs#L23-L42

We in turn call it with creating the `json_filters` https://github.com/casper-network/casper-node/blob/eb4a2d52385d13c57f47631db565cacd97a6a118/node/src/components/rpc_server/rpcs.rs#L103 

It looks pretty baked in and buried into the crate, there isn't a simple fix available IMO.
