### ISSUE TITLE
Mark known faulty validators when initializing eras.

### ISSUE THREAD

**Issue by afck** [casper-network/casper-node#1516]
We have two cross-era equivocation handling mechanisms:
* If a validator was known to be faulty by the previous switch block, we ban them in the next era and don't accept any of their messages. ([Currently deactivated](https://github.com/casper-network/casper-node/blob/a2d6511d17aa7df75a633542d207c280a775248e/node/src/components/consensus/era_supervisor.rs#L1056).)
* If a validator equivocates in a recent era, we start citing them as `Faulty` in all future eras as well, as if they had equivocated there, too.

Even after re-enabling banning, this still leaves a gap between the creation of the switch block and the initialization of the next era. So:

When initializing a new era, we should immediately mark everyone as `Faulty` who equivocated in the past `bonded_eras()` eras. The implementation is probably as easy as adding this to `EraSupervisor::new_era`:

```diff
diff --git a/node/src/components/consensus/era_supervisor.rs b/node/src/components/consensus/era_supervisor.rs
index d11573894..9d5cf7540 100644
--- a/node/src/components/consensus/era_supervisor.rs
+++ b/node/src/components/consensus/era_supervisor.rs
@@ -348,6 +348,15 @@ where
             now,
         );
 
+        for past_era_id in self.iter_past_other(era_id, self.bonded_eras()) {
+            for pub_key in self.active_eras[&past_era_id]
+                .consensus
+                .validators_with_evidence()
+            {
+                consensus.mark_faulty(pub_key);
+            }
+        }
+
         if should_activate {
             let secret = Keypair::new(self.secret_signing_key.clone(), our_id.clone());
             outcomes.extend(consensus.activate_validator(
```

The hard part is writing tests for it.

Also related is #1538: If that is done before this issue, it shouldn't be `bonded_eras()`, of course, and just the auction delay instead.

**Comment by xcthulhu** [comment]
Closed with #1607
