### ISSUE TITLE
Re-enable banning equivocators.

### ISSUE THREAD

**Issue by afck** [casper-network/casper-node#1520]
[Banning is currently disabled as all equivocators are reported in the `inactive` field instead of `equivocators`.](https://github.com/casper-network/casper-node/blob/a2d6511d17aa7df75a633542d207c280a775248e/node/src/components/consensus/era_supervisor.rs#L1056)
We need to put them back into `equivocators` so that they are banned in all future eras, even before eviction becomes effective. Since the plan is to not re-enable slashing, the EE should then treat equivocators the same as inactive validators, and only evict them.

See #1516 for more details.

**Comment by cspramit** [comment]
Scenario to test - 
Equivocate early in era N; verify that in era N + 1 it's never the proposer and receives 0 rewards.
(Not sure if we have a way to check that it also was never assigned a proposer slot in era N + 1?)

**Comment by xcthulhu** [comment]
@cspramit You are right!  We need to figure out the testing story here.

**Comment by cspramit** [comment]
@xcthulhu correct Matt, we scoped this and another doppelganger detection via - https://app.zenhub.com/workspaces/engineering-60953fafb1945f0011a3592d/issues/casper-network/casper-test/10
but currently we are only including the doppelganger scenario in malicious node
