### ISSUE TITLE
Add EffectBuilder::get_consensus_validator_info.

### ISSUE THREAD

**Issue by afck** [casper-network/casper-node#1526]
`EffectBuilder::get_consensus_validator_info` should return a map, keyed by the public key of each current and recent validator. The value should be a list of status change events, including the eras in which they occurred:

* Were they added to the validator set?
* Did they equivocate?
* Were they inactive?
* Were they excluded from the proposer sequence?
* Were they banned?
* Were they removed from the validator set?

This is meant to be used in a new endpoint or to add data to the `status` endpoint, to make this information more accessible.

**Comment by xcthulhu** [comment]
@cspramit @EdHastingsCasperLabs @Fraser999 @piotr-dziubecki Hey! Not sure about what the next steps are here. Based on [this comment][1], should we make another ticket?

[1]: https://github.com/casper-network/casper-node/pull/1540/files#r647811797

**Comment by cspramit** [comment]
@xcthulhu yes create another ticket - closed this
