### ISSUE TITLE
Equivocators are remembered for one unbonding period.

### ISSUE THREAD

**Issue by afck** [casper-network/casper-node#1538]
Consensus remembers your equivocation for one whole `unbonding_delay - auction_delay`. If you re-enable your bid within that period, you will get evicted again immediately, for your old equivocation.

After being evicted, it should not be possible to get evicted _again_ for any equivocation from before that eviction.

Alternatively, the period how long you can get accused after equivocating could be reduced: It doesn't _have_ to be the full time where the stake is bonded. 

~Consensus remembers your equivocation for one whole `unbonding_delay - auction_delay` and won't let you participate will accuse you again if you re-enable your bid.~

~It should only remember them for one `auction_delay`: After that they will be evicted anyway. If they reactivate their bid, the current mechanism could prevent them from participating for a few additional eras.~

~Originally the intention was to slash equivocators, so this would usually have been fine. But either way, the correct number for consensus-internal banning is just the `auction_delay`: After that the ban becomes official on-chain, consensus doesn't have to treat them as a special case anymore.~

~The same should apply to inactive validators, which only need to be explicitly excluded from the proposer sequence for one `auction_delay`.~ ([This is already the case.](https://github.com/casper-network/casper-node/blob/02fc6b9f9e3f099d09d9a49f7c00758884097c15/node/src/components/consensus/era_supervisor.rs#L564))

**Comment by xcthulhu** [comment]
Superseded by #1915
