### ISSUE TITLE
casper-updater should update cargo-casper

### ISSUE THREAD

**Issue by Fraser999** [casper-network/casper-node#1543]
`cargo-casper` needs to be updated via `casper-updater` so that manifest files which `cargo-casper` generates in new sample projects specify the correct version of our published crates.

**Comment by nilz3ro** [comment]
Reviewed and tested this with @Fraser999. Could not reproduce this bug, we verified that the updater and the `cargo-casper` crate are working correctly and that the files produced by `cargo-casper` are up-to-date.

**Comment by cspramit** [comment]
wontfix as per comments by Austin
