### ISSUE TITLE
Backport Changes From Fast-Sync To Dev

### ISSUE THREAD

**Issue by xcthulhu** [casper-network/casper-node#1545]
Changes from Fast-Sync need to be backported to `dev`.  In particular the following components are to be backported:

 - Storage
 - The BlockExecutor

**Comment by xcthulhu** [comment]
We're going to need to merge and squash #1547 before tackling this

**Comment by piotr-dziubecki** [comment]
@Fraser999 @fizyk20 do we need to revert this one?

**Comment by fizyk20** [comment]
@piotr-dziubecki If we're not including Fast Sync in 1.4, then I'd say unfortunately yes :grimacing:

**Comment by cspramit** [comment]
@piotr-dziubecki - as per @Fraser999 @fizyk20 - non-impactful merge to 1.4
