### ISSUE TITLE
Client put-deploy and make-deploy subcommands should handle transfers

### ISSUE THREAD

**Issue by Fraser999** [casper-network/casper-node#1572]
The `put-deploy` and `make-deploy` subcommands should allow for the creation of an `ExecutableDeployItem::Transfer`.

**Comment by cspramit** [comment]
@nilz3ro @Fraser999 whats the PR for this?

**Comment by nilz3ro** [comment]
@cspramit https://github.com/casper-network/casper-node/pull/1625
