### ISSUE TITLE
Add an RPC method returning % of weight of finality signatures attesting to a deploy/block

### ISSUE THREAD

**Issue by goral09** [casper-network/casper-node#1595]
There needs to exist a simple way for clients to detect whether a particular deploy/block is safe to trust. There is a _finalization_ phenomenon inside Consensus that occurs when enough validators have formed a quorum – had seen each other see a particular block. This has a particular disadvantage in that a client has to trust the node that told it about the finalization event since it [the client] itself can't observe the finality. There is a way for clients to detect finality in a trustless way – finality signatures. 

Add an RPC endpoint `get_finalization_status(block_hash|deploy_hash)` returning:
* a value between 0 and 100 which is a % (by weight) of validators from which we have received finality signatures for that particular block/deploy,
* set of the finality signatures that sign over that block

**WARNING:** Just because node is returning finality signatures now it doesn't mean that any node can be trusted blindly. Clients should verify that signatures are correct and indeed created by active validators from the proper era. This can be done by cross-checking with another node(s) and cryptographically verifying the signatures correctness in the client.

**NOTE:** In the spirit of not adding non-essential, client-facing functionalities to the node itself, this particular feature could (and probably should) be implemented in a 2nd layer service that consumes the event stream.

**Comment by cspramit** [comment]
@Fraser999  should we do this - if yes (need to add to epic)
