### ISSUE TITLE
Minimal Proofs of Sufficient Validator Stake

### ISSUE THREAD

**Issue by xcthulhu** [casper-network/casper-node#1622]
Casper should support having token representation on other blockchains.

This could be done via an [SPV][1] smart contract running on another blockchain.

Such a smart contract will need to use finality signatures to track the state of Casper.

It may trust the switch block for era `N` and need to verify proofs for the switch block of era `N+2`.

With [CEP-41][2], it will be possible to download and verify the top ~3 validators for the switch block for era `N+1`. But to use those to verify the switch block for era `N+2`, we'd need to know the total stake.

In order to support this use case the block body would need to be extended to include the total stake.

[1]: https://en.bitcoin.it/wiki/Scalability#Simplified_payment_verification
[2]: https://github.com/casper-network/ceps/blob/master/text/0041-extensible-block-body.md

**Comment by devendran-m** [comment]
Closed as part of triage on 23rd Sep.
