### ISSUE TITLE
Upgradability of StoredValue

### ISSUE THREAD

**Issue by mpapierski** [casper-network/casper-node#1626]
Related to #1487 (and follow-up of #1531)

This task is tracking a continuation of work started in #1531. To be able to extend (or shrink) the data structures we need easy upgradability of values referenced from `StoredValue` as currently defined here https://github.com/casper-network/casper-node/blob/1873b237b0356d6fd9eb8ac3b28c1c0bbe0c4d9c/execution_engine/src/shared/stored_value.rs#L29-L41

For example, the current implementation of `ToBytes for Account` or `FromBytes for Account` does not allow extending the data structure. We can use a similar pattern as defined in #1531 to write key and length-delimited value pairs.

**Comment by piotr-dziubecki** [comment]
@mpapierski please consult this with @Fraser999 also in the context of the target release. For now we move it to 1.5
