### ISSUE TITLE
casper-node-launcher :  Memory usage keeps growing

### ISSUE THREAD

**Issue by mabahma** [casper-network/casper-node#1653]
I'm running a node in testnet under ubuntu 20.04 (32 GB RAM)
Only casper node is running on the server.
I've monitored memory usage during a week.
At random time every day, i was issuing :  sudo service  casper-node-launcher  status
I noticed the memory usage grows over time. It grows by average 0.5 -1GB every day
last run gave : 

casper-node-launcher.service - Casper Node Launcher
     Loaded: loaded (/lib/systemd/system/casper-node-launcher.service; enabled; vendor preset: enabled)
     Active: active (running) since Fri 2021-06-11 20:35:27 UTC; 2 weeks 6 days ago
       Docs: https://docs.casperlabs.io
   Main PID: 955 (casper-node-lau)
      Tasks: 11 (limit: 38373)
     **Memory: 16.3G**
     CGroup: /system.slice/casper-node-launcher.service
             ├─ 955 /usr/bin/casper-node-launcher
             └─1044 /var/lib/casper/bin/1_2_0/casper-node validator /etc/casper/1_2_0/config.toml

16.3GB : That's huge !
Is that normal and why it keeps growing like this?What will happen when it will take whole memory?

**Comment by sacherjj** [comment]
Do you have your IP address that we can look at metrics?

**Comment by dwerner** [comment]
`systemd` can report a larger amount of consumed memory than our process is using at a given time. This might be critical or might not.

[See relevant superuser question.](https://superuser.com/questions/1431117/why-does-systemctl-show-high-memory-usage-when-top-and-htop-show-much-less)

Also, we use a custom memory allocator (`jemalloc`) that helps track the overall use from within the process and surfaces that on the node's metrics endpoint.  That allows you to see how much memory the process is using, but not in much detail. `jemalloc` does hold on to memory depending on it's tuning. You can see how `jemalloc` can be tuned [here](https://github.com/jemalloc/jemalloc/blob/dev/TUNING.md) but I would warn that any changes here could crash or slow the node.

If you are interested in exploring the issue, I'd recommend tracing the process with a tool that allows capture of a trace file which can be shared and visualized to see what is allocating memory, and not releasing it, or if this is simply resident to the allocator. For that I like to use the excellent [heaptrack](https://github.com/KDE/heaptrack) for both capture and visualization.

I'll close this for now - if you have any more questions or if you have a heaptrack/other trace file you'd like to share I'm happy to discuss further.
