### ISSUE TITLE
High payment amount results in a stuck deploy

### ISSUE THREAD

**Issue by AlexanderLimonov** [casper-network/casper-node#1677]
PROBLEM:
Deploys with gas payment amounts set to anything above 10,000 CSPR (block gas limit) get stuck forever without failing or succeeding, with no errors or warnings for the user.

TO REPRODUCE:
Launch an NCTL network built from 1.2 or the dev branch, submit a deploy with payment amount set to 10,000,000,000,001 motes.

**Comment by cspramit** [comment]
@AlexanderLimonov  does this kill the network??

**Comment by AlexanderLimonov** [comment]
> @AlexanderLimonov  does this kill the network??

No, everything continues working normally, but the deploy is stuck forever (other deploys will still be processed, it doesn't block anything)

**Comment by cspramit** [comment]
Add to deploy acceptor Epic @cspramit @piotr-dziubecki
