### ISSUE TITLE
Make standstill shutdown optional.

### ISSUE THREAD

**Issue by afck** [casper-network/casper-node#1680]
Add a configuration option to disable the automatic shutdown entirely, and make that the default.

**Comment by afck** [comment]
To summarize the current logic:

* Whenever an era is initialized, the _progress alert_ timer is started, with `standstill_timeout`.
* When the progress alert timer fires, the node requests the latest protocol state from its peers, except if:
  - the protocol state has changed since the era was initialized (evidence or units were received),
  - the era's last block has already been finalized, or
  - the era is already in evidence-only mode.
* After that, the "standstill alert" timer is initialized and fires periodically, every `standstill_timeout`.
* When the standstill alert timer fires the node shuts down, except if:
  - the protocol state has changed since the era was initialized (evidence or units were received),
  - the era's last block has already been finalized, or
  - the era is not the latest one we have initialized.

**Comment by afck** [comment]
Related PRs:
* #1130 — shutdown on standstill alert ([HWY-266](https://casperlabs.atlassian.net/browse/HWY-266))
* #1204 — request protocol state only for latest era
* #1397 — request protocol state only if stalled

**Comment by xcthulhu** [comment]
Closed by #1681
