### ISSUE TITLE
Only Put Finality Signatures for Switch Blocks in Storage

### ISSUE THREAD

**Issue by xcthulhu** [casper-network/casper-node#1683]
In order for a client to establish trust in a block given a historic hash, it only needs finality signatures for switch blocks (and the signatures of the block itself if it is in the current era).

To conserve space we should only store finality signatures for switch blocks in storage.  Finality signatures for recent blocks may be kept in memory.

**Comment by piotr-dziubecki** [comment]
@Fraser999 -> @xcthulhu - should we work on this in Q3?

**Comment by RitaMAllenCA** [comment]
9.5.2023 no longer necessary as we have reduced the size of the auction on disk in 2.0

**Comment by EdHastingsCasperAssociation** [comment]
This should have been closed a very long time ago. The version of fast sync we shipped with 1.5 addressed this (though the implementation is very different than what is suggested here).
