### ISSUE TITLE
Design: better doppelgänger detection

### ISSUE THREAD

**Issue by afck** [casper-network/casper-node#1701]
If a node receives an unknown Highway unit signed by its own key, it knows that it has a doppelgänger: another node with the same key. So it stops creating new units because two active nodes with the same key would inevitably equivocate eventually. The current mechanism is not ideal:

* It's likely that both nodes will shutdown, so the validator will become inactive.
* It often detects the doppelgänger only when it's too late and an equivocation has already happened.

It would be good to have a more reliable mechanism. E.g. a node with a validator key could always announce itself in advance

**Comment by xcthulhu** [comment]
Chatting with @afck, we may desire to implement this outside of Highway in a consensus-mechanism-independent manner.

**Comment by cspramit** [comment]
@afck are making changes , any milestones??
