### ISSUE TITLE
Provide uptime as part of the node's status

### ISSUE THREAD

**Issue by piotr-dziubecki** [casper-network/casper-node#1716]
@Fraser999 commented on [Mon Jul 19 2021](https://github.com/casper-network/Governance/issues/33)

The node's REST and JSON-RPC servers should update their status responses to include an `uptime_seconds` field, which will be a count of whole seconds since the node started.

Each server should have an additional member variable `node_start_instant` which is set via the constructor.  The same instant should be used for each server, which means that the REST server will need to provide a getter for the value so it can be retrieved in order to be passed in to the JSON-RPC server's constructor.

**Comment by rafal-ch** [comment]
@Fraser999 
What about using a `TimeDiff` and let the `uptime` format itself, similarly to the current implementation of `round_length`?

Example snippet from the response:
```
{
-- some fields cut ---
"api_version": "1.0.0",
"round_length": "4s 96ms",
"uptime": "17m 4s"
"next_upgrade": null,
}
```
