### ISSUE TITLE
CEP: Specify criteria for automatic restart

### ISSUE THREAD

**Issue by afck** [casper-network/casper-node#1717]
We repeatedly had to change the rules for automatically restarting the node: On the one hand, for a joining node that gets stuck it can make sense to retry by restarting. On the other hand we don't want validator nodes to shut down while consensus is paused (because too many other validators are already offline) and make things worse.

We should specify the exact criteria for when to shutdown.

To summarize the current logic:

* Whenever an era is initialized, the _progress alert_ timer is started, with `standstill_timeout`.
* When the progress alert timer fires, the node requests the latest protocol state from its peers, except if:
  - the protocol state has changed since the era was initialized (evidence or units were received),
  - the era's last block has already been finalized, or
  - the era is already in evidence-only mode.
* After that, _if_ `shutdown_on_standstill = true`, the "standstill alert" timer is initialized and fires periodically, every `standstill_timeout`.
* When the standstill alert timer fires the node shuts down, except if:
  - the protocol state has changed since the era was initialized (evidence or units were received),
  - the era's last block has already been finalized, or
  - the era is not the latest one we have initialized.

Some ideas for improvements:

* Distinguish between joining and upgrading: We might want to restart only if we're joining.
* Don't consider yourself stuck if you receive enough pings: That just means the network is in pause mode.

Related PRs:

* #1130 — shutdown on standstill alert ([HWY-266](https://casperlabs.atlassian.net/browse/HWY-266))
* #1204 — request protocol state only for latest era
* #1397 — request protocol state only if stalled
* #1681 — add `shutdown_on_standstill` option with default `false`

**Comment by afck** [comment]
Also keep in mind that systemd won't restart if the node shuts down three times within 30 seconds. (Configurable.)

**Comment by xcthulhu** [comment]
Subsumed by #1914
