### ISSUE TITLE
Drop `state` Database

### ISSUE THREAD

**Issue by xcthulhu** [casper-network/casper-node#1730]
Fast sync does not need the `state` database in LMDB, so a data migration to drop that database is necessary.

**Comment by xcthulhu** [comment]
Note that this is not necessary for the 1.4.0 release, but will be desirable later for disc recovery.

**Comment by goral09** [comment]
It's not going to recover much since we're deleting entries in the `state` database when we're done syncing https://github.com/casper-network/casper-node/blob/release-1.3.2/node/src/components/linear_chain_sync.rs#L968

**Comment by xcthulhu** [comment]
This database was removed in #1917
