### ISSUE TITLE
Small network Wasm transfer pending not executed

### ISSUE THREAD

**Issue by cspramit** [casper-network/casper-node#1756]
Scenario 3: Rate Limits with Load directed at Validators
Casper Node: e9b28da7e
Network : 5V + 5NV + 5RO
Instance: t3a.large
Dashboard:
https://grafana.casperlabs.io/goto/Z0flowink
https://grafana.casperlabs.io/goto/C4UuTwmnz
Config Override:
{'config': {'max_outgoing_byte_rate_non_validators': 6553600, 'max_incoming_message_rate_non_validators': 3000, 'enable_mem_deduplication': 'true'}, 'chainspec': {}}
Logs: http://genesis.casperlabs.io/ajith-kaboom-130/casper-node-logs/16Jul21-5V5NV-all-limits-validator-nodes-e9b28da7e/16072021_0415/log_download_list.txt
Observations:
- network stable
- load targeted to ONLY validator nodes with stest
- 30k transfers completed
- :x:  **3.6k wasm transfers not fully executed. ~200 were pending/not-executed**
- 5 joiner nodes successfully synced
- 1 out of 5 reloaded twice to sync to height
- :x: SSE reports shows empty wasm blocks with workload executions
-----------------------------------------------------------------------------------------------
Scenario 3: Rate Limits with Load directed at Non-Validators
Casper Node: e9b28da7e
Network : 5V + 5NV + 5RO
Instance: t3a.large
Dashboard:
https://grafana.casperlabs.io/goto/Qhkuqwmnz
https://grafana.casperlabs.io/goto/SHeuqQm7z
Observations:
- network stable
- load targeted to ONLY non-validator nodes with stest
- 30k transfers completed
- :x:  3.6k wasm transfers not fully executed. ~200 were pending/not-executed
- 5 joiner nodes successfully synced
- :x: SSE reports shows empty wasm blocks with workload executions (edited)

**Comment by Fraser999** [comment]
This was resolved by reverting the usage of the deploy gossiper announcement.
