### ISSUE TITLE
Docs update: execution_engine/storage

### ISSUE THREAD

**Issue by mpapierski** [casper-network/casper-node#1768]
Add or update existing rust docs in a `storage` rust module in EE:

- [x] storage/error
- [x] storage/global_state
- [ ] storage/protocol_data_store
- [x] storage/store
- [x] storage/transaction_source
- [x] storage/trie
- [x] storage/trie_store
- [x] storage/*

**Comment by dwerner** [comment]
Opting not to document `protocol_data` and `protocol_data_store` because those modules should be removed in #1814

**Comment by dwerner** [comment]
merged to dev in https://github.com/casper-network/casper-node/pull/1848

**Comment by cspramit** [comment]
@dwerner closing issue since merged please note though " storage/protocol_data_store" is unchecked
