### ISSUE TITLE
Make external EE docs up-to-date

### ISSUE THREAD

**Issue by mpapierski** [casper-network/casper-node#1769]
Currently, EE-related external docs are published under https://docs.casperlabs.io/en/latest/implementation/execution-semantics.html and related pages.

This task is about re-reviewing the doc, and making sure it contains all the necessary up-to-date information for developers to understand the execution semantics.

References to specs found in the code that should be updated and externalized:

- https://casperlabs.atlassian.net/wiki/spaces/EN/pages/123404576/Payment+code+execution+specification (referenced from `execution_result.rs` etc)

**Comment by mpapierski** [comment]
We're up to date after matching old internal specs in confluence and comparing them to our docs in-depth. We're up to date (and where we're not, we're pointing at the source). I talked to @ipopescu about the documentation process, and I pointed out outdated ERC20 tutorial as part of casper-network/docs#345

**Comment by ipopescu** [comment]
Tutorial updates are in [PR 359](https://github.com/casper-network/docs/pull/359).
