### ISSUE TITLE
Joining node stuck after sync in sync_upgrade_test

### ISSUE THREAD

**Issue by fizyk20** [casper-network/casper-node#1781]
Running sync_upgrade_test fails with node 6 getting stuck after the linear chain is synchronized up to the current era.

**Comment by cspramit** [comment]
@fizyk20 is there a PR for the fix?

**Comment by fizyk20** [comment]
@cspramit I don't remember, sorry :grimacing: 
#1773 and #1780 were merged around the time I moved this issue to "Done" and they concerned a part of the code that might have affected this, so maybe it was one of them, but I can't be sure at this point.
