### ISSUE TITLE
Remove `enable_bonding` from config-example.toml.

### ISSUE THREAD

**Issue by nilz3ro** [casper-network/casper-node#1786]
Remove the commented configuration option `enable_bonding` ([these lines](https://github.com/casper-network/casper-node/blob/release-1.3.1/resources/production/config-example.toml#L301-L302)) from `resources/production/config-example.toml`.

If an operator tries uncomment the line, the node will crash on startup.

**Comment by cspramit** [comment]
Should a change in example file impact the node, had the change been in config.toml i can see but how in config-example.toml
