### ISSUE TITLE
GlobalState upgrade regression test

### ISSUE THREAD

**Issue by mpapierski** [casper-network/casper-node#1791]
This task is about creating a regression test using an LMDB fixture that is pre-loaded with all existing StoredValue variants, auction eras, transfers, and other global state values. A test would use a pre-generated fixture and try to execute/query existing data to detect regressions.

The code to generate pre-existing data in an LMDB fixture could be based on code found in https://github.com/casper-network/casper-node/compare/dev...mpapierski:gh-1767-upgrade-pre-existing-state

**Comment by cspramit** [comment]
@mpapierski has a pr marked done - should this be closed
