### ISSUE TITLE
Change log level to debug

### ISSUE THREAD

**Issue by piotr-dziubecki** [casper-network/casper-node#1801]
We need to specify which logs messages will go to debug level.

@cspramit  -> For example nodes on different networks are trying to connect and giving these messages. 

CC @Fraser999

**Comment by cspramit** [comment]
for context - https://casperlabs-team.slack.com/archives/C01ULKL8G8J/p1627479684139800

**Comment by Fraser999** [comment]
See also https://casperlabs-team.slack.com/archives/C01ULKL8G8J/p1627479684139800
