### ISSUE TITLE
Fix current npm audit vulnerabilities

### ISSUE THREAD

**Issue by mpapierski** [casper-network/casper-node#1803]
Fix vulnerabilities reported by `npm audit`. 

Current status at a time of writing this issue:

```
$ npm audit
14 vulnerabilities (1 low, 5 moderate, 8 high)
```

Some of the changes might require updating the supported AssemblyScript version to newer (currently supported: 0.10, new release: 0.19).

See also #1802

**Comment by cspramit** [comment]
@cspramit get back with Jan and Michal

**Comment by piotr-dziubecki** [comment]
https://github.com/casper-network/casper-node/pull/2122

**Comment by bradjohnl** [comment]
https://github.com/casper-network/casper-node/pull/2699
