### ISSUE TITLE
Query dictionary item logic should be moved to EE

### ISSUE THREAD

**Issue by mpapierski** [casper-network/casper-node#1812]
Currently `test_support` and RPC for querying dictionary items have duplicated logic. This task is about moving this logic into EE as a separate method on EngineState. Historically we also used to put more methods on EngineState for specific queries i.e. get balance, get era validators and so on.

After the change both `test_support` and RPC can use this method, and the logic to resolve account/contract/seed URef etc logic would live in one place.

See also #1807 and #1674

**Comment by cspramit** [comment]
@mpapierski discuss with @EdHastingsCasperLabs

**Comment by devendran-m** [comment]
Won't do.
