### ISSUE TITLE
Consistent use of durations in configs and chainspec

### ISSUE THREAD

**Issue by piotr-dziubecki** [casper-network/casper-node#1821]
CC @Fraser999

**Comment by Fraser999** [comment]
We have two configuration files which a node requires to operate: [a chainspec.toml](https://github.com/casper-network/casper-node/blob/dev/resources/production/chainspec.toml) and [a config.toml](https://github.com/casper-network/casper-node/blob/dev/resources/production/config-example.toml).

There is an inconsistent style in these for representing durations, and this should be fixed.  We should consistently use [the humantime crate for parsing durations](https://docs.rs/humantime/2.1.0/humantime/fn.parse_duration.html), and use the moderately-abbreviated form of each suffix (e.g. `2hr`, not `2h` nor `2hours`)

In the Rust code, that means that we need to change the corresponding types from integers to our own [`TimeDiff` newtype](https://github.com/casper-network/casper-node/blob/dev/node/src/types/timestamp.rs#L208).  The relevant configuration structs can be traced from [the participating reactor's `Config` struct](https://github.com/casper-network/casper-node/blob/dev/node/src/reactor/participating/config.rs).

Note that we have [a test copy of the config.toml file](https://github.com/casper-network/casper-node/blob/dev/resources/local/config.toml) which will need to be updated too.

**Comment by rafal-ch** [comment]
The following candidates to update have been identified:

```
1. SmallNetwork::gossip_interval
2. Gossip::finished_entry_duration_secs
3. Gossip::gossip_request_timeout_secs
4. Gossip::get_remainder_timeout_secs
5. Fetcher::get_from_peer_timeout
```

**Comment by rafal-ch** [comment]
Duration suffixes to be used by default and in examples:

- "ms"
- "sec"
- "min"
- "hr"
- "day" or "days"
- "month" or "months"
- "year" or "years"
