### ISSUE TITLE
Corrupt NCTL linebreaks

### ISSUE THREAD

**Issue by AlexanderLimonov** [casper-network/casper-node#1825]
PROBLEM:
On release-1.3.1 branch, running the NCTL activation script results in the following:
```
: command not found
: command not found
: command not found
: command not found
: command not found
: command not found
: No such file or directorysperLabs/casper-node/utils/nctl
: command not found
: command not found
: command not found
: command not found
: command not found
: command not found
: command not found
: command not found
: command not found
: command not found
: command not found
: command not found
: command not found
: command not found
: command not found
: command not found
: command not found
: command not found
```
The problem seem to be Windows-type linebreaks, and everything is right again after applying the dos2unix utility to every script

**Comment by cspramit** [comment]
@AlexanderLimonov please provide more details like OS, steps to reproduce etc

**Comment by AlexanderLimonov** [comment]
@cspramit, I would close this out for now, because it might be an issue with some of the software I use (CLion, in particular), will check again with 1.4
