### ISSUE TITLE
Remove GenesisConfig/RunGenesisRequest from EE

### ISSUE THREAD

**Issue by mpapierski** [casper-network/casper-node#1829]
This structure seems to be used only on EE tests but `EngineState`'s API accepts `ExecConfig` (which as for now is part of `GenesisConfig` struct). After the unused `GenesisConfig` is gone we can safely rename `ExecConfig` into the `GenesisConfig` or `GenesisRequest` because it is what it is - a configuration object passed to a `commit_genesis` method. 

A `RunGenesisRequest` (which contains `GenesisConfig`) also is only referenced from within EE integration tests. This is also not necessary considering that `commit_genesis`.

See the genesis API: https://github.com/casper-network/casper-node/blob/79ea25b8ee2138b312ae68240d1b47540ef853d2/execution_engine/src/core/engine_state/mod.rs#L132-L138
Genesis config: https://github.com/casper-network/casper-node/blob/a6ee5ff40d7c5a3bbd1b67d4d1b7d5c44f053254/execution_engine/src/core/engine_state/genesis.rs#L424-L430

Discovered and ticketed as part of #1764

**Comment by devendran-m** [comment]
Not valid.
