### ISSUE TITLE
Allow to get "self-address".

### ISSUE THREAD

**Issue by piotr-dziubecki** [casper-network/casper-node#1855]
@zie1ony please provide the description.

**Comment by goral09** [comment]
Isn't that what `get_callstack()[0]` returns? @mpapierski

**Comment by mpapierski** [comment]
> 
> 
> Isn't that what `get_callstack()[0]` returns? @mpapierski

More like `get_callstack().last().unwrap()`. This information is pushed at the end

**Comment by goral09** [comment]
Anyway, it basically means @piotr-dziubecki that starting from version 1.3.X this feature should already be available.
