### ISSUE TITLE
ContractPackageHash::from(&str)

### ISSUE THREAD

**Issue by piotr-dziubecki** [casper-network/casper-node#1856]
more generally, a way to take the string repr of a hash and turn it into the strong type for that kind of hash (not a Key:: of that hash)

**Comment by EdHastingsCasperAssociation** [comment]
more generally, a way to take the string repr of a hash and turn it into the strong type for that kind of hash (not a Key:: of that hash)

**Comment by cspramit** [comment]
This now moved to 1.5??

**Comment by Fraser999** [comment]
Closed in favour of #2257
