### ISSUE TITLE
Write NCTL tests for Upgrade - nodes lagging upgrade/stage- Protocol

### ISSUE THREAD

**Issue by cspramit** [casper-network/casper-node#1864]
In a 10 node network
Scenario 1:

Stage 8 of 10 nodes and upgrade 8  nodes (validator + non validator)
Let network move forward 2 eras
Post activation point
Now stage the other 2 nodes (Validator + non Validator)
Get trusted_hash into config.toml of the new stage on 2 nodes
Restart 2 nodes
Verify these 2 nodes upgraded and reach same height as rest of the network.
Scenario 2:

Stage 8 of the 10 nodes and upgrade these 8 nodes (Validator + non Validator)
Let network move forward 7 eras (no longer has consensus info for upgrade point)
Stage the remaining 2 nodes
Get trusted_hash into config.toml of the new stage on 2 nodes
Restart 2 nodes
Upgrade and verify upgrades successfully and catches up to the latest network height

**Comment by TomVasile** [comment]
blocked by: https://app.zenhub.com/workspaces/cn-sre-60d363546afb85000e491ff6/issues/casper-network/sre/112

**Comment by TomVasile** [comment]
switching this from 7 era to 10 to account for: https://app.zenhub.com/workspaces/cn-sre-60d363546afb85000e491ff6/issues/casper-network/sre/161

**Comment by piotr-dziubecki** [comment]
https://github.com/casper-network/sre/issues/161 related ticket blocking this issue

**Comment by TomVasile** [comment]
merged: https://github.com/casper-network/casper-node/pull/2106
