### ISSUE TITLE
Permanently Ban Peers

### ISSUE THREAD

**Issue by xcthulhu** [casper-network/casper-node#1875]
Currently, when a peer misbehaves we can ban them. This is done via `NodeId`. But they can still reconnect.

We need the capability to permanently ban them.

**Comment by marc-casperlabs** [comment]
@Fraser999  In the initial discussion when implementing bans this was brought up, and I believe for a short time we had this feature. After a while, we fell back on only having 10 minute bans. Should be revert this and go for permanent bans?

Unfortunately I don't remember all the specific arguments to the discussion, sorry :(

**Comment by piotr-dziubecki** [comment]
as per @xcthulhu : We need to permanently ban peers
