### ISSUE TITLE
Explore Responder errors in testing, tune down when appropriate

### ISSUE THREAD

**Issue by dwerner** [casper-network/casper-node#1897]
After adding https://github.com/casper-network/casper-node/pull/1894, @Fraser999 brought up that we should:
    - Investigate the most common causes of this issue and lifetime of the `Responder`.
    - Tune down the cases where this is not truly deserving of an `error!` log level to `warn!`.

**Comment by dwerner** [comment]
First attempt at this didn't capture the trace context correctly, new PR here https://github.com/casper-network/casper-node/pull/1901

**Comment by marc-casperlabs** [comment]
This should be considered done (see https://github.com/casper-network/casper-node/issues/2207)
