### ISSUE TITLE
Direct auction contract call charges for other system contract calls are misleading.

### ISSUE THREAD

**Issue by mpapierski** [casper-network/casper-node#1902]
Calling auction contract's `add_bid` directly with a standard payment with the amount of 2.5CSPR results in a GasLimit error even though `add_bid` costs 2.5CSPR. 

The "hidden cost" here is that the native auction contract calls for "create_purse," which also calls host mint's implementation that charges for `create` entry point. Also, reported gas cost is for 2.5CSPR (add_bid) but we technically charge for 2.5CSPR + 10k motes (add_bid + create)

Workaround: Currently on mainnet and testnet `create` costs 10k motes, then users should be able to call add_bid by calling payment code with 2.5CSPR + 10k motes.

**Comment by cspramit** [comment]
@mpapierski @piotr-dziubecki - Michal what is the point estimate on this?

**Comment by mpapierski** [comment]
Closed by #2205
