### ISSUE TITLE
Doppelgänger detection is less likely because we disconnect from the doppelgänger.

### ISSUE THREAD

**Issue by afck** [casper-network/casper-node#1904]
The networking component will immediately disconnect if a node with the same secret key tries to connect to us (assuming it's ourselves). This means the current consensus doppelgänger detection will almost never be triggered.

**Comment by afck** [comment]
(Related comment: https://github.com/casper-network/casper-test/issues/10#issuecomment-896782279)

**Comment by cspramit** [comment]
@afck is this 1.4.0 as well - adding the milestone and release - if not please change it

**Comment by afck** [comment]
I don't know, it depends on what we could do on the networking side: E.g. can we just do detection of _directly connected_ doppelgängers there instead of in consensus? I.e. if someone connects to us and proves that they have the same secret key as we do, can we inform the consensus component about it so it deactivates?

**Comment by piotr-dziubecki** [comment]
@afck please meet with @marc-casperlabs and @Fraser999 and decide on this.

**Comment by afck** [comment]
We just met:

> will immediately disconnect if a node with the same secret key tries to connect to us

Turns out this isn't true! Closing.
