### ISSUE TITLE
Message Format Envelope & Caching Fetcher Handlers

### ISSUE THREAD

**Issue by xcthulhu** [casper-network/casper-node#1912]
The deploy caching system in 1.3.0 is incompatible with the changes to the fetcher in the `feat-fast-sync` branch.

Moreover, new complex composite objects that can now be fetched (eg, "blocks with sufficient finality signatures") may also require caching.

Finally, we need the message format to match the at-rest representation of data as closely as possible (in particular, for deploys and tries).  This will require an envelope.

**Comment by xcthulhu** [comment]
The fetchers currently use `bincode`, this needs to be replaced with `bytesrepr`

**Comment by marc-casperlabs** [comment]
#2054 handles the first part of this ticket.

**Comment by Fraser999** [comment]
The bulk of this work has been completed.  The remainder will be handled in a new ticket.
