### ISSUE TITLE
Normalize Block Rewards

### ISSUE THREAD

**Issue by xcthulhu** [casper-network/casper-node#1913]
Rather than burning block rewards for validator downtime, we should normalize them.

**Comment by afck** [comment]
As discussed, we will move the computation out of the consensus component, into the `step` function itself.

**Comment by cspramit** [comment]
@AlexanderLimonov  pls look in

**Comment by afck** [comment]
Won't do. See https://github.com/casper-network/ceps/issues/65#issuecomment-971417369.

**Comment by xcthulhu** [comment]
I have been talking this over with @luis-casper .

Since the auction contract is falling over we need to move to a pull-based system.

This exact simplified reward scheme is assumed in this paper which describes an efficient pull-based scheme:

https://uploads-ssl.webflow.com/5ad71ffeb79acc67c8bcdaba/5ad8d1193a40977462982470_scalable-reward-distribution-paper.pdf

**Comment by afck** [comment]
Is there another issue that tracks this?
Because the pull-based system doesn't require normalized block rewards, so I think this issue here can be closed.
