### ISSUE TITLE
TestContext block time

### ISSUE THREAD

**Issue by deuszex** [casper-network/casper-node#1916]
Currently test_support `TestContext` always has a `blocktime` of zero. This prevents the testing of `blocktime` sensitive contract features via the `TestContext`.

**Comment by MParlikar** [comment]
Let's please prioritize this for 1.5 @piotr-dziubecki

**Comment by piotr-dziubecki** [comment]
CC @Fraser999 for explanation

**Comment by Fraser999** [comment]
#2005 renders this ticket unnecessary, as it replaces the `TestContext` with the more complete `WasmTestBuilder` which it previously wrapped.  Along with the `ExecuteRequestBuilder::with_block_time`, the user has full control of the block time for the purposes of running tests.
