### ISSUE TITLE
Tracking copy transforms should be in insertion order

### ISSUE THREAD

**Issue by piotr-dziubecki** [casper-network/casper-node#1930]
to be consistent ops also.

CC @EdHastingsCasperLabs @goral09

**Comment by EdHastingsCasperAssociation** [comment]
The goal is, downstream from EE the deploy metadata written to storage and also the the json produced from the rpc api and the event produced from the sse should all also be ordered.

**Comment by cspramit** [comment]
@dwerner your PR #1957 should be closed?
