### ISSUE TITLE
Query state via package hash

### ISSUE THREAD

**Issue by piotr-dziubecki** [casper-network/casper-node#1931]
CC @EdHastingsCasperLabs

**Comment by nilz3ro** [comment]
Summary of conversations with @Fraser999 and @mpapierski 
We should be able to use a contract package hash as the base key of a query. When no query path is provided, the contract package will be returned. When a query path is provided, the path will be queried from the latest version of the contract inside the contract package.

**Comment by cspramit** [comment]
@nilz3ro to discuss with @Fraser999

**Comment by piotr-dziubecki** [comment]
This was working as intended. We've added test to prove it.
