### ISSUE TITLE
`block_rewards` should be in motes

### ISSUE THREAD

**Issue by xcthulhu** [casper-network/casper-node#1936]
`Block` contains a `rewards` field that contains a score for each validator. Their reward is _proportional_ to that score, but not identical. It would be more helpful for clients if that field were directly in motes, i.e. it represented the actual rewards.

Just changing that would be a confusing change for users, so maybe we should also rename the field?

**Comment by RitaMAllenCA** [comment]
@AlexanderLimonov @fizyk20 Is this still something we want to do?

**Comment by AlexanderLimonov** [comment]
@RitaMAllenCA mentioned in relevant existing ticket and closing as obsolete
