### ISSUE TITLE
Trie Store 2.0: Remove Extension Nodes

### ISSUE THREAD

**Issue by piotr-dziubecki** [casper-network/casper-node#1944]

**Comment by cspramit** [comment]
@piotr-dziubecki any description pls?

**Comment by afck** [comment]
Is this about the idea of simplifying the trie by merging the [`Extension` and `Node` variants of `Trie`](https://github.com/casper-network/casper-node/blob/788d43e0879015eff6bfb0faafebf727ce11d6f4/execution_engine/src/storage/trie/mod.rs#L338) in the execution engine?
(If it is, it's not 1.4.0 or 1.5.0 — _maybe_ 2.0.0, but needs discussion first.)

**Comment by piotr-dziubecki** [comment]
@xcthulhu was that your request? if so please add here more details. Thank you.
