### ISSUE TITLE
Make Project Compatible With Rust Analyzer

### ISSUE THREAD

**Issue by xcthulhu** [casper-network/casper-node#1952]
The current project structure does not work with rust analyzer.  This makes it hard to develop using various open-source IDEs such as *emacs* and *neovim*.

**Comment by dwerner** [comment]
Today's discussion, though no new progress on this:
Option 1: revert to the 1.3.2 version of the ee-966 contract that remains in the workspace:

https://github.com/casper-network/casper-node/blob/release-1.3.2/smart_contracts/contracts/test/ee-966-regression/src/main.rs

Option 2: Alternatively, we could remove the contracts from the workspace and instead build them, externally, perhaps with `cargo-task`.

**Comment by dwerner** [comment]
https://github.com/casper-network/casper-node/pull/2193
