### ISSUE TITLE
Convert `Config` fields from `Option<...>` to use `#[serde(default="...")]`

### ISSUE THREAD

**Issue by dwerner** [casper-network/casper-node#1967]
Across several config objects, whereever we have a truly non-optional field (ie has a default) then we can apply a `#[serde(default="...")]` annotation to reduce boilerplate.

**Comment by dwerner** [comment]
@sacherjj @Fraser999, I wanted to ask your opinion on this one - it shouldn't change the behavior wherever there are defaults, and where there aren't it's not appropriate.

**Comment by Fraser999** [comment]
Alternatively, consider making all config fields non-optional, so they have to be specified in the toml files.  This avoids making default values or even entire fields opaque to end users.

We should discuss with @sacherjj before making a decision here.

**Comment by cspramit** [comment]
@Fraser999 @dwerner as in standup - discuss further to close or not
