### ISSUE TITLE
Make ContractRuntime use CSP

### ISSUE THREAD

**Issue by dwerner** [casper-network/casper-node#1969]

**Comment by goral09** [comment]
@dwerner , could you explain what do you mean by CSP? I am not familiar with this term.

**Comment by dwerner** [comment]
This is intended to encapsulate the tech-debt in the removal of mutex-locked state from the ContractRuntime and move it into task-local state, reading from a channel using message passing or [CSP](https://en.wikipedia.org/wiki/Communicating_sequential_processes).
