### ISSUE TITLE
call the get_consensus_validator_info method and wire the resultant data

### ISSUE THREAD

**Issue by piotr-dziubecki** [casper-network/casper-node#1977]
call this method and wire the resultant data up to the json-rpc & rest status endpoints;

**Comment by afck** [comment]
Here's the relevant PR: https://github.com/casper-network/casper-node/pull/1540
It's currently only on [the `feat_get_consensus_validator_info` branch](https://github.com/casper-network/casper-node/tree/feat_get_consensus_validator_info)
