### ISSUE TITLE
Make the internal types in EE integration tests public

### ISSUE THREAD

**Issue by piotr-dziubecki** [casper-network/casper-node#1978]

**Comment by piotr-dziubecki** [comment]
Delete `execution_engine_testing` internal mod: `exec_with_return`
Delete the internal mod, move the contents to the top level.
Document everything that will become public
Deprecate `account.rs`
Deprecate `error.rs`
Deprecate types in `session.rs`
Deprecate types in `code.rs`
Deprecate `WasmTestResult` from `wasm_test_builder.rs` 
Rename `WasmTestBuilder` to `WasmTestContext`
Deprecate `WasmTestBuilder` `finish`, `from_result`, replace with new function `WasmTestBuilder` `clear_results`
Add documentation to deprecated code that directs developers to the correct replacement.

**Comment by cspramit** [comment]
@Fraser999 - friendly reminder to keep the documentation updated on this
