### ISSUE TITLE
Improve test_support lookup paths

### ISSUE THREAD

**Issue by mpapierski** [casper-network/casper-node#2000]
When developing a smart contract by default test_support expects following paths:

```
Failed to open compiled Wasm file.  Tried the following locations:
    - /home/michal/.cargo/registry/src/target/wasm32-unknown-unknown/release/erc20.wasm
    - /home/michal/Projects/erc20_wip/contract-tests/wasm/erc20.wasm
    - erc20.wasm
```

`~/.cargo/registry` comes from `CARGO_MANIFEST_DIR` - which, if you depend on `test-support` in your crate is this. This path is not useful for 3rd parties, but it will work for local development.

For 3rd parties (people who depend upon `test-support` through crates.io) we should support a lookup through `$MY_CONTRACT/target/{debug,release}/wasm32-unknown-unknown`. Because as for now contracts require custom build scripts to copy target/release/wasm32-unknown-unknown into $MY_PROJECT/wasm

**Comment by Fraser999** [comment]
@mpapierski With the latest `cargo-casper` output, this functionality is handled by a Makefile now.  I don't see a need for this ticket now, so I'll close it, but if you strongly disagree, ping me so we can discuss further offline.
