### ISSUE TITLE
Simplify `AccountHash::from_public_key`

### ISSUE THREAD

**Issue by xcthulhu** [casper-network/casper-node#2006]
There are various methods for constructing an `AccountHash` from a public key. Sometimes, the contract runtime's `blake2bhash` is called. Other times an account hash is constructed without going through the contract runtime.  We should decide how `AccountHash`s are constructed and be consistent.

**Comment by xcthulhu** [comment]
Note that this kind of refactor work should wait for #2007 so it can be tested for backward compatibility.

**Comment by piotr-dziubecki** [comment]
@EdHastingsCasperLabs decided to close it
