### ISSUE TITLE
Set `HASH_V2_PROTOCOL_VERSION` to `1.5.0`

### ISSUE THREAD

**Issue by xcthulhu** [casper-network/casper-node#2017]
We must set the `HASH_V2_PROTOCOL_VERSION` to 1.5.0 under the mainnet feature flag when we ship 1.5.0

**Comment by afck** [comment]
Should this say "1.5.0" now?

**Comment by xcthulhu** [comment]
@afck updated

**Comment by Fraser999** [comment]
Closed in favour of #2474
