### ISSUE TITLE
Windows or WSL2 support

### ISSUE THREAD

**Issue by ipopescu** [casper-network/casper-node#2025]
Any guides for this should be added in the documentation: https://github.com/casper-network/docs/.

Two team members and possibly other community members have access to Windows machines. Could we enable and support cargo-casper and casper-client on on WSL2 or native Windows? 
The requirements would be to run the following commands without any issues:

```
cargo install cargo-casper
cargo casper my-project
```

and

```
rustup toolchain install nightly
cargo +nightly-2021-06-17 install casper-client
```

**Comment by davidtai** [comment]
So I was able to get this mostly working.  

The first problem is systemd is not supported in WSL2 yet so I did a simple init.d (I'm not at that computer) which I'll post later. 

The second problem is getting the firewall to bind the ports on the virtual interface to the internet which I haven't fixed yet.

**Comment by ipopescu** [comment]
Thank you @davidtai!

**Comment by davidtai** [comment]
Here's the init.d file I used.  You should fix the log locations since I think they are a little off compared to the official docs but otherwise, its pretty straight forward conversion from a systemd unit file to an init.d file.

```bash
#!/bin/sh
### BEGIN INIT INFO
# Provides: casper-node-launcher
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start daemon at boot time
# Description:       Enable service provided by daemon.
### END INIT INFO

dir=""
cmd="/usr/bin/casper-node-launcher"
user="casper"

name=`basename $0`
pid_file="/var/run/$name.pid"
stdout_log="/var/log/$name.log"
stderr_log="/var/log/$name.err"

get_pid() {
    cat "$pid_file"
}

is_running() {
    [ -f "$pid_file" ] && ps -p `get_pid` > /dev/null 2>&1
}

case "$1" in
    start)
    if is_running; then
        echo "Already started"
    else
        echo "Starting $name"
        cd "$dir"
        if [ -z "$user" ]; then
            sudo $cmd >> "$stdout_log" 2>> "$stderr_log" &
        else
            sudo -u "$user" $cmd >> "$stdout_log" 2>> "$stderr_log" &
        fi
        echo $! > "$pid_file"
        if ! is_running; then
            echo "Unable to start, see $stdout_log and $stderr_log"
            exit 1
        fi
    fi
    ;;
    stop)
    if is_running; then
        echo -n "Stopping $name.."
        kill `get_pid`
        for i in 1 2 3 4 5 6 7 8 9 10
        # for i in `seq 10`
        do
            if ! is_running; then
                break
            fi

            echo -n "."
            sleep 1
        done
        echo

        if is_running; then
            echo "Not stopped; may still be shutting down or shutdown may have failed"
            exit 1
        else
            echo "Stopped"
            if [ -f "$pid_file" ]; then
                rm "$pid_file"
            fi
        fi
    else
        echo "Not running"
    fi
    ;;
    restart)
    $0 stop
    if is_running; then
        echo "Unable to stop, will not attempt to start"
        exit 1
    fi
    $0 start
    ;;
    status)
    if is_running; then
        echo "Running"
    else
        echo "Stopped"
        exit 1
    fi
    ;;
    *)
    echo "Usage: $0 {start|stop|restart|status}"
    exit 1
    ;;
esac

exit 0
```

I don't have the commands for poking open the ports but there are several steps:

1) Get the ports opened on windows firewall
2) Get WSL2 ports bound not only to localhost but an external ip address

Resources:
https://www.williamjbowman.com/blog/2020/04/25/running-a-public-server-from-wsl-2/
https://stackoverflow.com/questions/64513964/wsl-2-which-ports-are-automatically-forwarded

It shouldn't be too difficult to get it fully working with Windows 11.
