### ISSUE TITLE
`bytesrepr::Bytes` Should Use Base64 (Rather than Base16) in Their JSON Representation

### ISSUE THREAD

**Issue by xcthulhu** [casper-network/casper-node#2027]
The current implementation for the JSON serialization of `bytesrepr::Bytes` uses base16 (see [here][1]).  Representing them as base64 would make our JSON representation more efficient.

We should do this for Deploys, Tries, etc.

[1]: https://github.com/casper-network/casper-node/blob/e8aa3c38834e98a6ee582c71bf5dc85a87ccf13d/types/src/bytesrepr/bytes.rs#L293

**Comment by Fraser999** [comment]
There was discussion on this in the past and we committed to using base16 rather than base64 throughout.  I don't think this is something we should change.
