### ISSUE TITLE
Investigate and design a test where the blocks are filled up to their full capacity

### ISSUE THREAD

**Issue by piotr-dziubecki** [casper-network/casper-node#2045]

**Comment by goral09** [comment]
I've added some additional logging that tracked the depth of transaction pool and how many deploys were being rejected. In a test with `deploy_delay=1min` (default), we were seeing up to 4000 deploys not being included in a block b/c their reception time was less than `deploy_delay` time ago. To test that theory, there was a second test ran with `deploy_delay=1sec` and it seemed to confirm it ([Kibana link](https://kibana.casperlabs.io/app/kibana#/discover?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-09-14T14:53:41.171Z',to:now))&_a=(columns:!(fields.rejected_deploys),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:e6999930-29fe-11eb-a64a-15b34222d8d2,key:cl-sre-metadata.network_uuid,negate:!f,params:(query:'2fcb99c2-bbc6-54a5-badb-d8c5d1b69b06'),type:phrase),query:(match:(cl-sre-metadata.network_uuid:(query:'2fcb99c2-bbc6-54a5-badb-d8c5d1b69b06',type:phrase)))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:e6999930-29fe-11eb-a64a-15b34222d8d2,key:target,negate:!f,params:(query:'casper_node::components::block_proposer'),type:phrase),query:(match:(target:(query:'casper_node::components::block_proposer',type:phrase)))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:e6999930-29fe-11eb-a64a-15b34222d8d2,key:fields.message,negate:!t,params:(query:'pruned%20deploys%20from%20buffer'),type:phrase),query:(match:(fields.message:(query:'pruned%20deploys%20from%20buffer',type:phrase)))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:e6999930-29fe-11eb-a64a-15b34222d8d2,key:fields.message,negate:!t,params:(query:'handling%20finalized%20block'),type:phrase),query:(match:(fields.message:(query:'handling%20finalized%20block',type:phrase)))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:e6999930-29fe-11eb-a64a-15b34222d8d2,key:fields.message,negate:!t,params:(query:'proposing%20a%20block%20payload'),type:phrase),query:(match:(fields.message:(query:'proposing%20a%20block%20payload',type:phrase)))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:e6999930-29fe-11eb-a64a-15b34222d8d2,key:fields.message,negate:!t,params:(query:'pending%20deploys%20count'),type:phrase),query:(match:(fields.message:(query:'pending%20deploys%20count',type:phrase)))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:e6999930-29fe-11eb-a64a-15b34222d8d2,key:fields.message,negate:!f,params:(query:'rejected%20deploys%20count'),type:phrase),query:(match:(fields.message:(query:'rejected%20deploys%20count',type:phrase))))),index:e6999930-29fe-11eb-a64a-15b34222d8d2,interval:auto,query:(language:kuery,query:''),sort:!(!('@timestamp',asc))))) Now, we were seeing only max 40 deploys being rejected and blocks' fill rates were much higher. 

This, coupled with the fact that it may take up to 4seconds for deploy acceptor to perform its verification, lead to a situation where there wasn't enough deploys in the txn pool ready to be proposed. Hence fill rates were failing short. 

To make sure that all blocks are filled to their maximum limits we should:
* Test with lower values of `deploy_delay` (carefully though as proposing a deploy no one has can kill the proposer when everyone else starts asking for deploy dependencies)
* improve efficiency of deploy acceptor (to verify deploys faster, shortening the time when deploy is in the node but can't be proposed yet b/c it hasn't been accepted)
* increase load of deploys in the internal tests.
