### ISSUE TITLE
Fix AsymmetricType::from_hex for system variant

### ISSUE THREAD

**Issue by Fraser999** [casper-network/casper-node#2047]
Should be updated to
```rust
match tag[0] {
    SYSTEM_TAG => {
        if key_bytes.is_empty() {
            return Ok(Self::system());
        }
        Err(Error::AsymmetricKey(format!("failed to decode from hex: invalid system variant")))
    }
    ED25519_TAG => {
        let bytes = hex::decode(key_bytes)?;
        Self::ed25519_from_bytes(&bytes)
    }
    SECP256K1_TAG => {
        let bytes = hex::decode(key_bytes)?;
        Self::secp256k1_from_bytes(&bytes)
    }
    _ => Err(Error::AsymmetricKey(format!(
        "failed to decode from hex: invalid tag: expected {} or {}, got {}",
        ED25519_TAG, SECP256K1_TAG, tag[0]
    ))),
}

```
and tests added

**Comment by Fraser999** [comment]
The Ed25519 and secp256k1 variants of the asymmetric types have comprehensive unit tests [here](https://github.com/casper-network/casper-node/blob/dev/node/src/crypto/asymmetric_key.rs#L270-L516) and [here](https://github.com/casper-network/casper-node/blob/dev/node/src/crypto/asymmetric_key.rs#L518-L739).  We want something similar for the "system" variants.

This will involve adding a `mod system` to the `tests` module and inside that, adding the following tests:
* `secret_key_to_der_should_error`
* `secret_key_to_pem_should_error`
* `secret_key_to_file_should_error`
* `public_key_serialization_roundtrip`
* `public_key_to_der_should_error`
* `public_key_to_pem_should_error`
* `public_key_to_file_should_error`
* `public_key_to_and_from_hex`
* `sign_should_panic`
* `signature_to_and_from_hex`
* `public_key_traits`
* `public_key_to_account_hash`
* `signature_traits`
* `verify_should_error`
* `bytesrepr_roundtrip_signature`

We should also extend the existing [`tests::public_key_traits` and `tests::signature_traits`](https://github.com/casper-network/casper-node/blob/dev/node/src/crypto/asymmetric_key.rs#L741-L754) which check for sort order of two different variants to include checks using the system variants with each of the other two variants too.

**Comment by cspramit** [comment]
@luis-casper is there a PR for this issue?

**Comment by luis-casper** [comment]
Yes, I forgot to link it.
https://github.com/casper-network/casper-node/pull/2118
