### ISSUE TITLE
Is there a public node rpc to develop application , I want to konw 

### ISSUE THREAD

**Issue by malingzhao** [casper-network/casper-node#2060]

**Comment by cspramit** [comment]
@Fraser999 could u pls?

**Comment by Fraser999** [comment]
The JSON-RPC API is documented in an OpenRPC format and can be provided by any running node.

You can retrieve the schema by e.g. running
```
casper-client list-rpcs -n http://<IP>:7777
```
where IP is the public IP of a running node.  You can find e.g. the testnet nodes' IPs at https://casper-explorer.dev.make.services/tools/peers.

If you don't have the `casper-client` installed, you can do that via
```
cargo install casper-client
```
We're working on presenting the schema in a more human-readable form than raw JSON.  I hope @ipopescu can link the relevant ticket for that work.

**Comment by dudebing99** [comment]
> _No description provided._

Do you find any available public nodes?
