### ISSUE TITLE
Make --payment-amount in client optional for both native transfer subcommands

### ISSUE THREAD

**Issue by piotr-dziubecki** [casper-network/casper-node#2074]
In the Rust client, we should support no payment-related args being provided in the `transfer` and `make-transfer` subcommands.  In the case that no payment-related args are provided by the user, the deploy's payment code should be constructed so that it results in a standard payment of 2_500_000_000 motes.  For reference, see https://github.com/casper-network/casper-node/blob/91b760341b2dd93da87ac9b903f510ea952e2cc1/client/lib/parsing.rs#L524-L527 and https://github.com/casper-network/casper-node/blob/91b760341b2dd93da87ac9b903f510ea952e2cc1/client/lib/parsing.rs#L228-L239

We should also update the help strings output to a user of the client, and the rustdoc comments around the relevant lib code to make it clear that payment-related args are stored as part of the deploy, but are otherwise unused.

**Comment by RitaMAllenCA** [comment]
@Fraser999 2 questions: First - is this still relevant?   Then, please confirm i should move this to the ecosystem repo.   THanks

**Comment by RitaMAllenCA** [comment]
moved to ecosystem: https://github.com/casper-ecosystem/casper-client-rs/issues/60
