### ISSUE TITLE
Change wasmless transfer cost to 250 million gas units

### ISSUE THREAD

**Issue by cspramit** [casper-network/casper-node#2079]
set wasmless_transfer_cost in chainspec to .25 CSPR for production release
this is mitigation against ping pong behavior witnessed in testnet

**Comment by EdHastingsCasperAssociation** [comment]
@mpapierski please turn this around when you wake up tomorrow

**Comment by cspramit** [comment]
@mpapierski this will have to reverted as there is a rejection coming from Mrinal
