### ISSUE TITLE
Get rid of `blake2b` dependencies everywhere except for the `casper-hashing` crate

### ISSUE THREAD

**Issue by xcthulhu** [casper-network/casper-node#2082]
Currently `AccountHash` requires a call to `blake2b` in its constructor in `casper-types`.

There should be one data path for computing hashes.

**Comment by luis-casper** [comment]
How would we approach the dependency of `casper-hashing` on `casper-types` (for the `ToBytes` and `FromBytes` traits)?
If we are to replace Blake2b computations in `casper-types` with the `Digest` version, we need to circumvent this circular dependency.
Moving the `ToBytes` and `FromBytes` implementations from `casper-hashing` to `casper-types::bytesrepr` should be fine, but how about the hashing of BTrees? We could create a trait `Digestible` and implement that for types implementing `ToBytes`.

**Comment by luis-casper** [comment]
I attempted to go this route, but it has proven to be difficult, in particular because it involves non-trivial use of traits and might require `#![feature(specialization)]`, which is not stable yet.
The tip of my attempt is at commit `7dc31354f60a37b3f96c9c8a8f4c5e70a02f618a` on my fork (<https://github.com/luis-casper/casper-node>).

**Comment by luis-casper** [comment]
I have tried two new avenues to solve this issue, but with no luck:
* Move the BTree hashing to `casper-types` also, but my rug was pulled when checksummed hashes were introduced in the hashing crate recently, which would make removing the dependence on `casper-types` impossible;
* Removing the `blake2b` function from `casper-types` (a suggestion from @xcthulhu), but still far too many uses of it in the crate remain, and most are non-trivial to remove.

I think we have to accept that, without major refactoring, there will be Blake2b operations within `casper-types` that don't go through `casper-hashing`. For this issue, I will simply attempt to redirect all Blake2b computations elsewhere to `casper-hashing`, but I doubt this will be concluded in this sprint.

**Comment by luis-casper** [comment]
After discussions with Matt and Fraser, I believe the best course of action is to drop this issue.
