### ISSUE TITLE
Remove unchecked arithmetic from Gas and Motes

### ISSUE THREAD

**Issue by mpapierski** [casper-network/casper-node#2103]
We should remove unchecked operators such as Add, Sub, Div, etc., from Gas and Motes types. Subtle and hard to detect bugs can happen with uncareful use of this. All operations on Gas and Motes should only be through `checked_add`. We also don't need to bring num_traits here as it requires unchecked traits implemented.

**Comment by devendran-m** [comment]
Marked for discussion with @mpapierski .
Sidebar for L1 daily.

**Comment by devendran-m** [comment]
This issue was added to replace another issue removed from the sprint.
