### ISSUE TITLE
Retrieve State Tool Should Not Do A Directory Walk to Check For Existing Blocks

### ISSUE THREAD

**Issue by xcthulhu** [casper-network/casper-node#2121]
The proposed implementation of the retrieve state tool uses a directory walk to check for existing blocks before resuming (see [here][1]).

On slow disks this does not have great performance.

[1]: https://github.com/casper-network/casper-node/pull/2102/files#r713313001

**Comment by dwerner** [comment]
new PR https://github.com/casper-network/casper-node/pull/2182
