### ISSUE TITLE
Store the actual journal and not the json helper types.

### ISSUE THREAD

**Issue by piotr-dziubecki** [casper-network/casper-node#2124]
We should look to replace usage of `ExecutionEffect` with `ExecutionJournal`, and further we should store and serve these as `ExecutionJournal`s rather than as their lossy JSON-helper equivalents (the types defined in execution_results.rs of casper-types crate).

not required: migration of legacy deploys.

**Comment by RitaMAllenCA** [comment]
@Fraser999 please add a small description in all your spare time.

**Comment by RitaMAllenCA** [comment]
7.10.23 historical, immutable types should only be migrated if there is a technical reason (optimization alone is not sufficient).

**Comment by RitaMAllenCA** [comment]
7.12.23 needs client updates - creating a long running branch for the client.   @RBYGLLS @bpr
