### ISSUE TITLE
Remove the usage of ratio

### ISSUE THREAD

**Issue by piotr-dziubecki** [casper-network/casper-node#2134]
We have several usages of `num_rational::Ratio` throughout the code.  These should all be replaced with integer values for the numerator and denominator, since the fact that `almost_1 + almost_1` can overflow is counterintuitive and a footgun.  I expect the `num_rational` crate will be able to be removed from all Cargo.toml files as a part of this work.

If required, discuss details with @afck before working on this ticket, and definitely assign him as a reviewer.

**Comment by luis-casper** [comment]
I have met with @afck and we reached the conclusion that the `Ratio` type itself presents no problem if used correctly. It supports checked arithmetic. As part of addressing this issue, I am writing a new `Ratio` type to locate all occurrences of ratio arithmetic and re-evaluating each one. Once this is done, we can discuss which is the best avenue to take.
