### ISSUE TITLE
Add new contract API calls

### ISSUE THREAD

**Issue by piotr-dziubecki** [casper-network/casper-node#2135]
We want to provide two new helpers in the `contract_api::storage` module:
- `fn named_dictionary_get(dictionary_name: &str, dictionary_item_key: &str) -> Result<Option<V>, bytesrepr::Error>`
- `fn named_dictionary_put(dictionary_name: &str, dictionary_item_key: &str, value: V)`

These are convenience functions which call `runtime::get_key()` internally to get the dictionary's URef followed by `storage::dictionary_get()` or `storage::dictionary_put()`.

**Comment by luis-casper** [comment]
What variant of `bytesrepr::Error` should we return in case `runtime::get_key` returns `None`?
For now I am returning `EarlyEndOfStream`.

**Comment by luis-casper** [comment]
And if it returns a key that is not a URef?

**Comment by cspramit** [comment]
@luis-casper pls add the PR link
