### ISSUE TITLE
Improve robustness of gossiping

### ISSUE THREAD

**Issue by piotr-dziubecki** [casper-network/casper-node#2146]
When node B receives a gossip request from node A, if it does not already know of the item being gossiped, it indicates this in the gossip response.  This serves a dual purpose.  Node A uses this information to decide whether it should continue to gossiping this item.  It also indicates to node A that it should provide the remainder of the item to node B if that item is classified as partial.

Currently gossiping is only used for two types: Node addresses, which are not partial items, and Deploys, which _are_ partial items.  In other words, the address gossiper sends around complete addresses and in the case described above, node A would not have to send anything further to node B on receipt of its response, since node B would now hold a complete copy of the gossiped address.  But in the case of Deploys, the Deploy IDs are gossiped, and node A would send the full Deploy to node B as a reaction to the response from node B.

In the case of partial data, there is a potential for further improvement by retrying other peers in the case that node B requested data from node A, but was not provided with the full data.  In a non-malicious environment, this should only happen if node A loses its connection to node B.

When node B sends its response to node A indicating it wants the full data, it should schedule a timeout handler.  When the timeout is executed, if node A has still not provided the data, a different peer should be chosen from the ongoing gossip state, and an explicit GetRequest sent for the data, with a similar timeout.

A possible simpler alternative is to move away from having the gossiper handle providing complete data and instead use a fetcher.

**Comment by Fraser999** [comment]
Closing as not required.
