### ISSUE TITLE
Fetchers should respond with 'unavailable' message as appropriate 

### ISSUE THREAD

**Issue by piotr-dziubecki** [casper-network/casper-node#2156]
When a node receives a `GetRequest` message from a peer, if it cannot provide the requested data, it should respond with a new message indicating this.

Before working on this ticket, liaise with @marc-casperlabs to discuss the recent work he's done in this area for the feat-fast-sync branch, so as to avoid adopting an approach which will need to be heavily refactored once fast-sync is integrated fully.

**Comment by Fraser999** [comment]
Already completed as part of fast-sync work.
