### ISSUE TITLE
Dictionary keys' max length should be increased

### ISSUE THREAD

**Issue by piotr-dziubecki** [casper-network/casper-node#2157]
Currently the `DICTIONARY_ITEM_KEY_MAX_LENGTH` is set to 64.  This is too short to be useful in some cases where it would be convenient to use our formatted-hex format for various types.

The const should be updated to 128.

**Comment by luis-casper** [comment]
See https://github.com/casper-network/casper-node/pull/2170

**Comment by luis-casper** [comment]
I accidentally closed this issue. My bad.

**Comment by cspramit** [comment]
@luis-casper we need to associated PR to the issue
