### ISSUE TITLE
Remove nested bincode serialization in GetRequests

### ISSUE THREAD

**Issue by piotr-dziubecki** [casper-network/casper-node#2163]

**Comment by piotr-dziubecki** [comment]
Due to the priorities change (rocksdb) we remove this from the current sprint scope.

**Comment by marc-casperlabs** [comment]
Testing changes https://github.com/casper-network/casper-test/pull/73

**Comment by marc-casperlabs** [comment]
This will likely slip due to #2860 and #2866 being added.

**Comment by marc-casperlabs** [comment]
As discussed with @Fraser999, we are closing this, as the underlying problem that was exacerbating this issue (msgpack encoding for network traffic) has been solved and the remaining gains will likely become obsolete with a switch to `ToBytes` encoding in 2.0 the latest. In other words, there is far less bang for our buck implementing this now.
