### ISSUE TITLE
Hard Reset Upgrade failure

### ISSUE THREAD

**Issue by sacherjj** [casper-network/casper-node#2181]
During the 1.3.2 to 1.3.4 upgrade of MainNet we experienced issues with the cutover to 1.3.4 when an upgrade was staged late by multiple Eras.

The needed fix was shutdown and manually editing casper-node-launcher-status.toml to 1.3.4.  

I believe this would be addressed by https://github.com/casper-network/casper-node/pull/2101

**Comment by cspramit** [comment]
@sacherjj is this similar to the late upgrade issues we reported earlier for 1.4.0?

**Comment by cspramit** [comment]
This is addressed by PR #2101
