### ISSUE TITLE
 Use the decorator approach for Deploy.

### ISSUE THREAD

**Issue by piotr-dziubecki** [casper-network/casper-node#2184]
By decorator approach we mean that a raw inner type like UnvalidatedBlock implements deserialization without validation, and an outer type struct Block(UnvalidatedBlock) implements serialization and can only constructed by validating the inner one.

**Comment by Fraser999** [comment]
This ticket should probably be closed as "won't do", but I'll hang fire on closing it until I hear further arguments in favour of bypassing the `DeployAcceptor`.
