### ISSUE TITLE
Design a Logging System for the Smart Contract Runtime,

### ISSUE THREAD

**Issue by piotr-dziubecki** [casper-network/casper-node#2185]
Smart contracts require an ability to log events.  An API similar to https://ethereum.org/en/developers/tutorials/logging-events-smart-contracts/ should be provided by the smart-contract runtime.

Reporter: @xcthulhu

**Comment by cspramit** [comment]
@Fraser999 reassign please

**Comment by devendran-m** [comment]
Done. @devendran-m , find and attach the PR.

**Comment by devendran-m** [comment]
The PR that implemented the solution is https://github.com/casper-network/casper-node/pull/4370

**Comment by devendran-m** [comment]
Other related PRs;
- https://github.com/casper-network/roadmap/issues/225
- https://github.com/casper-network/casper-node/pull/4344
