### ISSUE TITLE
Verify fetched items in fast sync

### ISSUE THREAD

**Issue by cspramit** [casper-network/casper-node#2189]
Fast sync needs to verify that the deploys and blocks received from peers are cryptographically valid and match the ones that were requested.

**Comment by afck** [comment]
We decided to change the implementation:

1. Separate `validate` from `id`.
2. Validate signatures as part of domain logic, only after we know the signer is expected.
3. Use `Deploy::is_valid` and memoize in a `Cell`, ignore in `Eq`.
