### ISSUE TITLE
Allow control of external nodes

### ISSUE THREAD

**Issue by piotr-dziubecki** [casper-network/casper-node#2208]
As per casper-test roadmap, we need to be able to control external nodes through SSH access. We will use a server-side wrapper script named casper-ctl with the simple commands of start, stop and status in the first iteration to abstract inner remote node details away.
The external environment will call these to control nodes in test if an SSH key is set by shelling out to the ssh binary.

**Comment by piotr-dziubecki** [comment]
blocked by https://github.com/casper-network/roadmap/issues/33

**Comment by marc-casperlabs** [comment]
The issue is in the wrong repo, PR is up at https://github.com/casper-network/casper-test/pull/59
