### ISSUE TITLE
1.3.2>13.4>1.4.0 Upgrade failure when era duration short

### ISSUE THREAD

**Issue by cspramit** [casper-network/casper-node#2209]
Issue: When era duration is 15 mins and upgrade point era 3, upgrade failure .
Path - 1.3.2> 13.4 and 1.3.2>1.3.4>1.4.0

"// This is an invalid run where blocks are missing from storage.  Try exiting the
// process and downgrading the version to recover the missing blocks.
//
// TODO - if migrating data yields a new empty block as a means to store the
//        post-migration global state hash, we'll come to this code branch, and we
//        should not exit the process in that case."

https://casperlabs-team.slack.com/archives/C01ULKL8G8J/p1633999365206100
https://casperlabs-team.slack.com/archives/C01ULKL8G8J/p1634116042220500?thread_ts=1633999365.206100&cid=C01ULKL8G8J

**Comment by cspramit** [comment]
@thamps-casp do we have the chainspec we used or the setting we changed to run this scenario for a shorter era duration, Engg need

**Comment by cspramit** [comment]
@thamps-casp as we scale down era time other parameters in the config also needs to be adjusted accordingly - but which is not fully known as discussed in huddle

**Comment by thamps-casp** [comment]
yes agreed. the chainspec was from production and only era duration parameter was modified. There are other parameters that are impacted by this change. 

Would be good to identify configs that with smaller Era durations and that can provide valid results in internal performance testing.

@cspramit Unable to upload attachments.
@thamps-casp - if you are unable to - send it across - will try

**Comment by afck** [comment]
As discussed I will add a test to #2222, and then backport it to [release-1.3.4-alt](https://github.com/casper-network/casper-node/tree/release-1.3.4-alt) and [release-1.4.0](https://github.com/casper-network/casper-node/tree/release-1.4.0).
