### ISSUE TITLE
Introducing tests to trigger all error variants from the JSON-RPC specification

### ISSUE THREAD

**Issue by piotr-dziubecki** [casper-network/casper-node#2234]
The way the `warp_json_rpc` crate is designed prevents us from correctly returning all possible errors defined by the OpenRPC standard (https://www.jsonrpc.org/specification#response_object):

<html>
<body>

code | message | meaning
-- | -- | --
-32700 | Parse error | Invalid JSON was received by the server.An error occurred on the server while parsing the JSON text.
-32600 | Invalid Request | The JSON sent is not a valid Request object.
-32601 | Method not found | The method does not exist / is not available.
-32602 | Invalid params | Invalid method parameter(s).
-32603 | Internal error | Internal JSON-RPC error.
-32000 to -32099 | Server error | Reserved for implementation-defined server-errors.

<br class="Apple-interchange-newline">
</body>
</html>

The goal of this ticket is to create tests in the `casper-test` framework for each error described in the above table. Because right now it is not possible to return all the errors, some of these tests will fail and will need to be ignored in the CI run.

After we see which tests fail, we'll make a decision how to process. Among the possible solutions are:
* fork and fix the `warp_json_rpc` crate
* create a PR to the `warp_json_rpc` crate
* get rid of the `warp_json_rpc` crate and provide own solution

**Comment by rafal-ch** [comment]
The following PR:
https://github.com/casper-network/casper-test/pull/55

adds the `rpc_jsonrpc_error_codes.rs` tests.

Within this test there is a case which expects error `-32600`, but the node returns `-32700`, due to the `warp-json-rpc` limitations:
```
    // Invalid Request - request is a correct JSON, but not a correct RPC request
    (
        r#"
        {
            "a": 1
        }"#,
        -32700, // Should be -32600
    ),
```

After the issue with `warp-json-rpc` is solved this test should start to fail and the we need to update the expected error code.
