### ISSUE TITLE
Only upgrade after switch block is fully signed and stored.

### ISSUE THREAD

**Issue by piotr-dziubecki** [casper-network/casper-node#2235]
We need to make sure that the last switch block before an upgrade gets fully signed and stored. All nodes must get a chance to see the switch block finalized, either because the others wait long enough so they can provide the full consensus protocol state, or because they still provide the signed switch block after the restart (see #1490). We always need to wait for the switch block (see #2209) and — if we are validators — our own signature to be stored before restarting.

**Comment by afck** [comment]
This could (and should) actually be done even before fast sync, on `dev`.
