### ISSUE TITLE
Add functionality to undelegate everything

### ISSUE THREAD

**Issue by piotr-dziubecki** [casper-network/casper-node#2241]
Is there a way to undelegate everything from a validator?  We are observing that there’s a little bit that’s left over because we can’t accurately calculate rewards. This will eventually become a problem because we will have dangling delegators in the auction state with small amounts of cspr delegated.

**Comment by Fraser999** [comment]
We need a test to confirm this behavior.

**Comment by cspramit** [comment]
this turned out be a CNR bug, thus no code change - however believe dust motes were real, were we not able to reproduce at all? @nilz3ro @Fraser999

**Comment by cspramit** [comment]
@nilz3ro ??
