### ISSUE TITLE
Discover all production code panics

### ISSUE THREAD

**Issue by piotr-dziubecki** [casper-network/casper-node#2255]
Assert, unwrap, panic, unreachable, i.e. not tests, root/utils, benches. The deliverable for this is a set of links against feat-fast-sync catagorized where it's in the code, e.g. in network, EE, consensus, etc...

**Comment by HansWestman74** [comment]
After discussion with Fraser, Matt and Ed we are closing the initial PR providing just the list. And we consider this work to be done. Follow up stories will be added in future sprints.

@piotr-dziubecki  Per Ed create an epic for this tranche of work. More stories will be created within it. Ask Fraser for details.
