### ISSUE TITLE
Clean up the story about lmdb and unit file locations.

### ISSUE THREAD

**Issue by piotr-dziubecki** [casper-network/casper-node#2256]
Config has
```
[storage]

# Path (absolute, or relative to this config.toml) to the folder where any files created
# or read by the storage component will exist.
#
# If the folder doesn't exist, it and any required parents will be created.
#
# If unset, the path must be supplied as an argument via the CLI.
path = '/var/lib/casper/casper-node'
```
for lmdb, but we are using and additional <network-name> for path.
For unit files:
```
[consensus.highway]

# The folder in which the files with per-era latest unit hashes will be stored.
unit_hashes_folder = "/var/lib/casper/casper-node"
```
This is expected to not use the <network-name> path.
config-example should be up updated to mention that a network-name sub directory is automatically created and used.
unit files should move into there and also have the same updated comments if they cannot be moved into lmdb.
Note: this will most likely need a storage migration step.
Also what happens when this config value is changed between versions at an upgrade?  Are moving lmdb and unit files?

**Comment by piotr-dziubecki** [comment]
@sacherjj It would also be nice to clean up older unit files if possible.  Some servers have hundreds of these from Apr or older.

**Comment by fizyk20** [comment]
> Note: this will most likely need a storage migration step.

As for now we're just moving where the files are stored, storage migration won't be necessary.

> Also what happens when this config value is changed between versions at an upgrade? Are moving lmdb and unit files?

Unit files can be safely ignored, or even manually removed. We're not instantiating any eras from before an upgrade, so the unit files from before an upgrade become irrelevant after the upgrade.
