### ISSUE TITLE
Fix integer overflow in u8_slice_to_bytes.

### ISSUE THREAD

**Issue by piotr-dziubecki** [casper-network/casper-node#2260]
Instead of a conversion using as, prefer the TryFrom trait in https://github.com/casper-network/casper-node/blob/release-1.3.4/types/src/bytesrepr.rs#L1100

**Comment by luis-casper** [comment]
There is a minor design decision that must be made to solve this: what would be the error variant on overflow?
Currently `bytesrepr::Error` has four variants: `EarlyEndOfStream`, `Formatting`, `LeftoverBytes` and `OutOfMemory`.
However, the first two are reserved for deserialization according to their code comments.
Would introducing a new variant be acceptable?
