### ISSUE TITLE
Execute ecosystem smart contracts regression tests against upcoming release

### ISSUE THREAD

**Issue by piotr-dziubecki** [casper-network/casper-node#2262]
1. Define the list of contracts
2. Check CI/CD
3. Check test suite for the contracts
4. Execute the test/add tests

CC @deuszex @astro019

**Comment by piotr-dziubecki** [comment]
reporter @Fraser999  - please contact him before taking this task.

**Comment by goral09** [comment]
Worth adding that @luis-casper wants to include a set of known smart-contracts in a benchmarking pipeline that would detect regressions in cost/size. Maybe there's some work that can be shared.

**Comment by luis-casper** [comment]
> Worth adding that @luis-casper wants to include a set of known smart-contracts in a benchmarking pipeline that would detect regressions in cost/size. Maybe there's some work that can be shared.

Indeed, I think instrumenting the `*WasmTestBuilder`s would be the way to go.

**Comment by devendran-m** [comment]
This is an ongoing release process. Hence closing it.
