### ISSUE TITLE
Allow contract upgrade to overwrite named keys.

### ISSUE THREAD

**Issue by piotr-dziubecki** [casper-network/casper-node#2275]
Currently, when calling add_contract_version the logic takes the newly supplied named key list, then appends the old named keys to it, as such the new ones are overwritten by the old ones. Flip this logic so named keys can be upgraded. We already discussed this topic with @EdHastingsCasperLabs 

https://github.com/casper-network/casper-node/blob/dd260c86aad94ea3a9e958080558778e8aee9f40/execution_engine/src/core/runtime/mod.rs#L2571

Reporter: @deuszex 
Approver: @EdHastingsCasperLabs

**Comment by devendran-m** [comment]
Technically, a "could do" with proper justifications. However, closing it as won't do.
