### ISSUE TITLE
ChunkWithProof exposes the smart constructor only

### ISSUE THREAD

**Issue by piotr-dziubecki** [casper-network/casper-node#2293]
Only expose smart constructor: ChunkWithProof::new(index: u64, data: &impl AsRef<[u8]>) -> Result<ChunkWithProof, IndexOutOfBoundesError>.

**Comment by rafal-ch** [comment]
Currently, as a result of implementation of [the chunking ticket](https://github.com/casper-network/casper-node/issues/2119) we only expose the following constructor, which I think is consistent with the requirements of this ticket:
```
pub fn new(data: &[u8], index: u64) -> Result<Self, MerkleConstructionError>
```
