### ISSUE TITLE
Remove verify_accounts config option and VerifyDeployCryptographicValidity event from deploy acceptor

### ISSUE THREAD

**Issue by cspramit** [casper-network/casper-node#2297]
@darthsiroftardis pls add description

**Comment by darthsiroftardis** [comment]
The deploy acceptor has one superflousous event titled `VerifyDeployCryptographicValidity`, this was a part of the early work involved in expanding the acceptor but is now not necessary. Additionally, the constructor to the acceptor takes in an `verify_accounts` arg, but that should be removed as well
