### ISSUE TITLE
Improve BlockProposer state caching and retrieval

### ISSUE THREAD

**Issue by cspramit** [casper-network/casper-node#2298]
Currently the BlockProposer only caches its state every time it prunes that state, on a repeating timer of 10 second intervals.  That gives a window of up to 10 seconds-worth of recently enqueued deploys which will not be saved if the node stops running, and hence will not be re-enqueued on the next startup.  We need to either 1. update the stored state on every new deploy enqueued, or 2. update the node architecture so that components have an opportunity to store their state before the reactor and storage component are shut down, or 3. don't store the pending deploys as "state", but rather just build up the equivalent info on startup by querying the storage's deploy store.
These all have drawbacks: 1. is not feasible without a rework of how state is stored (we don't want to overwrite a collection of several thousand deploys' info on every single new deploy), 2. will probably be somewhat complex, and might still not be the best option in that it will require the node to exit gracefully in order to cache the state, and 3. is probably prohibitively expensive without an additional index/db specifically for this purpose.

**Comment by devendran-m** [comment]
The block proposer does not exist any more. It was replaced by transaction buffer which does not have this problem.
