### ISSUE TITLE
 Make RPCs distinguish whether we have state for a root hash in feat-fast-sync.

### ISSUE THREAD

**Issue by piotr-dziubecki** [casper-network/casper-node#2302]
If a client asks for some trie based on a block's root hash, the response should not look the same in these two cases:

* We don't have the full state for that block.
* We do have the full state and we know that that entry does not exist.

We should also add a new RPC so we can ask a node what is the oldest block that it has fully stored (including body, deploys and state).

Reporter: @afck

**Comment by Fraser999** [comment]
Duplicate of https://github.com/casper-network/casper-node/issues/2632
