### ISSUE TITLE
SPIKE: Investigate how the auction performance could be improved

### ISSUE THREAD

**Issue by piotr-dziubecki** [casper-network/casper-node#2316]
Create a benchmark (parameterized, using values as close as possible to the mainnet)

Ensure that we consider running the auction for several eras.

The outcome of this -> proposal for the improvements -> meeting.

**Comment by dwerner** [comment]
Sprint planning: Nov 15 - Ed pointed out that this doesn't need to be a spike, and instead should be a meeting to discuss approaches and options.

**Comment by dwerner** [comment]
Reviewed this last week with the team, and we decided a new design we needed this written up @AlexanderLimonov @EdHastingsCasperLabs @afck

**Comment by dwerner** [comment]
Unassigning myself, assigning @Fraser999 as I'm not sure what to do with this ticket with the currently-being-developed proposal here.
