### ISSUE TITLE
trie-store integrity check progress

### ISSUE THREAD

**Issue by RapidMark** [casper-network/casper-node#2326]
I would suggest a way to show progress of the integrity check.

Not only does it take hours/days, there is no feedback on the progress (while this talks about ways to speed it up (https://github.com/casper-network/casper-node/issues/2268) this is suggesting we have a way to check on the progress.

Maybe via :8888/status or even scraping the log files...

**Comment by Fraser999** [comment]
Thanks for the suggestion.

As @afck mentioned in the ticket you linked, we're planning an overhaul of this integrity check mechanism.  We'll keep this suggestion in mind when the rework takes place.

**Comment by piotr-dziubecki** [comment]
Improvements to integrity checks including observability are coming to 1.5.1

**Comment by piotr-dziubecki** [comment]
we're going to refine integrity check to only check the tip.
