### ISSUE TITLE
 Deploys downloaded as part of synchronization should not be added to a deploy buffer.

### ISSUE THREAD

**Issue by piotr-dziubecki** [casper-network/casper-node#2339]
Currently, every deploy that reaches the node and goes through DeployAcceptor gets added to the deploy buffer for potential proposal later (link). That's unnecessary and incorrect. Deploys that have already been included in a block cannot be proposed again. This means, that as the part of replay protection, we're unnecessarily iterating over thousands of deploys that cannot be proposed again.

From Andreas:
Actually, will that cause problems with unhandled_finalized? Will the deploys from that block end up in that collection and never get pruned, because the block proposer doesn't know their timestamps and TTL?
The other question is whether we want to add deploys to the buffer that are part of a proposed block: If the block gets orphaned, we should propose them again, but maybe orphans are rare enough so that we don't need to care?

_To the person that will work on this: let's make sure that the above concern is addressed (unit test, integration test, etc.)_

**Comment by Fraser999** [comment]
See https://casperlabs-team.slack.com/archives/C02FE1UTRS6/p1636464320099100, but the summary is that this seems to be a non-issue since the linear chain sync only exists in the joiner reactor and the block proposer only exists in the participating reactor.
