### ISSUE TITLE
Refunds after a duration

### ISSUE THREAD

**Issue by piotr-dziubecki** [casper-network/casper-node#2343]
refunds after a lockup period.   ![004FC75C-1A84-4F27-808A-47EB62726663.jpeg](https://images.zenhubusercontent.com/633d7d99e49afa10e7f6fa89/a6f66b1e-2365-4dea-8de5-7854a9556598)

EE: 
refund according to the proportional model on demand.    
ratio is determined via a chainspec setting
bounded: do not support negative or 100+% payouts

Pricing will be implemented on the node side.  
Need to incentivize inclusion of deploys

Adding/rephrasing above from @AlexanderLimonov :
- immediate implementation
    - proportional refunds from aggregate remaining locked funds governed by a chainspec parameter
    - calculation to be carried out on demand
- pricing considerations independent mechanically, but synergistic (arguably **necessary** in the long run) with refund delays in promoting responsible use of the blockchain (see dynamic pricing and refund notes linked below)
- additional incentives for precise gas estimation ([CEP #68](https://github.com/casper-network/ceps/blob/9fae432207bf96b2fbd7348bd05e9fedaa49ae8c/text/0068-delayed-refunds.md)) considered but deemed unnecessary
- new design for incentivizing honest reporting of deploy buffer necessary for 2.0+ improvements (now that there are no fees)
- considerations of honest reporting of deploy buffer also led to consideration of modifications to Zug/block proposal to eliminate/minimize empty blocks (@fizyk20 heads up)
- notes based on prior modeling
    - [total refunds without dynamic pricing](https://docs.google.com/document/d/16npOJUcBIPVL4wQM7eJMHe8_GyyehRhz1Soi4QqYytI/edit)
    - [total refunds WITH dynamic pricing](https://docs.google.com/document/d/1E_dEpT3xPQaU15_rx-B9I4o55JE-2uCPuJxGzAlgnJA/edit)

**Comment by AlexanderLimonov** [comment]
Related to (but not blocked by) https://app.zenhub.com/workspaces/engineering-l1-60953fafb1945f0011a3592d/issues/gh/casper-network/governance/462
