### ISSUE TITLE
Provide chainspec config value for CHUNK_SIZE_BYTES

### ISSUE THREAD

**Issue by Fraser999** [casper-network/casper-node#2354]
We should:
* make the `CHUNK_SIZE_BYTES` value configurable via the chainspec `CoreConfig`
* rename it to `hash_chunk_size` (to be consistent with `maximum_net_message_size`) and specify the units as bytes in the comment in both the Rust code and the Toml
* if the value is `0`, it has the effect of disabling the chunking functionality
* provide a check in `Chainspec::is_valid()` that `3 * hash_chunk_size < maximum_net_message_size`

**Comment by goral09** [comment]
> * rename it to `hash_chunk_size`

why does it have to have `hash_` in the name?

**Comment by rafal-ch** [comment]
Passing the configured chunk size to the `Digest::hash()` function proved to be dubious due to large amount of changes on the calling sites.

One of the potential solutions is to have a separate `Digest::hash_with_chunks()` and use it only when the chunking could really occur, and leave other places as they are.

No final design decision is made, though.

**Comment by rafal-ch** [comment]
According to @xcthulhu, having two separate hashing functions is not advised, as we need to make sure we consistently use the correct functions in all places of the system. Because in most situations the two functions will return the same value, this could escape testing.

**Comment by rafal-ch** [comment]
Also, @xcthulhu suggests that adding the ability to disable the chunking completely could introduce an attack vector.

**Comment by rafal-ch** [comment]
@Fraser999 we should discuss the suggested `HashConfig` approach.

**Comment by rafal-ch** [comment]
As discussed, we'll keep the current implementation, i.e.:
* chunk size remains hardcoded
* chunking is always enabled

However, we'll add a log warning in `Chainspec::is_valid()` when `[network][maximum_net_message_size]` is less than "chunks size * 3"
