### ISSUE TITLE
Flush LMDB to disk after commit_step, commit_genesis, commit_upgrade

### ISSUE THREAD

**Issue by cspramit** [casper-network/casper-node#2375]
We should call flush_environment after each of these - commit_step, commit_genesis, commit_upgrade

**Comment by dwerner** [comment]
PR up here https://github.com/casper-network/casper-node/pull/2374

**Comment by xcthulhu** [comment]
@afck This needs to be done in the fast sync branch too

CC @EdHastingsCasperLabs @Fraser999

**Comment by afck** [comment]
@xcthulhu: We should just merge `dev` to `feat-fast-sync` again, once the other fixes have merged, too.

**Comment by afck** [comment]
@xcthulhu: Or is this something we also need to do explicitly in `Participating::new`?

**Comment by afck** [comment]
Looks like it is, because it's done by the _caller_ and not inside `commit_*`.
