### ISSUE TITLE
Update launcher to run highest installed version of node.  

### ISSUE THREAD

**Issue by piotr-dziubecki** [casper-network/casper-node#2379]
The behavior of the updated launcher:
* At startup, launcher scans for the installed versions of the node
* If at least two versions are found, two most recent ones are selected and config migration process is started
* The most recent node is started

Notes:
* Launcher state file is no longer needed
* The config migration process could be run multiple times without impacting the result (idempotence)

Nice to have:
* Add the ability to override the launcher default behavior and force it to run a version other than the latest

**Comment by marc-casperlabs** [comment]
~~Here's a proposal:~~

* ~~Have a text file (or launcher state file) that indicates which version should be launched.~~
* ~~Network runs on 1.5, goes down for upgrade, causing the launcher to indicate in the state file that 1.6 should be launched next.~~
* ~~When it restarts, the state file will cause 1.6 to be launched. All is fine.~~
* ~~Problematic scenario: Someone installs the 1.5+1.6 package with a 1.5 state file, but the network has progressed to 1.6. In this case, we crash and require the operator to manually set 1.6 in the state. ~~

(superseded by idea below)

**Comment by marc-casperlabs** [comment]
Here's an even better proposal:

* Assume that all data migrations are not backwards compatible ~(we've been silently assuming this for the longest time, but we really should not)~. This means that we can only go forward, not backward with versions.
* The node itself and outside parties should be able to identify the version of its database state (we could simply add a text file `data_version` to the storage directory).
* If a node starts on an incompatible database version, it exits with an error.
* The launcher always launches the highest version available if there is no `data_version` or no database is available.
* If a running node observes a transition (activation point), it returns a special exit code, causing the launcher to run the data migration (which will change `data_version`). As a result, the next time the launcher launches, it will require the correct version to be started.
* Launcher commands need to exist to trigger data migrations manually, as well as running a different version on an empty database.

This scheme protects against accidental data migrations and premature launches of later versions.

Use cases are:

* New installation, but no upcoming upgrade: Launching the highest version will result in the correct behavior.
* New installation, but upgrade already staged: The user will have to manually specify that they want to create an "old" installation.
* Existing installation going through upgrade: All should work out correctly by itself.
* Existing installation was down during upgrade: User runs migration manually once, then the launcher picks up automatically.

Launching an old version of a node will cause it to be "stuck", as it cannot connect to any known nodes, once rejection of older nodes is in. Heuristics can be added to automatically exit in a separate ticket, but I believe a `WARN` level message about the version mismatch when connecting to a `known_addresses` should be enough.

**Comment by rafal-ch** [comment]
There will be only a single change in the launcher behavior required:

* if there's no existing launcher state file, have the launcher pick the highest installed version of node and run that (in normal mode, not data-migration mode)

Additionally, we should add support for the command line argument for overriding the state file.
