### ISSUE TITLE
 Do not call key.to_bytes() in get/put methods in trait Store<K, V>

### ISSUE THREAD

**Issue by piotr-dziubecki** [casper-network/casper-node#2399]
In all cases where Store trait is used Key is always a Digest (or similar [u8; 32] wrapper) and calling to_bytes() allocates a Vec just to take slice of it.  For Digest it does not matter because digest.to_bytes() == digest and we can just simply take a slice of the array. To keep things generic we can change specialization from K: ToBytes into K: AsRef<[u8]> or just remove generic paramter K altogether and replace it with Digest.

**Comment by Fraser999** [comment]
I think changing to `K: AsRef<[u8]>` is a reasonable change here, and should be a fairly small change.  Let's take that approach.
