### ISSUE TITLE
 Config-gated HTTP server for debug information

### ISSUE THREAD

**Issue by piotr-dziubecki** [casper-network/casper-node#2405]
As we add additional debugging capabilities, we want to add another HTTP server that can be enabled (default off) through the configuration file. It offers REST-style endpoints, which later tickets will fill with the appropriate debugging functionality.
The HTTP server has some special priviledges, mainly by making requests that require large datadumps while invariably freeze processing on the node in doing so.

**Comment by marc-casperlabs** [comment]
This feature has been replaced by the UNIX debug console from #2539.
