### ISSUE TITLE
 SIGHUP for config reloading

### ISSUE THREAD

**Issue by piotr-dziubecki** [casper-network/casper-node#2406]
The node should listen to SIGHUP signals and provide a way to hot reload configuration.
This can take the shape of a ConfigurationReloadAnnouncement<T> that contains the reloaded configuration, or a method on the component itself. Components interested in having hot-reloadable configuration can implement these and support them.
The debug HTTP server is a likely first consumer for this feature.

**Comment by marc-casperlabs** [comment]
This feature has been replaced by the UNIX debug console from #2539 -- config reloading was only required as a means to enabled the debug HTTP server from #2405, but having a secure UNIX socket to gate access is a better solution.
