### ISSUE TITLE
 Remove mainnet feature flag from feat-fast-sync.

### ISSUE THREAD

**Issue by piotr-dziubecki** [casper-network/casper-node#2474]
Instead, add a chainspec entry `merkle_tree_hash_activation` which specifies the _era_ from which the new block body hashing scheme is used.

So instead of comparing the block's protocol version to a hard-coded (but feature flag-dependant) constant, the block's era has to be compared to `merkle_tree_hash_activation` to determine whether hashing v1 or v2 should be applied.

**Comment by rafal-ch** [comment]
Pulled back from "In Review" as there is some more work needed in the tests.
