### ISSUE TITLE
 Extend tests for the fast-sync node

### ISSUE THREAD

**Issue by piotr-dziubecki** [casper-network/casper-node#2476]
This ticket covers creating different `nctl` tests to reproduce various issues reported against the `fast-sync` node by the team.

Issues identified so far:
- Performance of the joiner node
  - postponed, until the `block_proposer` issue is resolved (for now, correctness is more important than performance)
  - the `block_proposer` issue is tracked here: https://github.com/casper-network/casper-node/issues/2472
- Test for #2457 
  - PR ready for review: https://github.com/TomVasile/casper-node/pull/11
- Test for the following scenario
  - 1.5.x (fast-sync) network is running
  - remember the trusted hash
  - upgrade network to 1.6.x (next version of the fast-sync node)
  - try to join a new node with trusted hash from 1.5
  - the node is expected to fail with a message

Problems detected by @TomVasile , @thamps-casp when running SRE tests:
- itst13.sh
  - Node 5 doesn't catch up after restart, network eventually stalls out
- emergency_upgrade_test.sh
- gov96.sh
  - probably bad toml
- unnamed test (Fast Sync Testing - feat-fast-sync branch)
  - when `archival sync = true` ➜ stalled for long, sync mid-way and 1 block per 20mins (http://genesis.casperlabs.io/rti-fast-sync/casper-node-logs/15Dec21-fs-joiner-a/15122021_0245/log_download_list.txt)
  - when `archival sync = false` ➜ node shutdown with storage error `storage error: Non-existent deploy or transfer in block` - Andreas is working on a ticket (https://github.com/casper-network/casper-node/pull/2511).

**Comment by rafal-ch** [comment]
~Currently addressing two issues:~
~- Performance of the joiner node - postponed~
~- Test for https://github.com/casper-network/casper-node/pull/2457~
  ~- PR for review: https://github.com/TomVasile/casper-node/pull/11~

Progress is now tracked in the description of the PR.
