### ISSUE TITLE
 Add on-disk file size checks to WasmTestBuilder

### ISSUE THREAD

**Issue by piotr-dziubecki** [casper-network/casper-node#2481]
We need to watch data.lmdb and it's growth, so we should add the capacity to check the on-disk size of lmdb during a test. This would be useful to know, for example, the size growth after N transfers, purses, auction steps with N delegators, etc.

**Comment by dwerner** [comment]
PR: https://github.com/casper-network/casper-node/pull/2549

**Comment by dwerner** [comment]
I'd like to close this when #2623 merges, as it is included there.
