### ISSUE TITLE
 Do sync-to-genesis in parallel with normal operation

### ISSUE THREAD

**Issue by piotr-dziubecki** [casper-network/casper-node#2487]
Downloading all blocks and their state back to genesis can take a long time. It should be possible to start a node and make it follow the network, while it downloads historical data in the background.

**Comment by xcthulhu** [comment]
This duplicates  #2083

**Comment by xcthulhu** [comment]
As I stated [previously](https://github.com/casper-network/casper-node/issues/2083#issuecomment-920514587).

One suggestion put forward by @goral09 is to launch a task in the participating reactor.

One way of doing this is to extract the following from the run_fast_sync_task, delete it there and launch it as an effect in the participating reactor:

```rust
    // Sync to genesis
    let mut walkback_block = *fetch_and_store_block_by_hash(effect_builder, trusted_block_header.hash()).await?;;
    loop {
        sync_deploys_and_transfers_and_state(effect_builder, &walkback_block).await?;
        if walkback_block.height() == 0 {
            break;
        } else {
            walkback_block = *fetch_and_store_block_by_hash(
                effect_builder,
                *walkback_block.header().parent_hash(),
            )
            .await?;
        }
    }
```
