### ISSUE TITLE
Upgrade version 1_4_3, but wait a long time node is not synchronized

### ISSUE THREAD

**Issue by COLUD4** [casper-network/casper-node#2503]
![截屏2021-12-17 上午11 37 34](https://user-images.githubusercontent.com/21240219/146484954-209e0dc2-4fbe-401e-a290-a39cc5faea3e.png)
I stopped running nodes first, then execute the following command: 1, the curl - s genesis. Casperlabs. IO and casper / 1 _4_3 / stage_upgrade. Sh

2, cd ~; curl -sSf genesis.casperlabs.io/casper/1_4_3/stage_upgrade.sh | sudo bash -
Then I changed the RPC port in confg. Toml of 1_4_3.
Then start the node with sudo systemctl start casper-node-launcher.
But it took a long time for the nodes to start synchronizing

**Comment by sacherjj** [comment]
This would need logs and other things to have any idea of what is going on.  I can't do anything with this.

**Comment by sacherjj** [comment]
This looks to be in the deploy check of 1_4_1 startup and will probably restart with detection of 1_4_3 and sync.
