### ISSUE TITLE
 In fast_sync_to_most_recent we should go forward as far as possible.

### ISSUE THREAD

**Issue by piotr-dziubecki** [casper-network/casper-node#2508]
It's wasteful to download the global state of an old block, and currently we'd always download the state of the first block in the current era. We should go as far as possible instead, to download the state of a block as recent as possible.

**Comment by piotr-dziubecki** [comment]
Once this is implemented, we should measure/benchmark to see if this yields an improvement or not.

**Comment by RitaMAllenCA** [comment]
@rafal-ch old - is this still relevant? If not, please close

**Comment by rafal-ch** [comment]
Closing as irrelevant (applies to the initial implementation of fast sync)

cc: @Fraser999
