### ISSUE TITLE
Disable usage of checksummed-hex encoding in the node, but continue to support decoding

### ISSUE THREAD

**Issue by piotr-dziubecki** [casper-network/casper-node#2514]
Early feedback on the 1.4.3 mainnet release shows that some stakeholders are unable to work with the checksummed-hex encoding as currently implemented.

To resolve this, we should reduce the scope of this encoding to only `AccountHash` and `PublicKey` types.

**Comment by Fraser999** [comment]
Note that the ticket has been updated to cover disabling all usages of this encoding style to ensure we're providing output which all current consumers can use.
