### ISSUE TITLE
Bulk writes to the trie store

### ISSUE THREAD

**Issue by piotr-dziubecki** [casper-network/casper-node#2517]
Writes to the trie must be as efficient as possible.  Currently every time a (Key, StoredValue) pair is written to the trie, there are many intermediate PointerBlocks and ExtensionNodes that are written.  The final state root hash does not contain a reference to these, however.  A more efficient solution is to write them in bulk.  This can be done by constructing a recursive intermediate structure.

**Comment by luis-casper** [comment]
This is implemented here: https://github.com/dwerner/casper-node/pull/17
