### ISSUE TITLE
Deduplicate block execution code

### ISSUE THREAD

**Issue by piotr-dziubecki** [casper-network/casper-node#2518]
When merging dev into feat-fast-sync, the block execution code in contract_runtime got duplicated because we are using a synchronous and an async version.

**Comment by dwerner** [comment]
As my PR that attempted to address this is closed in favour of some work that @Fraser999 has in the works, I'm moving this back to the backlog.

**Comment by dwerner** [comment]
This duplicated code no longer exists in feat-2.0. I suspect this changed when ScratchTrie was implemented. What does exists are two pathways:
1. `EffectBuilder::execute_finalized_block()` - used by the chain synchronizer to `create_immediate_switch_block`.
2. `EffectBuilder::execute_finalized_block_or_requeue()` - used by the era supervisor to enqueue a block for execution, or re-queue it using the effect builder again.

Both paths use `contract_runtime::operations::execute_finalized_block()`.
