### ISSUE TITLE
 Replace signal-based queue dumps with console based one

### ISSUE THREAD

**Issue by piotr-dziubecki** [casper-network/casper-node#2546]
As soon as debug console support is merged, the USR1/USR2 way of dumping the event queue should be unified by replacing it with an additional command on the debug console.

**Comment by cspramit** [comment]
@marc-casperlabs are these 1.5.0 stuff, seems the PR is already merged??

**Comment by marc-casperlabs** [comment]
It's not 1.5 stuff and the merged PR is just a prerequisite, sorry!

**Comment by piotr-dziubecki** [comment]
@Fraser999 is this for 1.5?

**Comment by marc-casperlabs** [comment]
No, it's not a blocker @piotr-dziubecki , just a nice-to-have.
