### ISSUE TITLE
Investigate disk space issue

### ISSUE THREAD

**Issue by piotr-dziubecki** [casper-network/casper-node#2558]

**Comment by dwerner** [comment]
My notes on this:

LMDB exhibits write amplification when writing very small values. In my testing, we can do much better (about 50% better) with disk space by moving to RocksDb with zstd compression for our global state data store.

![image](https://user-images.githubusercontent.com/1497784/152026579-ce95fc53-64b5-410b-89dd-f1ac8c1a8511.png)
