### ISSUE TITLE
 Upgrade state is not cleared when /etc/casper/[sem_ver] and /var/lib/casper/bin/[sem_ver] are removed.

### ISSUE THREAD

**Issue by piotr-dziubecki** [casper-network/casper-node#2566]
Expected use case for this is a pulled upgrade.  Currently if the directories disappear, the node would still try to start them and crash.  I don't believe it would drop back to previous version.

**Comment by sacherjj** [comment]
This is due to setting in casper-node-launcher-state.toml.  So this would be deleted along with it, or we need to update casper-node-launcher to downgrade if miss was detected.
