### ISSUE TITLE
 Add nctl test for joining node with trusted hash from before the upgrade.

### ISSUE THREAD

**Issue by piotr-dziubecki** [casper-network/casper-node#2569]
Split from #2476.

Scenario:

- 1.5.x (fast-sync) network is running
- remember the trusted hash
- upgrade network to 1.6.x (next version of the fast-sync node)
- try to join a new node with trusted hash from 1.5
- the node is expected to fail with a message

**Comment by TomVasile** [comment]
@piotr-dziubecki @Fraser999 @cspramit 
"the node is expected to fail with a message"

what is the expected message?

Also I want to confirm that we really mean "the node is expected to fail" using an early hash? This is a pretty big deviation from the normal. Lvl3 guys currently ask users to use an earlier trusted hash ( If i recall correctly :P ) when they are helping users with syncing issues.

**Comment by Fraser999** [comment]
The error message should contain `failed to sync linear chain` and also `the trusted block has an older version. Current version is A.B.C, but trusted block header has older version BLOCK-HEADER` where `A.B.C` is the current protocol version, and `BLOCK-HEADER` is the debug output of the trusted block's header.

And, yes, the node will exit with an error under this condition.

**Comment by TomVasile** [comment]
https://github.com/casper-network/casper-node/pull/2693

**Comment by TomVasile** [comment]
2693 merged
