### ISSUE TITLE
 Fast sync before and after an upgrade.

### ISSUE THREAD

**Issue by piotr-dziubecki** [casper-network/casper-node#2574]
If the trusted hash is from before the most recent upgrade, but that upgrade is already older than ~2 eras, the node would currently fail to join: after applying the upgrade it would try to start consensus, but the other nodes wouldn't have the first era after the upgrade anymore.
Instead, we should continue fast syncing after applying the upgrade.

**Comment by fizyk20** [comment]
Closed by #2785 and #2791.
