### ISSUE TITLE
Is kill -USR1 $NODE_PID still working?

### ISSUE THREAD

**Issue by GuybrushX** [casper-network/casper-node#2613]
1. Please clarify "working directory" in the README.md for the queue_dump.json file

2. Out of curiosity I tried the command also mentioned in the README.md:
```
kill -USR1 $NODE_PID
```

Exactly nothing happened. I also couldn't find the queue_dump.json file:
```
find / -name queue_dump.json
```

The node is in the mainnet but not validating, no bid, not bonded -> could that be the reason?

3. I also just tried the following command out of curiosity:
```
kill -USR2 $NODE_PID
```

-> That command crashed the node causing a trie-state check etc.

I don't know the Un*x process and signal handling good enough but the node shouldn't just crash when it receives an unknown signal I guess but just ignore it as long as it isn't a -9/SIGKILL which can't be ignored anyway IIRC.

I also saw there is a debug console coming so maybe that is fixed there already or should be tested and improved to not crash so easily.

**Comment by GuybrushX** [comment]
Thanks to @sacherjj on TG I found the files at least. It seems they go to /tmp and include a timestamp:
```
# find / -name queue_dump*
/tmp/queue_dump_debug-2022-01-20T18:56:12.337Z.txt
/tmp/queue_dump-2022-01-20T18:56:12.337Z.json
```

So a few things should be corrected I guess:
1. The file name isn't static but includes a timestamp (README.md mentions a static `queue_dump.json` only)
2. There is a JSON + a TXT file created already (README.md mentions JSON only)
3. The file names are different/inconsistent ("_debug" on the TXT file only but not on the JSON file):
- queue_dump-<Timestamp>.json
- queue_dump_debug-<Timestamp>.txt
4. Not crashing on other/unknown signals

**Comment by marc-casperlabs** [comment]
I'll be updating the docs, as the USR1 dumps have been removed in favor of the diagnostics console in recent versions.
