### ISSUE TITLE
Fix Payload::incoming_resource_estimate

### ISSUE THREAD

**Issue by cspramit** [casper-network/casper-node#2644]
We should remove the default implementation of this trait's method and for the impl on Message, we want a value of 1 for
GetRequest, Deploy
GetResponse, Deploy
GetRequest, for all tags used by fast sync operations

**Comment by rafal-ch** [comment]
@marc-casperlabs @Fraser999 
Do we want `1` for `GetRequest::Deploy` or shall we take the value from `PayloadWeights`?

**Comment by marc-casperlabs** [comment]
We want this to be configurable in general, so we can change it during testing and possibly in the case of an emergency at runtime. My favored approach would be to extend `PayloadWeights` with values for all types (that's what it was made for).

**Comment by rafal-ch** [comment]
We'll extend the `PayloadWeights` to contain the following params:
* consensus=0
* gossip=0
* finality_signatures=0
* deploy_requests=1
* deploy_responses=1
* block_requests=1
* block_responses=0
* trie_requests=1
* trie_responses=0 

The default values cannot be set in config.
