### ISSUE TITLE
Check and fix all links in the repository

### ISSUE THREAD

**Issue by piotr-dziubecki** [casper-network/casper-node#2651]
Check for all instances of the word `CasperLabs` and ensure that any which are links like `https://github.com/CasperLabs...` are updated to the appropriate new repos.

Also ensure that any changes which are still relevant from #1298 are applied.

**Comment by RitaMAllenCA** [comment]
Closing this because it is no longer an issue with the new rebranding.   It is an old ticket and likely no longer relevant.  If it is, a new ticket will be opened.
