### ISSUE TITLE
Fast-sync joins during active deploy load cause network stalls

### ISSUE THREAD

**Issue by thamps-casp** [casper-network/casper-node#2667]
A small network loaded with 90k deploys and concurrently loaded with 30k transfer deploys and 20 joining nodes, slows down the network. 

The network seems to be prioritizing the joining of fast-sync nodes and stalls the network even with incoming message rate limits in place.

Network : 5 validators + 2 non-validators (genesis)
Deploys: 90K
Joining Nodes: 20
Test: 30K transfers + 20 joining nodes

Config: {"config":{"max_parallel_deploy_fetches": 1000, "max_parallel_trie_fetches": 1000, "max_incoming_message_rate_non_validators":200}, "chainspec":{"era_duration": \"30minutes\"}}

Different settings where attempted for `max_incoming_message_rate_non_validators` = 200 / 1000/ 2000 / 3000. All settings have some outcome.

Tests Report: https://docs.google.com/spreadsheets/d/1rOL_ejIIEeANItrzG9EqkqU1QLAQiswr7gUIWU6Z8Y4/edit#gid=0

**Comment by marc-casperlabs** [comment]
This is fixed as of https://github.com/casper-network/casper-node/pull/2678
