### ISSUE TITLE
Fix Get Trie Buckets In Metrics

### ISSUE THREAD

**Issue by cspramit** [casper-network/casper-node#2691]
Grafana only shows the values in multiples of 10ms as indicated below. This does not provide useful information.

![image.png](https://images.zenhubusercontent.com/6052183097bb2e8b11cdf45e/82a19eeb-0297-4212-bcdb-40dd8832ac3a)

**Comment by goral09** [comment]
I can't find the metric that the screenshot was taken of. Also, we aren't measuring anything in the ContractRuntime in ms, it's all in seconds.

**Comment by goral09** [comment]
I've checked the dashboards (https://grafana.casperlabs.io/d/NtiRElLMg/release-test-metrics-overview-v3-1?orgId=1&from=1648594360710&to=1648643034556&editPanel=203) and they seem to be allright. The comment on the ticket is incorrect - these metrics are not "cut off", they fell into the small bucket of 10ms. The actual metrics starts at 10ms and goes as high as 10s. The screenshot shows 10ms which means the actual measurement was BELOW the smallest value 10ms.

They're not multiples of 10ms either. It's:
10ms
20ms
40ms
80ms
160ms
320ms
640ms
1.2s
2.4s
5s
10s

**Comment by goral09** [comment]
@cspramit who is the reporter here?
