### ISSUE TITLE
Remove integrity_check from the node

### ISSUE THREAD

**Issue by piotr-dziubecki** [casper-network/casper-node#2707]
The "fast-sync" node should not perform any kind of data integrity checks. Apparently, even when the node has some incorrect state it should be able to "repair" it via the process currently known as "archival sync".
Potentially also get rid of the PidFile, but this still need to be agreed.

**Comment by cspramit** [comment]
@rafal-ch @marc-casperlabs is ok with removal of pid file - just fyi ( if ok capture the point estimate accordingly)
