### ISSUE TITLE
Add resumption-safety to rocksdb migration

### ISSUE THREAD

**Issue by cspramit** [casper-network/casper-node#2717]
As a part of the optimizations needed to make the lmdb to rocksdb migration move faster, we took out resumability. This means that a partial migration (stopped while migrating) will fail to write the nodes to the trie that it was processing.
We need to keep track of what tries (by key) have been migrated, and use that to drive the migration.

**Comment by dwerner** [comment]
resolved this in https://github.com/casper-network/casper-node-private/pull/70
