### ISSUE TITLE
Align all RPC tests to the feat-fast-sync branch 

### ISSUE THREAD

**Issue by cspramit** [casper-network/casper-node#2728]
Align all RPC tests to the feat-fast-sync branch - some of the RPC requests behave differently

**Comment by TomVasile** [comment]
Turned off failing rpc tests in: https://github.com/casper-network/casper-test/pull/67

**Comment by rafal-ch** [comment]
Tests are being aligned on this branch: https://github.com/rafal-ch/casper-test/tree/2728_align_tests_to_latest_node

Checklist:
* rpc_chain_get_block - DONE
* rpc_chain_get_block_transfers - DONE
* rpc_get_era_info_by_switch_block - DONE
* rpc_get_state_root_hash - DONE
* rpc_info_get_peers - DONE
* rpc_info_get_status - DONE
* rpc_jsonrpc_error_codes - DONE
* rpc_list_rpcs - DONE
* rpc_put_deploy_get_deploy - DONE
* rpc_query_global_state_get_balance - DONE
* rpc_send_deploy_file - DONE
* rpc_server_mirrors_request_id - DONE
* rpc_state_get_account_info - DONE
* rpc_state_get_auction_info - DONE
* rpc_transfer - DONE

**Comment by rafal-ch** [comment]
There is a PR under review that should close this ticket: https://github.com/casper-network/casper-test/pull/69


@TomVasile Once it's merged, we can revert https://github.com/casper-network/casper-test/pull/67
