### ISSUE TITLE
List and add tests  for all recently modified or added endpoints

### ISSUE THREAD

**Issue by cspramit** [casper-network/casper-node#2729]
List and cover with tests all recently modified or added endpoints, for example, info_get_chainspec added here

**Comment by devendran-m** [comment]
Sidecar based. Check with Jakub.

**Comment by devendran-m** [comment]
Per the triage with @zajko on 3rd Oct;
- Close this ticket in favour of having a set of tickets to test the JSON RPC from the perspective of sidecar. 
- Action - To list all the recently changed endpoints and add it to the new set of tickets.
