### ISSUE TITLE
Emergency restart test failure for 2 new validating nodes

### ISSUE THREAD

**Issue by cspramit** [casper-network/casper-node#2748]
**Issue:** - 2 validator from set B not starting up after emergency restart.

**Dump** -  http://genesis.casperlabs.io/rti-fast-sync/casper-node-dumps/16Mar22-fast-sync-emergency/16032022_0738/dump_download_list.txt

**Scenario** -
Test: Emergency Restart
stop 2 of 5 initial validator nodes (set A) and stall network
generate new validator list global state toml with 3 initial validators (set B) + 2 non-validators (set C)
generate new emergency upgrade package + global state toml +  publish to all nodes of network
restart the new validator list (set B + set C) nodes
emergency restart successful with new validators = Set B + Set C

used the global-state-update-gen binary from this commit

{"timestamp":"Mar 16 07:16:38.683","level":"WARN","fields":{"message":"failed to download trie","err":"ExecutionEngine(Storage(BytesRepr(Formatting)))","trie_key":"16b5f6576703a6c45be00bde2e799b5f66d9a8769a2257c436c504222c5005e3"},"target":"casper_node::components::chain_synchronizer::operations"}
{"timestamp":"Mar 16 07:16:38.683","level":"ERROR","fields":{"message":"failed to sync linear chain","error":"Storage error: Deserialization error: formatting"},"target":"casper_node::components::chain_synchronizer"}
{"timestamp":"Mar 16 07:16:38.683","level":"ERROR","fields":{"message":"fatal error via control announcement","file":"node/src/components/chain_synchronizer.rs","line":"161","msg":"Storage error: Deserialization error: formatting"},"target":"casper_node::reactor"}

**Comment by cspramit** [comment]
@thamps-casp please provide further log and other info here

**Comment by cspramit** [comment]
Reference chat - https://casperlabs-team.slack.com/archives/C01ULKL8G8J/p1647416770600559

**Comment by thamps-casp** [comment]
Steps to re-produce with feat-fast-sync branch commit: `3bfc5f0d711634d13d32df9df178475fb9b702ed`

1. provision 5 validator + 2 non-validator network
2. **Set A** ( 2 validator  to suspend ), **Set B** (3 validator for new validator list), **Set C** (2 non-validator for new validator list)
3. get previous switch block info for emergency restart activation
4. stop ALL 5 validator nodes - **Set A + Set B** - Network Stalls
5. create global-state.toml with new validator list - **Set B + Set C**
6. create emergency upgrade package 1_5_1 with same build
7. publish upgrade package and global-state.toml to **Set B + Set C**
8. Stop and Start New Validator List Nodes ONLY - **Set B + Set C**

After trigger node restart, all nodes report ERROR with
```
{"timestamp":"Mar 17 01:45:05.922","level":"ERROR","fields":{"message":"failed to sync linear chain","error":"Storage error: Deserialization error: formatting"},"target":"casper_node::components::chain_synchronizer"}
{"timestamp":"Mar 17 01:45:05.922","level":"ERROR","fields":{"message":"fatal error via control announcement","file":"node/src/components/chain_synchronizer.rs","line":"161","msg":"Storage error: Deserialization error: formatting"},"target":"casper_node::reactor"}
```

**Test Network Info:**
Set A: 172.142.85.181 (validator), 172.142.107.247(validator)
Set B: 172.142.61.2 (validator), 172.142.67.29(validator), 172.142.73.14(validator)
Set C: 172.142.72.205(non-validator), 172.142.53.242(non-validator)

New Validator list: Set B + Set C
Suspended Validator Nodes for Emergency restart: Set A

**Test Network Dumps:**
http://genesis.casperlabs.io/rti-fast-sync/casper-node-dumps/rti-fast-sync/17032022_0138/dump_download_list.txt

**Test Network Database:**
http://genesis.casperlabs.io/rti-fast-sync/casper-node-dumps/rti-fast-sync/17032022_0138/db/172.142.61.2/rti-fast-sync-v-1-db.tar.gz
http://genesis.casperlabs.io/rti-fast-sync/casper-node-dumps/rti-fast-sync/17032022_0138/db/172.142.73.14/rti-fast-sync-v-0-db.tar.gz
http://genesis.casperlabs.io/rti-fast-sync/casper-node-dumps/rti-fast-sync/17032022_0138/db/172.142.67.29/rti-fast-sync-v-4-db.tar.gz

**Comment by thamps-casp** [comment]
This error was a false positive. It was identified that the Ansible Playbooks had a defect which caused the upgrade package to be replaced by an older 1_5_0 binary or another version altogether.

After fixing the code and step 6
`6. create emergency upgrade package 1_5_1 with same build`

the upgrade package should be of same build as the running network for this test. ie. `3bfc5f0d711634d13d32df9df178475fb9b702ed`

The emergency restart is working as expected.
