### ISSUE TITLE
Eliminate Long Storage Indexing Time at Node Startup

### ISSUE THREAD

**Issue by cspramit** [casper-network/casper-node#2751]
Description: Every time the node starts, it creates indices of `block height -> block hash` and `era number -> block hash`.  These are expensive and take ~1.5 minutes on mainnet.

**Acceptance Criterion:** Either eliminate the indices altogether or eliminate the long wait time to create them for good.  We might need a one-time indexing to get rid of them though.

4.11.23 Ed's PR for blockchain_type removes this behavior, and renders this not necessary (enables lazy indexing). The feature that this supports is likely to move to sidecar, not node.

**Comment by RitaMAllenCA** [comment]
@alsrdn If you pull this into the sprint, please start with Fraser.
