### ISSUE TITLE
Port RocksDB branch to 1.4.5-alt

### ISSUE THREAD

**Issue by piotr-dziubecki** [casper-network/casper-node#2755]
Split up the changes from c1323e5b75af3b2e9d6a8d01d4a29a71012c090b into manageable chunks and, if possible, apply the to the `release-1.4.5-alt` branch. The end result should be a version of 1.4.5 that runs on RocksDB.

**Comment by marc-casperlabs** [comment]
Initial attempts to port just the RocksDB changes failed, as it is dependent (not only for performance) on some of the storage changes, which in turn require the full changeset of the offloaded storage migration.

**Comment by marc-casperlabs** [comment]
The changeset has been split into roughly three parts, see https://github.com/marc-casperlabs/casper-node/tree/rocksdb-implementation-split

The four commits are storage changes, rocksdb impl changes and test support changes, those three combined are 100% matching the commit they are based off of. The final commit is the code review changes applied.

The private repo contains a cherry-pickable backported version of the storage changes. We will go ahead by apply this backport version onto 1.4.5-alt, along with a backported version of the RocksDB changes (which @Fraser999 kindly helped out with), while ignoring the testing support changes.

**Comment by marc-casperlabs** [comment]
After this process, the fourth commit 5f072c24543092807840102ffa9208aa8c153daa should be applied. *Note*: Changes from up to https://github.com/dwerner/casper-node/commit/218377c25745e707a9cb939fb0693d3c876c9107 have already been folded into these commits as well, so we should be done after this.
