### ISSUE TITLE
Minor cleanups

### ISSUE THREAD

**Issue by piotr-dziubecki** [casper-network/casper-node#2762]
* replace all `.../CasperLabs/casper-node` URLs with `.../casper-network/casper-node`
* remove
    * `build_wasm_package.sh`
    * `docker_make.sh`
    * `joiner-dev-tmux.sh`
    * `run-dev-tmux.sh`
    * `stop-dev.sh`
    * `update-rev.sh`
    * `upload.sh`
* avoid using `#[serde(with = "HexForm")]` in `ExecutableDeployItem::ModuleBytes::module_bytes` (we can remove the dependency entirely)
* feature-gate `CorrelationId::is_empty()` via `#[cfg(test)]`

**Comment by devendran-m** [comment]
Triaged;
* replace all `.../CasperLabs/casper-node` URLs with `.../casper-network/casper-node` - Still some references are there. Needs cleaning up.
* remove - Done
    * `build_wasm_package.sh`
    * `docker_make.sh`
    * `joiner-dev-tmux.sh`
    * `run-dev-tmux.sh`
    * `stop-dev.sh`
    * `update-rev.sh`
    * `upload.sh`
* avoid using `#[serde(with = "HexForm")]` in `ExecutableDeployItem::ModuleBytes::module_bytes` (we can remove the dependency entirely) - Done
* feature-gate `CorrelationId::is_empty()` via `#[cfg(test)]` - Removed

**Comment by devendran-m** [comment]
Triage update - Create new ticket for "replace all .../CasperLabs/casper-node URLs with .../casper-network/casper-node" and close this ticket.

**Comment by devendran-m** [comment]
New ticket created to replace incorrect URLs - https://github.com/casper-network/casper-node/issues/4902
