### ISSUE TITLE
Implement `GlobalStateEntry` for Capnproto

### ISSUE THREAD

**Issue by devendran-m** [casper-network/casper-node#2763]

**Comment by xcthulhu** [comment]
See https://github.com/casper-network/casper-node/compare/dev...feat-capnproto#diff-3932e57afb4602ad0080d518aa60f2c1b4c5a6f50d53176d32d071b0d8527015R36

**Comment by xcthulhu** [comment]
This particular abstraction is not appropriate for Storage 2.0.  The new trie will not store leaves with values since they are redundant.
