### ISSUE TITLE
Implement `EraEnd` for Capnproto

### ISSUE THREAD

**Issue by devendran-m** [casper-network/casper-node#2764]
Acceptance criteria:
- Schema file for `EraEnd` is created
- The `EraEnd` type is (de)serializable using CapnProto

**Comment by rafal-ch** [comment]
Types converted so far:
* U512
* BlockBody
* BlockHeader
* Block
* DeployHash
* Digest
* EraId
* EraReport
* EraEnd
* PublicKey
* AccountHash
* Weight
* ActionThresholds
* AssociatedKeys
* TypeMismatch - in progress...
