### ISSUE TITLE
Implement extract `Uref`s routine for `CLValue` in Capnproto

### ISSUE THREAD

**Issue by devendran-m** [casper-network/casper-node#2765]

**Comment by xcthulhu** [comment]
In particular, we need to port the following routine https://github.com/xcthulhu/casper-node/blob/7881d1d6638a8c4fab447b47dfb8b957ef77f8bd/execution_engine/src/core/runtime/mod.rs#L162-L162

**Comment by xcthulhu** [comment]
`CLValue` needs to stay in bytesrepr/borsh format for compatibility reasons.

The new API is not planned to be structured around `CLValue`.

Closing this for now.
