### ISSUE TITLE
Enable NCTL regression test for querying auction-info

### ISSUE THREAD

**Issue by cspramit** [casper-network/casper-node#2767]
We have written an nctl regression  test that ensures we can query for historical auction data in a Protocol version before 1.4.0, however that test needs to be wired up to be run. We have confirmed that the test does indeed work and it needs to be wired up with a change to the shell file that works with the global-state-update-gen tool.

The PR introducing the test: https://github.com/casper-network/casper-node-private/pull/58

**Comment by TomVasile** [comment]
PR: https://github.com/casper-network/casper-node-private/pull/68

**Comment by TomVasile** [comment]
merged
