### ISSUE TITLE
Casper Node 1.4.4 not available in official Debian Repository

### ISSUE THREAD

**Issue by the-smooth-operator** [casper-network/casper-node#2768]
The last version available in https://repo.casperlabs.io/releases is `1.4.3-0`.
Can I rely on this repository to have always the latest version, or should I not rely on it and always build the binary by myself?

**Comment by sacherjj** [comment]
Casper-node is never distributed from a debian repo.  casper-client and casper-node-launcher are distributed there.  

casper-node-launcher is currently at 1.0.0.   
casper-client used to be part of the casper-node repo, but was broken out into its own repo: https://github.com/casper-ecosystem/casper-client-rs

casper-client is backward and forward compatible to the casper-node software (however, might need to be updated if new APIs are introduced in the RPC).   You should not expect casper-client to be published with every casper-node binary release.
