### ISSUE TITLE
 Change rpc_server::rpcs::common::ErrorData to also include HighestBlockHeight(u64)

### ISSUE THREAD

**Issue by cspramit** [casper-network/casper-node#2780]
Change the get_lowest_contiguous_block_height_from_storage to get_highest_contiguous_range_from_storage and update as necessary in storage to provide the lowest contiguous block height and the highest block height in a single responde

**Comment by rafal-ch** [comment]
The error response will now look like this:
```
{
	"jsonrpc": "2.0",
	"id": "1",
	"error": {
		"code": -32001,
		"message": "block at height 200 not stored on this node",
		"data": {
			"highest_contiguous_block_height_range": [3, 93]
		}
	}
}
```
