### ISSUE TITLE
Change RPC server to not provide success responses for data outside its contiguous block range

### ISSUE THREAD

**Issue by cspramit** [casper-network/casper-node#2781]
The intent is that a request specifying a block identifier (height or hash), if that block's height is lower than the lowest contiguous block height as known by storage, then the server should respond with an ErrorData rather than success.

RPCs affected are:
* `chain_get_block`
* `chain_get_block_transfers`
* `chain_get_state_root_hash`
* `chain_get_era_info_by_switch_block`
* `state_get_auction_info`
* `state_get_account_info`
* `query_global_state` - only where using `GlobalStateIdentifier::BlockHash`

These RPCs are not affected:
* `state_get_item`
* `state_get_balance`
* `state_get_dictionary_item`

**Comment by rafal-ch** [comment]
The expected behavior is as follows:
```
| case | full blocks | seq.            | req. height | current resp. | new resp. |
|------|-------------|-----------------|-------------|---------------|-----------|
| 1    | 0-100       | 0-100           | 5           | Ok            | Ok        |
| 2    | 0-100       | 0-100           | 150         | Err           | Err       |
| 3    | 0-100       | 1-30 50-100     | 70          | Ok            | Ok        |
| 4    | 0-100       | 1-30 50-100     | 20          | Ok            | Err       | <-- actual change here
| 5    | 0-100       | 1-30 50-100     | 150         | Err           | Err       |
| 6    | 50-100      | 30-100 (a bug?) | 40          | Err           | Still Err |
```
