### ISSUE TITLE
Should return correct exit code

### ISSUE THREAD

**Issue by cspramit** [casper-network/casper-node#2784]
**sudo -u casper /etc/casper/node_util.py stage_protocols casper-test.conf
Should return exit code 0 and not 1 if executed successfully:**

e24@ip-178-216-202-150:/etc/casper$ sudo -u casper /etc/casper/node_util.py stage_protocols casper-test.conf
Pulling protocol for 1_0_0.
Using bin mode file of bin.tar.gz
Downloading http://casper-genesis.make.services/casper-test/1_0_0/config.tar.gz to /etc/casper/config.tar.gz
Extracting /etc/casper/config.tar.gz to /etc/casper/1_0_0
Deleting /etc/casper/config.tar.gz
Downloading http://casper-genesis.make.services/casper-test/1_0_0/bin.tar.gz to /var/lib/casper/bin/bin.tar.gz
Extracting /var/lib/casper/bin/bin.tar.gz to /var/lib/casper/bin/1_0_0
Deleting /var/lib/casper/bin/bin.tar.gz
Creating config for 1_0_0.
Querying your external IP...
 amazonaws.com says '178.216.202.150' with Status: 200
 ifconfig.me says '178.216.202.150' with Status: 200
 ident.me says '178.216.202.150' with Status: 200
Using detected ip: 178.216.202.150
Pulling protocol for 1_1_0.
Using bin mode file of bin.tar.gz
Downloading http://casper-genesis.make.services/casper-test/1_1_0/config.tar.gz to /etc/casper/config.tar.gz
Extracting /etc/casper/config.tar.gz to /etc/casper/1_1_0
Deleting /etc/casper/config.tar.gz
Downloading http://casper-genesis.make.services/casper-test/1_1_0/bin.tar.gz to /var/lib/casper/bin/bin.tar.gz
Extracting /var/lib/casper/bin/bin.tar.gz to /var/lib/casper/bin/1_1_0
Deleting /var/lib/casper/bin/bin.tar.gz
Creating config for 1_1_0.
Using detected ip: 178.216.202.150
Pulling protocol for 1_1_2.
Using bin mode file of bin.tar.gz
Downloading http://casper-genesis.make.services/casper-test/1_1_2/config.tar.gz to /etc/casper/config.tar.gz
Extracting /etc/casper/config.tar.gz to /etc/casper/1_1_2
Deleting /etc/casper/config.tar.gz
Downloading http://casper-genesis.make.services/casper-test/1_1_2/bin.tar.gz to /var/lib/casper/bin/bin.tar.gz
Extracting /var/lib/casper/bin/bin.tar.gz to /var/lib/casper/bin/1_1_2
Deleting /var/lib/casper/bin/bin.tar.gz
Creating config for 1_1_2.
Using detected ip: 178.216.202.150
Pulling protocol for 1_2_0.
Using bin mode file of bin.tar.gz
Downloading http://casper-genesis.make.services/casper-test/1_2_0/config.tar.gz to /etc/casper/config.tar.gz
Extracting /etc/casper/config.tar.gz to /etc/casper/1_2_0
Deleting /etc/casper/config.tar.gz
Downloading http://casper-genesis.make.services/casper-test/1_2_0/bin.tar.gz to /var/lib/casper/bin/bin.tar.gz
Extracting /var/lib/casper/bin/bin.tar.gz to /var/lib/casper/bin/1_2_0
Deleting /var/lib/casper/bin/bin.tar.gz
Creating config for 1_2_0.
Using detected ip: 178.216.202.150
Pulling protocol for 1_2_1.
Using bin mode file of bin.tar.gz
Downloading http://casper-genesis.make.services/casper-test/1_2_1/config.tar.gz to /etc/casper/config.tar.gz
Extracting /etc/casper/config.tar.gz to /etc/casper/1_2_1
Deleting /etc/casper/config.tar.gz
Downloading http://casper-genesis.make.services/casper-test/1_2_1/bin.tar.gz to /var/lib/casper/bin/bin.tar.gz
Extracting /var/lib/casper/bin/bin.tar.gz to /var/lib/casper/bin/1_2_1
Deleting /var/lib/casper/bin/bin.tar.gz
Creating config for 1_2_1.
Using detected ip: 178.216.202.150
Pulling protocol for 1_3_1.
Using bin mode file of bin.tar.gz
Downloading http://casper-genesis.make.services/casper-test/1_3_1/config.tar.gz to /etc/casper/config.tar.gz
Extracting /etc/casper/config.tar.gz to /etc/casper/1_3_1
Deleting /etc/casper/config.tar.gz
Downloading http://casper-genesis.make.services/casper-test/1_3_1/bin.tar.gz to /var/lib/casper/bin/bin.tar.gz
Extracting /var/lib/casper/bin/bin.tar.gz to /var/lib/casper/bin/1_3_1
Deleting /var/lib/casper/bin/bin.tar.gz
Creating config for 1_3_1.
Using detected ip: 178.216.202.150
Pulling protocol for 1_3_2.
Using bin mode file of bin.tar.gz
Downloading http://casper-genesis.make.services/casper-test/1_3_2/config.tar.gz to /etc/casper/config.tar.gz
Extracting /etc/casper/config.tar.gz to /etc/casper/1_3_2
Deleting /etc/casper/config.tar.gz
Downloading http://casper-genesis.make.services/casper-test/1_3_2/bin.tar.gz to /var/lib/casper/bin/bin.tar.gz
Extracting /var/lib/casper/bin/bin.tar.gz to /var/lib/casper/bin/1_3_2
Deleting /var/lib/casper/bin/bin.tar.gz
Creating config for 1_3_2.
Using detected ip: 178.216.202.150
Pulling protocol for 1_3_4.
Using bin mode file of bin.tar.gz
Downloading http://casper-genesis.make.services/casper-test/1_3_4/config.tar.gz to /etc/casper/config.tar.gz
Extracting /etc/casper/config.tar.gz to /etc/casper/1_3_4
Deleting /etc/casper/config.tar.gz
Downloading http://casper-genesis.make.services/casper-test/1_3_4/bin.tar.gz to /var/lib/casper/bin/bin.tar.gz
Extracting /var/lib/casper/bin/bin.tar.gz to /var/lib/casper/bin/1_3_4
Deleting /var/lib/casper/bin/bin.tar.gz
Creating config for 1_3_4.
Using detected ip: 178.216.202.150
Pulling protocol for 1_4_1.
Using bin mode file of bin.tar.gz
Downloading http://casper-genesis.make.services/casper-test/1_4_1/config.tar.gz to /etc/casper/config.tar.gz
Extracting /etc/casper/config.tar.gz to /etc/casper/1_4_1
Deleting /etc/casper/config.tar.gz
Downloading http://casper-genesis.make.services/casper-test/1_4_1/bin.tar.gz to /var/lib/casper/bin/bin.tar.gz
Extracting /var/lib/casper/bin/bin.tar.gz to /var/lib/casper/bin/1_4_1
Deleting /var/lib/casper/bin/bin.tar.gz
Creating config for 1_4_1.
Using detected ip: 178.216.202.150
Pulling protocol for 1_4_2.
Using bin mode file of bin.tar.gz
Downloading http://casper-genesis.make.services/casper-test/1_4_2/config.tar.gz to /etc/casper/config.tar.gz
Extracting /etc/casper/config.tar.gz to /etc/casper/1_4_2
Deleting /etc/casper/config.tar.gz
Downloading http://casper-genesis.make.services/casper-test/1_4_2/bin.tar.gz to /var/lib/casper/bin/bin.tar.gz
Extracting /var/lib/casper/bin/bin.tar.gz to /var/lib/casper/bin/1_4_2
Deleting /var/lib/casper/bin/bin.tar.gz
Creating config for 1_4_2.
Using detected ip: 178.216.202.150
Pulling protocol for 1_4_3.
Using bin mode file of bin.tar.gz
Downloading http://casper-genesis.make.services/casper-test/1_4_3/config.tar.gz to /etc/casper/config.tar.gz
Extracting /etc/casper/config.tar.gz to /etc/casper/1_4_3
Deleting /etc/casper/config.tar.gz
Downloading http://casper-genesis.make.services/casper-test/1_4_3/bin.tar.gz to /var/lib/casper/bin/bin.tar.gz
Extracting /var/lib/casper/bin/bin.tar.gz to /var/lib/casper/bin/1_4_3
Deleting /var/lib/casper/bin/bin.tar.gz
Creating config for 1_4_3.
Using detected ip: 178.216.202.150
Pulling protocol for 1_4_4.
Using bin mode file of bin.tar.gz
Downloading http://casper-genesis.make.services/casper-test/1_4_4/config.tar.gz to /etc/casper/config.tar.gz
Extracting /etc/casper/config.tar.gz to /etc/casper/1_4_4
Deleting /etc/casper/config.tar.gz
Downloading http://casper-genesis.make.services/casper-test/1_4_4/bin.tar.gz to /var/lib/casper/bin/bin.tar.gz
Extracting /var/lib/casper/bin/bin.tar.gz to /var/lib/casper/bin/1_4_4
Deleting /var/lib/casper/bin/bin.tar.gz
Creating config for 1_4_4.
Using detected ip: 178.216.202.150
Pulling protocol for 1_4_5.
Using bin mode file of bin.tar.gz
Downloading http://casper-genesis.make.services/casper-test/1_4_5/config.tar.gz to /etc/casper/config.tar.gz
Extracting /etc/casper/config.tar.gz to /etc/casper/1_4_5
Deleting /etc/casper/config.tar.gz
Downloading http://casper-genesis.make.services/casper-test/1_4_5/bin.tar.gz to /var/lib/casper/bin/bin.tar.gz
Extracting /var/lib/casper/bin/bin.tar.gz to /var/lib/casper/bin/1_4_5
Deleting /var/lib/casper/bin/bin.tar.gz
Creating config for 1_4_5.
Using detected ip: 178.216.202.150
e24@ip-178-216-202-150:/etc/casper$ echo $?
1
If the protocols have already been staged, the correct exit code is returned:
e24@ip-178-216-202-150:/etc/casper$ sudo -u casper /etc/casper/node_util.py stage_protocols casper-test.conf
1_0_0: Protocol Staged
1_1_0: Protocol Staged
1_1_2: Protocol Staged
1_2_0: Protocol Staged
1_2_1: Protocol Staged
1_3_1: Protocol Staged
1_3_2: Protocol Staged
1_3_4: Protocol Staged
1_4_1: Protocol Staged
1_4_2: Protocol Staged
1_4_3: Protocol Staged
1_4_4: Protocol Staged
1_4_5: Protocol Staged
e24@ip-178-216-202-150:/etc/casper$ echo $?
0

**Comment by bradjohnl** [comment]
@sacherjj 
The problem is the following.
in the function stage_protocols. There are the following checks:
```
if not self._pull_protocol_version(pv, platform):
                   exit_code = 1`
```
and 
```
if not self._config_from_example(pv, ip, args.replace):
                    exit_code = 1`
```

The problem is that in Python, functions with no return statement return None and this happens:
```
>>> x = None
>>> not x
True
>>> 
```

The if condition always returns True, so the exit code is set to 1 = always error.

As far as I could see, a part from that there is no issue with exit codes.

If you agree, will change the functions to return True if they end successfully so that the logic would work.

**Comment by bradjohnl** [comment]
@sacherjj  @Fraser999 @TomVasile 

I have solved the issue with clippy. I just fixed the code affected by the warnings. 
It was simply complaining of the usage of double quotes to enclose a single char, so it recommended to use single quotes.

Now the cargo audit fails as there are 2 vulnerable packages (See build https://drone-auto-casper-network.casperlabs.io/casper-network/casper-node-launcher/56/1/4):
```
$ cargo audit --deny-warnings
warning: the --deny-warnings flag is deprecated. Please use: --deny warnings
    Fetching advisory database from `https://github.com/RustSec/advisory-db.git`
      Loaded 404 security advisories (from /home/keepupdragon/.cargo/advisory-db)
    Updating crates.io index
    Scanning Cargo.lock for vulnerabilities (79 crate dependencies)
Crate:         regex
Version:       1.5.4
Title:         Regexes with large repetitions on empty sub-expressions take a very long time to parse
Date:          2022-03-08
ID:            RUSTSEC-2022-0013
URL:           https://rustsec.org/advisories/RUSTSEC-2022-0013
Solution:      Upgrade to >=1.5.5
Dependency tree: 
regex 1.5.4
└── tracing-subscriber 0.3.2
    └── casper-node-launcher 1.0.0

Crate:         thread_local
Version:       1.1.3
Title:         Data race in `Iter` and `IterMut`
Date:          2022-01-23
ID:            RUSTSEC-2022-0006
URL:           https://rustsec.org/advisories/RUSTSEC-2022-0006
Solution:      Upgrade to >=1.1.4
Dependency tree: 
thread_local 1.1.3
└── tracing-subscriber 0.3.2
    └── casper-node-launcher 1.0.0
```

I tried to fix the issues with `cargo audit fix`, but I got clippy errors (See build: https://drone-auto-casper-network.casperlabs.io/casper-network/casper-node-launcher/57/1/3):
```
latest: Pulling from casperlabs/casper-node-launcher-build
Digest: sha256:120d2f0ca7f361c30a3768f5708cbbeb939dd3f43b124b6648bbc6ab47d8fa34
Status: Image is up to date for casperlabs/casper-node-launcher-build:latest
+ cargo clippy -- --deny warnings
    Updating crates.io index
 Downloading crates ...
  Downloaded ansi_term v0.12.1
  Downloaded libc v0.2.121
  Downloaded sharded-slab v0.1.4
  Downloaded signal-hook v0.3.13
  Downloaded tracing-core v0.1.24
  Downloaded tracing-attributes v0.1.20
  Downloaded tracing-serde v0.1.3
  Downloaded quote v1.0.17
  Downloaded once_cell v1.10.0
  Downloaded log v0.4.16
  Downloaded indexmap v1.8.1
  Downloaded termcolor v1.1.3
  Downloaded textwrap v0.15.0
  Downloaded tracing-subscriber v0.3.10
  Downloaded syn v1.0.90
  Downloaded nix v0.23.1
  Downloaded matchers v0.1.0
  Downloaded clap v3.1.8
  Downloaded regex v1.5.5
  Downloaded anyhow v1.0.56
  Downloaded smallvec v1.8.0
  Downloaded tracing v0.1.32
  Downloaded thread_local v1.1.4
  Downloaded strsim v0.10.0
  Downloaded os_str_bytes v6.0.0
  Downloaded semver v1.0.7
   Compiling proc-macro2 v1.0.36
   Compiling autocfg v1.1.0
   Compiling unicode-xid v0.2.2
   Compiling syn v1.0.90
   Compiling libc v0.2.121
   Compiling serde_derive v1.0.136
   Compiling serde v1.0.136
   Compiling memchr v2.4.1
    Checking cfg-if v1.0.0
    Checking lazy_static v1.4.0
   Compiling log v0.4.16
    Checking regex-syntax v0.6.25
   Compiling serde_json v1.0.79
   Compiling cc v1.0.73
    Checking itoa v1.0.1
    Checking hashbrown v0.11.2
    Checking gimli v0.26.1
   Compiling semver v1.0.7
    Checking bitflags v1.3.2
    Checking ryu v1.0.9
    Checking once_cell v1.10.0
    Checking adler v1.0.2
   Compiling anyhow v1.0.56
    Checking pin-project-lite v0.2.8
   Compiling signal-hook v0.3.13
    Checking rustc-demangle v0.1.21
    Checking ansi_term v0.12.1
    Checking textwrap v0.15.0
    Checking termcolor v1.1.3
    Checking strsim v0.10.0
    Checking smallvec v1.8.0
    Checking tracing-core v0.1.24
    Checking sharded-slab v0.1.4
    Checking thread_local v1.1.4
   Compiling memoffset v0.6.5
   Compiling miniz_oxide v0.4.4
   Compiling indexmap v1.8.1
    Checking tracing-log v0.1.2
   Compiling backtrace v0.3.64
    Checking object v0.27.1
    Checking os_str_bytes v6.0.0
   Compiling quote v1.0.17
    Checking regex-automata v0.1.10
    Checking regex v1.5.5
    Checking signal-hook-registry v1.4.0
    Checking atty v0.2.14
    Checking nix v0.23.1
    Checking clap v3.1.8
    Checking addr2line v0.17.0
    Checking matchers v0.1.0
   Compiling tracing-attributes v0.1.20
    Checking tracing v0.1.32
    Checking tracing-serde v0.1.3
    Checking toml v0.5.8
    Checking tracing-subscriber v0.3.10
    Checking casper-node-launcher v1.0.0 (/drone/src)
error[E0432]: unresolved imports `clap::crate_description`, `clap::crate_version`
  --> src/main.rs:18:12
   |
18 | use clap::{crate_description, crate_version, App, Arg};
   |            ^^^^^^^^^^^^^^^^^  ^^^^^^^^^^^^^ no `crate_version` in the root
   |            |
   |            no `crate_description` in the root

error: cannot determine resolution for the macro `crate_version`
  --> src/main.rs:77:18
   |
77 |         .version(crate_version!())
   |                  ^^^^^^^^^^^^^
   |
   = note: import resolution is stuck, try simplifying macro imports

error: cannot determine resolution for the macro `crate_description`
  --> src/main.rs:88:16
   |
88 |         .about(crate_description!());
   |                ^^^^^^^^^^^^^^^^^
   |
   = note: import resolution is stuck, try simplifying macro imports

error: use of deprecated struct `clap::App`: Replaced with `Command`
  --> src/main.rs:18:46
   |
18 | use clap::{crate_description, crate_version, App, Arg};
   |                                              ^^^
   |
   = note: `-D deprecated` implied by `-D warnings`

error: use of deprecated struct `clap::App`: Replaced with `Command`
  --> src/main.rs:76:15
   |
76 |     let app = App::new(APP_NAME)
   |               ^^^

error[E0599]: no method named `about` found for struct `clap::Arg` in the current scope
  --> src/main.rs:83:18
   |
83 |                 .about("Forces the launcher to run the specified version of the node, for example \"1.2.3\"")
   |                  ^^^^^ method not found in `clap::Arg<'_>`

Some errors have detailed explanations: E0432, E0599.
For more information about an error, try `rustc --explain E0432`.
error: could not compile `casper-node-launcher` due to 6 previous errors
```

**Comment by bradjohnl** [comment]
I have reverted the cargo audit fix, but then the build for the casper-node-launcher was failing.
See: https://drone-auto-casper-network.casperlabs.io/casper-network/casper-node-launcher/63/1/2

```
latest: Pulling from casperlabs/casper-node-launcher-build
Digest: sha256:d8285537c6760dc2f7821312725895a6d39e3f7ef906f9e2d582985f528b3835
Status: Downloaded newer image for casperlabs/casper-node-launcher-build:latest
+ rustup update stable
info: syncing channel updates for 'stable-x86_64-unknown-linux-gnu'
info: latest update on 2022-04-07, rust version 1.60.0 (7737e0b5c 2022-04-04)
info: downloading component 'cargo'
info: downloading component 'clippy'
info: downloading component 'rust-docs'
info: downloading component 'rust-std'
info: downloading component 'rustc'
info: downloading component 'rustfmt'
info: removing previous version of component 'cargo'
info: rolling back changes
error: could not rename component file from '/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/etc/bash_completion.d' to '/root/.rustup/tmp/d47usblq9j3k14_6_dir/bk': Invalid cross-device link (os error 18)
```

I see the Docker image has been re-uploaded 1 week ago which should have fixed the error.
After that I have re-built and re-uploaded the build Docker image. It now goes past that, but I still got the audit errors:
```
latest: Pulling from casperlabs/casper-node-launcher-build
Digest: sha256:bb3be4b3965c5a9bb8f88ce5299973b6e8442ba4ad577c7327d0c2fad7543982
Status: Image is up to date for casperlabs/casper-node-launcher-build:latest
+ cargo audit --deny warnings  --ignore RUSTSEC-2021-0119 --ignore RUSTSEC-2020-0159
    Fetching advisory database from `https://github.com/RustSec/advisory-db.git`
      Loaded 404 security advisories (from /root/.cargo/advisory-db)
    Updating crates.io index
    Scanning Cargo.lock for vulnerabilities (79 crate dependencies)
error: 2 vulnerabilities found!
Crate:         regex
Version:       1.5.4
Title:         Regexes with large repetitions on empty sub-expressions take a very long time to parse
Date:          2022-03-08
ID:            RUSTSEC-2022-0013
URL:           https://rustsec.org/advisories/RUSTSEC-2022-0013
Solution:      Upgrade to >=1.5.5
Dependency tree: 
regex 1.5.4
└── tracing-subscriber 0.3.2
    └── casper-node-launcher 1.0.0

Crate:         thread_local
Version:       1.1.3
Title:         Data race in `Iter` and `IterMut`
Date:          2022-01-23
ID:            RUSTSEC-2022-0006
URL:           https://rustsec.org/advisories/RUSTSEC-2022-0006
Solution:      Upgrade to >=1.1.4
Dependency tree: 
thread_local 1.1.3
└── tracing-subscriber 0.3.2
    └── casper-node-launcher 1.0.0
```

I have re-attempted to fix them using cargo audit fix, but I still get the same errors:
```
error[E0432]: unresolved imports `clap::crate_description`, `clap::crate_version`
  --> src/main.rs:18:12
   |
18 | use clap::{crate_description, crate_version, App, Arg};
   |            ^^^^^^^^^^^^^^^^^  ^^^^^^^^^^^^^ no `crate_version` in the root
   |            |
   |            no `crate_description` in the root

error: cannot determine resolution for the macro `crate_version`
  --> src/main.rs:77:18
   |
77 |         .version(crate_version!())
   |                  ^^^^^^^^^^^^^
   |
   = note: import resolution is stuck, try simplifying macro imports

error: cannot determine resolution for the macro `crate_description`
  --> src/main.rs:88:16
   |
88 |         .about(crate_description!());
   |                ^^^^^^^^^^^^^^^^^
   |
   = note: import resolution is stuck, try simplifying macro imports

error: use of deprecated struct `clap::App`: Replaced with `Command`
  --> src/main.rs:18:46
   |
18 | use clap::{crate_description, crate_version, App, Arg};
   |                                              ^^^
   |
   = note: `-D deprecated` implied by `-D warnings`

error: use of deprecated struct `clap::App`: Replaced with `Command`
  --> src/main.rs:76:15
   |
76 |     let app = App::new(APP_NAME)
   |               ^^^

error[E0599]: no method named `about` found for struct `clap::Arg` in the current scope
  --> src/main.rs:83:18
   |
83 |                 .about("Forces the launcher to run the specified version of the node, for example \"1.2.3\"")
   |                  ^^^^^ method not found in `clap::Arg<'_>`

Some errors have detailed explanations: E0432, E0599.
For more information about an error, try `rustc --explain E0432`.
error: could not compile `casper-node-launcher` due to 6 previous errors
```


@Fraser999 @sacherjj @TomVasile
