### ISSUE TITLE
Implement "working set" and add migration to feat-rocksdb as part of forced migration

### ISSUE THREAD

**Issue by cspramit** [casper-network/casper-node#2833]
An optimization for the system is to not block on constructing the trie while executing a block.

If we decouple these things, then we can continue running consensus while we do operations on the trie and build blocks.

This also enables data migrations to be faster and potentially in the background.

**Comment by cspramit** [comment]
Needed post 1.5.1 , pre 2.0.0 @dwerner 

@piotr-dziubecki @Fraser999 we would need to triage the release for this one

**Comment by xcthulhu** [comment]
@Fraser999 @EdHastingsCasperLabs As discussed this should piggyback the rocksdb migration

**Comment by goral09** [comment]
I don't think this needs its own release. This is just an internal representation of a slice of Global State. This can be released as patch version and node operators can upgrade their own convenience. It doesn't require network-wide synchronized restart. It doesn't change anything in any observable way:

- No new RPC endpoints are added/changed/removed
- No new contract FFI endpoints are added/changed/removed
- Validity of blocks/deploys is not changed

The "tip" can be populated lazily, as the new keys are read & changed. This way it won't require a special migration.
