### ISSUE TITLE
Get rid of interstitial commits in `step`

### ISSUE THREAD

**Issue by xcthulhu** [casper-network/casper-node#2835]
Currently, when we create a switch block the execution engine makes unnecessary writes to global state.

It should only write to _scratch_ global state and in the end commit that.

**Comment by dwerner** [comment]
feat-rocksdb: https://github.com/casper-network/casper-node/pull/2869
release-1.4.5-rocksdb: https://github.com/casper-network/casper-node/pull/2862

**Comment by dwerner** [comment]
PR targetting dev: https://github.com/casper-network/casper-node/pull/2877

**Comment by dwerner** [comment]
PR targetting dev: https://github.com/casper-network/casper-node/pull/2877
