### ISSUE TITLE
Speed up fast sync: store trie children before parents.

### ISSUE THREAD

**Issue by cspramit** [casper-network/casper-node#2860]
Since find_missing_descendants is slow and does a lot of redundant work, let's instead introduce the invariant that a trie node can never be stored without its children.
If fast sync were sequential, a depth-first traversal of the trie would thus require O(log(N)) nodes in memory at any time.
We need to find a way to parallelize that a bit, so that with t worker tasks, it requires O(t · log(N)) nodes in memory without doing any redundant downloads

**Comment by marc-casperlabs** [comment]
This will be rewritten with the excellent new suggestions from @afck !
