### ISSUE TITLE
Add simple scoring system for fast sync peers.

### ISSUE THREAD

**Issue by cspramit** [casper-network/casper-node#2866]

**Comment by marc-casperlabs** [comment]
https://github.com/rafal-ch/casper-node/pull/4

**Comment by marc-casperlabs** [comment]
Upping the estimate to 5, I was a little naive initially and there will be cleanup work.

**Comment by marc-casperlabs** [comment]
This has been merged in the relevant branch.

**Comment by cspramit** [comment]
whats the PR @marc-casperlabs

**Comment by marc-casperlabs** [comment]
> whats the PR @marc-casperlabs

https://github.com/rafal-ch/casper-node/pull/4
