### ISSUE TITLE
Add limited, shared memory pool for outgoing messages

### ISSUE THREAD

**Issue by devendran-m** [casper-network/casper-node#2916]
We need to restrict the maximal memory usage from buffered network messages. A shared memory pool should be added to curb maximum total consumption, potentially freeing still unsent messages under pressure.

Reported by @marc-casperlabs

**Comment by marc-casperlabs** [comment]
This is currently pending reevaluation, depending on how #2932 pans out.

**Comment by marc-casperlabs** [comment]
This is no longer relevant, as backpressure should take of the underlying issue.
