### ISSUE TITLE
could not open pidfile: Not a directory (os error 20)

### ISSUE THREAD

**Issue by YuXiaoCoder** [casper-network/casper-node#2920]
Can anyone help me, thanks？
Platform：Kubernetes 1.22
OS：Ubuntu 20.4
Casper-node：1.4.5
Config：1.4.5，https://github.com/casper-network/casper-protocol-release

/opt/csprmain/core/casper-node validator /mnt/csprmain/conf/config.toml
{"timestamp":"Apr 29 12:13:12.754","level":"INFO","fields":{"message":"node starting up","version":"1.4.5-725c25d9e-casper-mainnet"},"target":"casper_node::cli"}
Error: could not open pidfile: Not a directory (os error 20)

Caused by:
    Not a directory (os error 20)

**Comment by piotr-dziubecki** [comment]
It has been fixed, we don't use pidfiles anymore.
