### ISSUE TITLE
How to send value as Vec<u8> in casper contract test

### ISSUE THREAD

**Issue by gyroflaw** [casper-network/casper-node#2933]
I am currently writing a simple casper smart contract.
In the contract entry point the I need to the Vec<u8> parameter as blew

```
#[no_mangle]
pub extern "C" fn set_merkle_root() {
    owner::only_owner();
    let new_merkle_root: Vec<u8> = runtime::get_named_arg(MERKLE_ROOT_RUNTIME_ARG_NAME);
    let merkle_tree_root_uref = merkle_tree::merkle_tree_root_uref();
    merkle_tree::write_merkle_tree_root_to(merkle_tree_root_uref, new_merkle_root);
}
```
and I make execute request as blew

```
let root = vec![
            51u8, 65, 24, 137, 120, 125, 178, 119, 245, 2, 191, 121, 226, 141, 48, 59, 84, 228, 67,
            79, 242, 81, 50, 156, 181, 142, 76, 61, 20, 216, 175, 193,
        ];

        ExecuteRequestBuilder::contract_call_by_hash(
            *DEFAULT_ACCOUNT_ADDR,
            context.ido_contract,
            SET_MERKLE_ROOT_ENTRY_NAME,
            runtime_args! {
                MERKLE_ROOT_RUNTIME_ARG_NAME => root,
            },
        )
        .build()
```
the test case failed
![image](https://user-images.githubusercontent.com/83718263/166209790-185f8c0b-eb62-47a8-9abb-408e18cefc04.png)

**Comment by piotr-dziubecki** [comment]
@deuszex could you check?

**Comment by deuszex** [comment]
Not an actual bug. 
[It is an attempted enforcement of type for serialization reasons.](https://github.com/casper-network/casper-node/blob/master/types/src/bytesrepr.rs#L334)
It has been like that for years.
Also this ticket is 2 months old,  we should try to catch user engagement quicker.
