### ISSUE TITLE
[Bug] Inconsistent key management fee 

### ISSUE THREAD

**Issue by KillianH** [casper-network/casper-node#2942]
Hello,

I come across an inconsistency in the fee calculation with key management operations.

Here's the two deploys. They have the same execution tree. Only the write deploy fee change.

https://testnet.cspr.live/deploy/e12016c5a87e4e7b63741aa1c15cf4fab9f01f1efb977009bbe65cc73f6f1d45
https://testnet.cspr.live/deploy/ed099aa2df93d2b9a92b2f6641571dd61775abd83a5f31ee6e4c2789b402bf6e

The difference between the two account is that one account have an nft collection deployed on it.
https://github.com/casper-ecosystem/casper-nft-cep47

This inconsistency make impossible to predict the fee needed for key management operations (and maybe others operations).

**Comment by piotr-dziubecki** [comment]
The costs of the key management are affected by how much data is manipulated. Working as intended.
