### ISSUE TITLE
Update small_network component to use bytesrepr exclusively

### ISSUE THREAD

**Issue by devendran-m** [casper-network/casper-node#2944]
Replace `BincodeFormat` with a new `BytesreprFormat` and use this to encode/decode messages.  
This work should allow all remaining usages of bincode in the node to be replaced with bytesrepr.  Confer with [@Marc](https://casperassociation.slack.com/team/U011YT7U30Q) if any of the details of small_network need explanation.

**Comment by marc-casperlabs** [comment]
This has grown in scope, since consensus messages are no longer opaque. We will need to decide whether or not we will use a macro to generate `ToBytes`/`FromBytes` impls for various new types.

**Comment by marc-casperlabs** [comment]
@RitaMAllenCA I'd like to pull this into 1.6, especially since the follow-up is also 1.6 :)

**Comment by marc-casperlabs** [comment]
As discussed, this will be tackled in two seperate approaches, more to come.
