### ISSUE TITLE
Remove HostFunctionFlag from the code

### ISSUE THREAD

**Issue by devendran-m** [casper-network/casper-node#2946]
This was developed to patch improper cascading costs of system contracts called from within host functions. 
At that time we didn’t have access to call stacks, and we didn’t have changes to execution flow introduced in the 1.4.5 release. Currently, we can achieve the same effect with less code relying on a call stack only.

**Comment by RitaMAllenCA** [comment]
@mpapierski please review this OLD ticket and either update the description to be current or close it as necessary.

**Comment by devendran-m** [comment]
Won't do.
