### ISSUE TITLE
Non-deterministic cargo test failure in CI

### ISSUE THREAD

**Issue by devendran-m** [casper-network/casper-node#2947]
Test failed during a merge to release-1.5.0. Link to [Drone Run](https://drone-auto-casper-network.casperlabs.io/casper-network/casper-node/5061/1/3)

**Comment by georgepisaltu** [comment]
Fixed in https://github.com/casper-network/casper-node/pull/3084

**Comment by georgepisaltu** [comment]
The PR which should have closed this was closed itself. Reopening
