### ISSUE TITLE
Implement migration of storage data to new encoding

### ISSUE THREAD

**Issue by piotr-dziubecki** [casper-network/casper-node#2961]
We need to implement the migration strategy for storage as discussed in last week's meeting.

The main points are that:
* the node will start with old and new instances of storage DBs - old being bincode-encoded data, essentially read-only, and new being bytesrepr-encoded read-write
* a background process will be started which iterates every entry in the old DBs, parses it, and writes it in the corresponding new DB.  The process needs to be resumable, so if the node stops and restarts, the process continues from where it left off
* the node should be able to report the state of the migration via metrics.  For each old DB:
    * an `IntCounter` for total items migrated from that DB so far
    * a `Counter` for total time spent migrating so far
* the storage component, when being asked to provide data, will first try in the new DB and if it doesn't exist there, fall back to try the old DB.  All new data will be written to the new DB.

**Comment by devendran-m** [comment]
Won't do.
