### ISSUE TITLE
Avoid fatal errors in storage

### ISSUE THREAD

**Issue by piotr-dziubecki** [casper-network/casper-node#2974]
Errors in storage should be returned to the caller rather than triggering fatal errors so they can be decided on a case-by-case basis whether they are actually cause for a node shutdown

**Comment by devendran-m** [comment]
To do: Identify if there are any fatal errors outstanding.

**Comment by devendran-m** [comment]
Discovery and Analysis ticket.

**Comment by devendran-m** [comment]
To do: Mob session. ETA - w/c 5th Nov.

**Comment by devendran-m** [comment]
Mob session planned for 7th Nov.
