### ISSUE TITLE
Expose Round Number to Contract Runtime

### ISSUE THREAD

**Issue by devendran-m** [casper-network/casper-node#2983]
Certain smart contracts will want time locks based on round height rather than the wall clock. We need to expose the round height to the smart contract runtime.

~We should add the previous switch block's round for an "absolute" round number, pretending that no rounds were skipped after the switch block.~

**Comment by afck** [comment]
Reassigning to @fizyk20 for now.

I think this only makes sense for Zug, not for Highway, since in Highway the round number is subjective.
Not sure whether it's needed at all. We should discuss whether smart contracts need to know the round number.

**Comment by fizyk20** [comment]
Wouldn't block height be better and more universal? It is well defined at the stage at which deploys are executed, too.

**Comment by afck** [comment]
Yes, I believe this issue came up when we were considering basing block rewards on this somehow. Maybe it's just not needed anymore?

**Comment by EdHastingsCasperAssociation** [comment]
This user story is a thing we intend to do, but its in the wrong epic. This would better fall into the epic for contract runtime enhancements because this enables functionality for smart contract to leverage.

**Comment by AlexanderLimonov** [comment]
@RitaMAllenCA seems like this should be assigned to some EE-related epic per comment above

**Comment by devendran-m** [comment]
Superseded by issue #4853, therefore closing.
