### ISSUE TITLE
global-state-update-gen to support creation of accounts with token balances

### ISSUE THREAD

**Issue by thamps-casp** [casper-network/casper-node#2991]
When a network is bootstrapped with an alternate network global state, the global-state-update-gen tool is used to update the new validator set.

This validator set will be set with a stake amount, but account will have no balances. Because of this, we are unable to run new deploys on this network and with that our release-testing tasks cannot be run.

Request for the capability to add accounts such that we can create a faucet account, and set all accounts in the network with a token balance.

**Comment by cspramit** [comment]
we may need to prioritize this as Aj might be blocked in executing some regression testing using the Mainnet db
