### ISSUE TITLE
Don't Do a DB Scan When Starting RocksDB Migration

### ISSUE THREAD

**Issue by devendran-m** [casper-network/casper-node#2994]
Description: Currently the rocksdb migration requires a ~2min database scan to get all of the state roots so it can migrate.  This happens in the participating reactor initialization and may interfere with joining.

Acceptance Criterion: Don't stop the node to do a database scan.

Subject Matter Expert: @dwerner @xcthulhu 
Release: 1.6.0

**Comment by xcthulhu** [comment]
@Fraser999 with the rearchitecture of the `Storage` component we think it might be best if you tackle this.

**Comment by dwerner** [comment]
closing as wontfix as we don't want to take on the risk of doing the rocksdb migration at this point.
