### ISSUE TITLE
Allow `transfer_from_purse_to_account`  and `transfer_to_account` to be called in a custom payment code

### ISSUE THREAD

**Issue by devendran-m** [casper-network/casper-node#3013]
Make changes to allow `transfer_from_purse_to_account`  and `transfer_to_account` to be called in a custom payment code

This change will allow `transfer to account` inside payment code which currently isn't possible because gas limit for payment code is set to 2.5 CSPR and host functions `transfer_from_purse_to_account`  and `transfer_to_account` costs 2.5 CSPR. 

Possible solution;
a. Fix the pricing for those host functions in the chainspec
OR
b. Bump MAX_PAYMENT and minimum transfer amount.

**Comment by piotr-dziubecki** [comment]
we will accommodate this request for a feature but it will require non-trivial breaking change.

**Comment by RitaMAllenCA** [comment]
N/A for current design.   closing this as "won't address".   Payment code will be reworked to allow contracts to pay for themselves, and this functionality will be addressed during that implementation.
