### ISSUE TITLE
RocksDb tip migration as a sidecar process

### ISSUE THREAD

**Issue by cspramit** [casper-network/casper-node#3018]
We need to test the rocksdb tip migration to as a sidecar process with a node running. The tool running the migration will also need to query the node for the highest block after this is complete, and update with any new roots. After this, a node operator could run their node and have most of the state needed to begin execution, while historical data would be migrated in the background

**Comment by cspramit** [comment]
SME: @dwerner @xcthulhu

**Comment by dwerner** [comment]
Closing as wont-do - we don't want to move towards rocksdb at this point.
