### ISSUE TITLE
Integrate muxink code into existing network component

### ISSUE THREAD

**Issue by cspramit** [casper-network/casper-node#3026]
With a working multiplexing implementation, we can now replace the TCP-based backpressure implementation with one leveraging our new channels instead to solve the head-of-line blocking issue that prevented the previous implementation from being generalized to more than trie nodes.

**Comment by marc-casperlabs** [comment]
First prototype in 48b83f2bfdacd4c5e31704839e5d5e892229d0ae in `feat-muxink-integration`.
