### ISSUE TITLE
Remove workarounds preventing cross-joiner trie downloads

### ISSUE THREAD

**Issue by cspramit** [casper-network/casper-node#3027]
With cross-joiner trie requests no longer being an issue, we can remove the special casing of joiner nodes in the networking/fast sync code that for deadlock avoidance prevents trie requests being made to them.

**Comment by marc-casperlabs** [comment]
This has been removed in 050ea7964 -- note that the final commit hash will change as the `feat-muxink-integration` branch is rebased.
