### ISSUE TITLE
Add a boolean tag to a EraReport to indicate if a block is an emergency switch block

### ISSUE THREAD

**Issue by devendran-m** [casper-network/casper-node#3038]
When syncing to genesis we need to indicate if a block is an emergency switch block.  We can’t verify the finality signatures on an emergency switch block. If a block indicates this in the header then the sync-to-genesis process will know not to try to download and verify finality signatures.

This system will simplify the current scheme, which is to rely on the chainspec.

Subject Matter Expert: @fizyk20 @afck @xcthulhu

**Comment by piotr-dziubecki** [comment]
@fizyk20 if you remove support for old trusted hashes, please close this as 'won't do'

**Comment by afck** [comment]
~@piotr-dziubecki: This ticket is also about sync-to-genesis; it's needed even if we remove support for old trusted hashes.~

**Comment by fizyk20** [comment]
Do we still need this with #3135 being completed?

**Comment by afck** [comment]
Ah, you're right, sorry! Then it can be closed.

**Comment by fizyk20** [comment]
I'll go ahead and close it, then :+1:
