### ISSUE TITLE
Get rid of keys_with_prefix and use a iterator for (Key,Value) pairs instead (using Working Set) in the Auction

### ISSUE THREAD

**Issue by cspramit** [casper-network/casper-node#3046]
The auction currently uses keys_with_prefix to get all of the bids keys and then all of their values.  This is inefficient; iterators through global state already get the values as they get the keys.  This means the code walks everything twice.  The keys_with_prefix method should be replaced with a method that returns impl Iterator<Item=Result<(Key,Value), Error>>, and the auction code should be cleaned up.  Note that RocksDb provides a prefix iterator that will be leveraged by WorkingSet that is suited to this, and the existing iterator using the trie will be sun-setted (or perhaps just used in test).

**Comment by cspramit** [comment]
SME: @EdHastingsCasperLabs @xcthulhu @mpapierski @dwerner

**Comment by dwerner** [comment]
Closing as wont-do.
