### ISSUE TITLE
Make Emergency Upgrade Work With WorkingSet

### ISSUE THREAD

**Issue by cspramit** [casper-network/casper-node#3047]
WorkingSet will need to be rolled back to an old state root during an emergency upgrade.  Then we will put_stored_values with the diff from the emergency upgrade to WorkingSet (which will asynchronously update the trie).

**Comment by cspramit** [comment]
SME: @EdHastingsCasperLabs @dwerner @xcthulhu

**Comment by dwerner** [comment]
wont-do
