### ISSUE TITLE
Get Rid of Tracking Copy Cache

### ISSUE THREAD

**Issue by cspramit** [casper-network/casper-node#3048]
The tracking copy cache is obviated by scratch global state.  It needs to be removed to enable future optimizations.

**Comment by cspramit** [comment]
SME: @EdHastingsCasperLabs @goral09 @xcthulhu

**Comment by dwerner** [comment]
The tracking copy must retain it's caching capacity in order for it's "forking" functionality to work. That is to say, based on my investigation (ripping out the caching machinery in TrackingCopy) the functionality of is fundamentally altered by removing the cache.

The tracking copy is intended to be a source of execution transforms for a given execution, and cannot simply write to the underlying store unconditionally without producing invalid data.

In all, I believe this is functioning as intended, and should not be removed. The intuition that this is merely tech-debt is not correct.
