### ISSUE TITLE
Rewards as Interest Multipliers

### ISSUE THREAD

**Issue by piotr-dziubecki** [casper-network/casper-node#3060]
6.1.23. This is an old ticket and may be stale.  Review the current proposed implementation of Zug-compatible rewards before doing any work with this.  

storage optimization.

**Comment by AlexanderLimonov** [comment]
@RitaMAllenCA, I somehow missed this being migrated into the Epic. This is auction reward accrual accounting changes, right? That's, strictly speaking, independent of Zug-compatible rewards (would apply to any scheme we come up with)

**Comment by devendran-m** [comment]
Implemented a different reward mechanism.

**Comment by AlexanderLimonov** [comment]
@devendran-m should be noted that this is orthogonal to the reward mechanism, this ticket is about making system auction internal accounting more efficient, but this can be re-opened if it becomes an issue once again (I believe we made a few optimizations over time that made this less relevant)
