### ISSUE TITLE
Include participation factor (value from 0 to 1),  interest and motes rewarded in the block

### ISSUE THREAD

**Issue by cspramit** [casper-network/casper-node#3088]
In 2.0 we want to directly include the participation factor (value from 0 to 1),  interest and motes rewarded in the block.

**Comment by RitaMAllenCA** [comment]
@AlexanderLimonov @fizyk20 I don't see this in the design doc - do we still want to do this?

**Comment by AlexanderLimonov** [comment]
@RitaMAllenCA mentioned in relevant existing ticket and closing as obsolete
