### ISSUE TITLE
Add `archive create` subcommand in `casper-db-util`

### ISSUE THREAD

**Issue by devendran-m** [casper-network/casper-node#3123]
`casper-db-util` should have an `archive create` subcommand to create zstd compressed archives of database files. It should also have an option to output a checksum to later verify download integrity. Desired functionality looks like this:

```sh
casper-db-util archive create
-o path  (otherwise stdout)
--checksum full path to filename
--db [path to db folder]
```

**Comment by georgepisaltu** [comment]
Closed in https://github.com/casper-network/casper-db-utils/pull/17
