### ISSUE TITLE
Add `latest-block` subcommand in `casper-db-util`

### ISSUE THREAD

**Issue by devendran-m** [casper-network/casper-node#3124]
`casper-db-util` should have an `latest-block` subcommand to view (or save to file along with checksum) metadata about the highest block given the path to the database files. Desired functionality looks like this:
```sh
casper-db-util latest-block
-o path (otherwise stdout)
--checksum to save
--db
```

**Comment by georgepisaltu** [comment]
After reconsidering the use case of the command, we decided not to include a `--checksum` option as this file is small and will be used for verification purposes only.

Additionally, the desired JSON output looks like:
```
{
body_hash: "fafa31405d333f9ec3e1d2df44c326422789aef793c3bfb019cd4015045ba7b3",
era_id: 5101,
height: 824825,
protocol_version: "1.4.6",
state_root_hash: "b7ce8147ac9a75625924956ef6ae2d876f665d29084eb9ac544eea36696a5fd4",
timestamp: "2022-05-31T17:26:55.232Z",
}
```
