### ISSUE TITLE
LinearChain component should not reject signatures for unbonded eras

### ISSUE THREAD

**Issue by cspramit** [casper-network/casper-node#3133]
Currently, the LinearChain component will reject a finality signature ([link](https://github.com/casper-network/casper-node/blob/dev/node/src/components/linear_chain/state.rs#L141-L152)) that was created for an already-unbonded era. It shouldn't be necessary - a node should accept a valid finality signature for an era even if it's already unbonded.

**Comment by goral09** [comment]
Probably won't do. We decided to piggyback the existing endpoint that accepts `BlockSignatures` instead.
