### ISSUE TITLE
Empty `params` sent in the  `chain_get_state_root_hash`  request gets are replaced with empty list 

### ISSUE THREAD

**Issue by devendran-m** [casper-network/casper-node#3174]
Issue - When sanity checking the newly created Release 1.5.0 RPC endpoints and their responses, the following issue was encountered;
- Empty `params` sent in the  `chain_get_state_root_hash`  request are replaced with an empty list causing the RPC server to interpret [] as the wrong parameter.

The library replaces the missing params argument with [] empty list

Bug identified when doing the [sanity check](https://github.com/casper-ecosystem/casper-js-sdk/issues/161)

**Comment by Fraser999** [comment]
Resolved in https://github.com/casper-network/casper-node/pull/3155.
