### ISSUE TITLE
Document node to node messages and messaging patterns

### ISSUE THREAD

**Issue by cspramit** [casper-network/casper-node#3185]
Document every message nodes send to each other, under what circumstances, and the expected responses (where relevant)

**Comment by cspramit** [comment]
Should be completed before the end of next sprint (26th July) earlier the better. @marc-casperlabs please add points as well

**Comment by marc-casperlabs** [comment]
Initial version is here: 
[Network protocol 1.5 spec.md](https://github.com/casper-network/casper-node/files/9229331/Network.protocol.1.5.spec.md)
