### ISSUE TITLE
Merge `feat-muxink` into `dev`

### ISSUE THREAD

**Issue by devendran-m** [casper-network/casper-node#3199]
Brings the new networking code live by merging the `feat-muxink` branch into `dev`. This ticket is mostly about fixing the changes that are going to be requested by various reviewers by this rather large change.

**Comment by marc-casperlabs** [comment]
Addressed most of the concerns so far. Since there is upcoming changes to `dev` for 1.5 prevent this (1.6) being merged, this has been instead addressed by making a feature branch `feat-muxink-integration`.
