### ISSUE TITLE
Unify (generalize) tests for `bincode` and `bytesrepr` codec

### ISSUE THREAD

**Issue by devendran-m** [casper-network/casper-node#3224]
Currently, we have two codecs (`bincode` and `bytesrepr`) with two separate sets of very similar tests. Since 1) all codecs should behave alike and 2) we might have more codecs in the future, we should try to generalize the testing code to make sure that we run the same tests on all codecs. This can be done via macro or traits or other means necessary. Some initial draft is [here](https://github.com/casper-network/casper-node/pull/3220#discussion_r932502778).

**Comment by marc-casperlabs** [comment]
This is no longer applicable, as we have removed this functionality from `muxink` entirely.
