### ISSUE TITLE
Investigate discrepancies between Zondax's outputs for generic txn support and the casper-deploy-generator tool.

### ISSUE THREAD

**Issue by cspramit** [casper-network/casper-node#3227]
Message from Natanael from Zondax: https://casperlabs-team.slack.com/archives/C01QFUKS946/p1659044819501679

**Comment by KillianH** [comment]
We need the generic txn support  for ledger to implement all the features of CasperHolders on mobile with ledger.

**Comment by goral09** [comment]
> We need the generic txn support for ledger to implement all the features of CasperHolders on mobile with ledger.

Yes @KillianH , I agree with that. We're very close to that. The Ledger code is basically ready and we're still waiting for the Ledger to review it and upgrade the app in their store. That process is very long and can take weeks to months.

**Comment by KillianH** [comment]
> > We need the generic txn support for ledger to implement all the features of CasperHolders on mobile with ledger.
> 
> Yes @KillianH , I agree with that. We're very close to that. The Ledger code is basically ready and we're still waiting for the Ledger to review it and upgrade the app in their store. That process is very long and can take weeks to months.

Awesome 😎
