### ISSUE TITLE
Detect validator-edit/emergency upgrades based on auction contract entries in the global state in sync-to-genesis.

### ISSUE THREAD

**Issue by cspramit** [casper-network/casper-node#3233]
When syncing back to genesis we need to detect immediate switch blocks after upgrades in which the validator set was changed by directly modifying the global state: Those get signed by the validators specified in their own header, rather than the previous switch block's header. So:
If we encounter a switch block in an era N whose protocol version is higher than its parent's, after synchronizing both blocks' global states, we load the validator maps from both states. They both contain the validator set for era N + 1, so we can compare that entry. If it has changed in block N, that must be because the validators were changed in that upgrade.
(Possibly slightly easier: We could avoid looking into block N's global state, because its header already contains the validator map for era N + 1. So we'd only need to look into its parent's.)

**Comment by afck** [comment]
WIP: https://github.com/afck/casper-node/tree/validator_change_upgrades
