### ISSUE TITLE
Retroactively add deploy approvals and execution results Merkle tree roots for blocks before 1.5.0

### ISSUE THREAD

**Issue by devendran-m** [casper-network/casper-node#3245]
Details to be confirmed, but this could possibly take the form of creating a global state file to be applied at the next upgrade

**Comment by RitaMAllenCA** [comment]
@Boiethios double check for relevancy before starting this work.

**Comment by real-felix** [comment]
Fraser told me that this ticket was created when the plan was to store Merkle root hashes for deploy approvals and execution results in global state under a key specific to the individual block (e.g. "da-1", "er-1", "da-2", "er-2" for blocks at height 1 and 2). We didn't implement that in the end, instead opting for a single static key under which the current block's checksums for deploy approvals and execution results are stored in a BTreeMap with 2 entries. Given this new approach, there is no possibility to backfill historical blocks as that would require modifying historical global state.
