### ISSUE TITLE
Change verification of deploy approvals and execution results to require Merkle root

### ISSUE THREAD

**Issue by devendran-m** [casper-network/casper-node#3246]
Once the historical Merkle roots have been added to global state, do not make it optional to verify synced approvals and execution results

TODO[RC]: Needs more detailed description.

**Comment by real-felix** [comment]
Fraser told me that this ticket was created when the plan was to store Merkle root hashes for deploy approvals and execution results in global state under a key specific to the individual block (e.g. "da-1", "er-1", "da-2", "er-2" for blocks at height 1 and 2). We didn't implement that in the end, instead opting for a single static key under which the current block's checksums for deploy approvals and execution results are stored in a BTreeMap with 2 entries. Given this new approach, there is no possibility to backfill historical blocks as that would require modifying historical global state.
