### ISSUE TITLE
 Failed to sync after missed upgrade

### ISSUE THREAD

**Issue by cspramit** [casper-network/casper-node#3260]
Logs from node 1 of failed upgrade-scenario-4 https://drone-auto-casper-network.casperlabs.io/casper-network/casper-node/6105/1/4 show that the node ran, but failed to participate after finishing joining.

**Comment by rafal-ch** [comment]
@fizyk20 
https://github.com/casper-network/casper-node/issues/3261 should also be closed via this PR.

**Comment by rafal-ch** [comment]
Moving back to "in progress", becase, as discussed, we should not derive the retry count from the `known_addresses` list length, but introduce separate config value.
