### ISSUE TITLE
Failed to fetch block signatures during sync-to-genesis

### ISSUE THREAD

**Issue by cspramit** [casper-network/casper-node#3266]
Logs from node 1 of failed upgrade_scenario_05 https://drone-auto-casper-network.casperlabs.io/casper-network/casper-node/6109/1/4 appear to show that the node failed to retrieve the block signatures for a particular block.

**Comment by Fraser999** [comment]
This will be fixed by trying more than once to fetch the signatures for a given block.  That work will be best left until https://github.com/casper-network/casper-node/issues/3273 is completed.
