### ISSUE TITLE
Provide functionality to allow the node to stop periodically

### ISSUE THREAD

**Issue by cspramit** [casper-network/casper-node#3269]
The node should be able to stop gracefully at the end of every multiple of a configurable number of eras after the current activation point.

- add a new config setting to the node section: recurring_shutdown_interval which is a u8 representing a number of eras.  Every time the node completes a multiple of this value past the activation point, the node should shut down.  For example, if the activation point is 1234 and recurring_shutdown_interval = 100 the node should shutdown at the end of eras 1334, 1434, 1534, ... .  If the config value is 0, no recurring shutdowns should be triggered.  The default value should be 0.

- there should be a new exit code for this specific case: RecurringShutdown = 103

- the linear chain component will be responsible for holding the new config value, and causing the shutdown to happen at the appropriate time.  The implementation should be very similar to how should_upgrade is handled in that component

- if a recurring shutdown point and upgrade activation point coincide, priority is given to the recurring shutdown and the new exit code should be emitted

- the GetStatusResult struct should have a new field pub next_shutdown: Option<EraId> which will be populated via a request to the linear chain component

- the node will not perform a recurring shutdown while in Initializer or Joiner mode - if it was shutdown for so long that it missed a scheduled shutdown point, then it won't shutdown while re-joining - that point will have been skipped.  Likewise, the status endpoints won't show a non-null next_shutdown value until the node is participating

**Comment by RitaMAllenCA** [comment]
won't do - Joe and Marc worked out an alternate solution.
