### ISSUE TITLE
Add `bootstrap_completed` to small_network

### ISSUE THREAD

**Issue by cspramit** [casper-network/casper-node#3274]
The bool value should be available to other components via a request to the small_network component.  It will be a simple heuristic which is false while the small_network is still acquiring new connections just after being constructed, and will permanently turn true once 2 * gossip_interval has elapsed or the node has symmetric connections to all known addresses

**Comment by marc-casperlabs** [comment]
This is no longer applicable with the additional 1.5 design changes coming in.
