### ISSUE TITLE
Fix JSON-RPC examples

### ISSUE THREAD

**Issue by piotr-dziubecki** [casper-network/casper-node#3296]
@piotr-dziubecki commented on [Mon Aug 29 2022](https://github.com/casper-network/Governance/issues/385)

The examples included in the rpc.discover RPC have params which are incorrectly wrapped in a ExampleParam struct.  This struct should be removed, and the raw params (for Some) or an empty array (for None) used instead.

**Comment by Fraser999** [comment]
The `rpc.discover` endpoint is working as per [the OpenRPC spec](https://spec.open-rpc.org/#example-pairing-object).
