### ISSUE TITLE
 Add tests for networking protocol fragmentizer

### ISSUE THREAD

**Issue by piotr-dziubecki** [casper-network/casper-node#3304]
The fragmentizer module needs to have outdated tests removed (and fragment_frame as well), replaced by proper tests of the Fragmentizer and Defragmentizer structs.

**Comment by georgepisaltu** [comment]
Tests are in the `feat-muxink` branch as of https://github.com/casper-network/casper-node/commit/18c0b0b2789f52576e6e5ee415befba2de8ee2a2.
