### ISSUE TITLE
Migrate and implement low-level networking tests from node to `muxink`

### ISSUE THREAD

**Issue by devendran-m** [casper-network/casper-node#3306]
There is a set of specified but not implemented tests in the `casper_node::components::small_network::handshake` module on the `feat-muxink-integration` branch. Where applicable, these should be migrated to `muxink` and implemented.

**Comment by georgepisaltu** [comment]
Tests are in `feat-muxink-integration` as of https://github.com/casper-network/casper-node/commit/42afd4889cabf7b656adb4e5e1b826de10095b1a
