### ISSUE TITLE
Optimize waker usage in `muxink` fragmentizer

### ISSUE THREAD

**Issue by devendran-m** [casper-network/casper-node#3309]
The `fragmented` module in `muxink` uses `Wakers` to ensure the progress of the generated futures when they are scheduled on different tasks. This is done by notifying all pending futures through calling their registered `wake` function. In reality, only one future out of all futures on a task needs to be woken up in order to progress and `Waker` has special functionality to detect this. Use this to optimize `wake` calls in the `fragmented` module.

**Comment by marc-casperlabs** [comment]
We decided against this optimization, as it turns out the pay off is too small to warrant the additional complexity.
