### ISSUE TITLE
 Add `SSLKEYLOGFILE`-style TLS logging support

### ISSUE THREAD

**Issue by devendran-m** [casper-network/casper-node#3316]
To ease debugging of potential networking issues, add support for logging TLS session keys of OpenSSL to the node, allowing captured traffic of `nctl` and similar to be dissected using tools like [wireshark](https://wireshark.org/).

If time permits, a simple dissector script would be helpful as well.

**Comment by piotr-dziubecki** [comment]
The issue moved out of the sprint and waiting for the green light from @Fraser999

**Comment by marc-casperlabs** [comment]
This done, just not merged to `dev`. It will find its way in with the muxink changes (which is where it is needed).

See https://github.com/casper-network/casper-node/pull/3317#issuecomment-1273338409
