### ISSUE TITLE
Add an endpoint with the costs of system transactions

### ISSUE THREAD

**Issue by RitaMAllenCA** [casper-network/casper-node#3322]
@RitaMAllenCA commented on [Mon Oct 24 2022](https://github.com/casper-network/Governance/issues/392)

**Comment by RitaMAllenCA** [comment]
There are a couple txn costs fixed -- wasmless transfer, delegate/undelegate. These costs are specified in the chainspec.toml and then define how much should the user pay for the specific txn. As part of the Ledger Live interagtion, these txn costs have to be either estimated (in the Ledger Live) or hardcoded. The costs are fixed so there's no need for estimation BUT, in theory, they could also change in the next version. Ledger Live needs to be aware of these changes.
We propose addition of the special endpoint where these costs would be available for the Ledger Live to query so that users of the desktop wallet can create txns with proper fees.

**Comment by EdHastingsCasperAssociation** [comment]
this doesn't make sense; i can explain why but not concisely
