### ISSUE TITLE
Handle ACK receival errors

### ISSUE THREAD

**Issue by RitaMAllenCA** [casper-network/casper-node#3324]
Due to an oversight, there is no clean handling of backpressure ACK receival errors (they are at best indistinguishable from closed connections). This should be correct to proper error handling, or rather logging.

**Comment by marc-casperlabs** [comment]
Sadly, this turned out to be a bigger issue requiring a refactoring/cleanup about 1k lines of tests :(.

**Comment by marc-casperlabs** [comment]
This is done, all work is merged into `feat-muxink`, which is being merged into `feat-1.6`.
