### ISSUE TITLE
Review `session_args_max_length` default length

### ISSUE THREAD

**Issue by devendran-m** [casper-network/casper-node#3328]
In the chainspec (casper-node/resources/local/chainspec.toml.in), under [deploys], there's a parameter called 'session_args_max_length'. The default is 1024. Since people using the new --session-args-json feature will run into this limit quite easily when using custom schema for cep-78, we should bump up the current parameter's value in the chainspec.toml. (The team should decide on an appropriate value).

**Comment by EdHastingsCasperAssociation** [comment]
Sorry, no.
