### ISSUE TITLE
Check when we call get_highest_block_header whether we mean complete block or not

### ISSUE THREAD

**Issue by piotr-dziubecki** [casper-network/casper-node#3347]

**Comment by georgepisaltu** [comment]
Ticket closed accidentally.

**Comment by georgepisaltu** [comment]
Analysis of `get_highest_block_header` and `get_highest_block` calls:

`storage::get_highest_block_header` called only through `effect::get_highest_block_header_from_storage`:
- [`deploy_acceptor::accept` when accepting a deploy](https://github.com/Fraser999/casper-node/blob/23e1a4c014ecacd5fc2e5625e70341c6b751295d/node/src/components/deploy_acceptor.rs#L216-L222) (probably most interesting call site for this issue, but seems fine as is)
- `rpc_server` for `QueryBalance` request

`storage::get_highest_block` called through:
- `effect::get_highest_block_from_storage`, which is called from:
   - `rest_server` for `Status` request
   - `rpc_server` for `GetStatus` request
- `storage::get_blocks_while` -> `storage::read_blocks_since` -> `main_reactor::control::initialize_next_component` when initializing the deploy buffer with the blocks more recent than the last known switch block

**Comment by georgepisaltu** [comment]
After checking in with @Fraser999 , the `get_highest_block_header` calls were not correct.

In both the `deploy_acceptor` and `query-balance` cases, we want to do the relevant checks with the latest available global state, which means getting the highest complete block header from storage. Getting the highest block header might not have the necessary global state and an early failure is not the desired behavior in either case.

**Comment by georgepisaltu** [comment]
Fixed in #3350
