### ISSUE TITLE
Add sync-to-ttl feature

### ISSUE THREAD

**Issue by piotr-dziubecki** [casper-network/casper-node#3371]
Currently there is a bool sync-to-genesis flag which if true causes a node to attempt to acquire all blocks from tip to genesis and if false causes a node to only add new blocks. Currently, a validator is allowed to have either option. However, the current version of fast sync won't allow a validator to participate in consensus unless they have a contiguous sequence of blocks equal to or greater than the deploy TTL. To allow validators who do not want to maintain all data, we will add a sync-to-ttl option which will back fill the necessary number of blocks to satisfy the TTL awareness requirement of consensus. The bool setting will be changed to a 3 variant enum: [sync-to-genesis | sync-to-ttl | no-sync]. Once the feature is implemented, a node may only become a validator if it is configured for either sync-to-genesis or sync-to-ttl (and meets all other requirements); no-sync nodes will not be allowed to transition to Validate mode.

**Comment by EdHastingsCasperAssociation** [comment]
https://github.com/casper-network/casper-node/pull/3428
