### ISSUE TITLE
Update status endpoint

### ISSUE THREAD

**Issue by piotr-dziubecki** [casper-network/casper-node#3374]
Update `GetStatusResult` as follows:
* move `pub peers: PeersMap,` to be the first field
* move `pub build_version: String,` to immediately follow `api_version`
* `starting_state_root_hash` should be changed to be set to the state root hash of the lowest block of the available block range (comment needs updated and remove deprecation)
* `node_state` should be replaced with `pub reactor_state: ReactorState,`
* add `pub last_progress: Timestamp,`
* add `pub blocks_sync: Vec<BlockSyncStatus>` (see below)
* add `pub available_block_range: AvailableBlockRange,`

```rust
struct BlockSyncStatus {
    block_hash: BlockHash,
    block_height: Option<u64>,
    acquisition_state: String, // BlockAcquisitionState.to_string()
}
```

**Comment by georgepisaltu** [comment]
Fixed in https://github.com/casper-network/casper-node/pull/3383
