### ISSUE TITLE
Add flow charts to new flows introduced in "new" fast sync implementation

### ISSUE THREAD

**Issue by piotr-dziubecki** [casper-network/casper-node#3377]
Description: Use the mermaid format and then the aquamarine crate to create proper docs
Points: 5

**Comment by rafal-ch** [comment]
* :heavy_check_mark: ReactorState
* Interaction between components (aka the original bubble chart)
* :heavy_check_mark: CatchUp flow (on the high level) - also for other reactor states
* :question: BlockSynchronizer (on the high level)
* HotBlock (lifecycle of a block)
* :heavy_check_mark: DeployAcceptor (could be useful for external consumers, smart contract devs?)

abandoned:

* :heavy_check_mark: ComponentState
* :heavy_check_mark: BlockAcquisitionState
* ReactorState
* CatchUp process (_sync leaps_)
* KeepUp process
* Validate process
* BlockAccumulator
* DeployAcquisition
* ExecutionResultsAcquisition
* GlobalStateSynchronizer
* DeployBuffer (_hold, dead, etc._)
* UpgradeWatcher
* :question: Consensus
