### ISSUE TITLE
All nodes should create immediate switch blocks

### ISSUE THREAD

**Issue by piotr-dziubecki** [casper-network/casper-node#3390]
Currently, only validating nodes produce immediate switch block at genesis and upgrade, but we have decided that all nodes should produce them when going forward.

Nodes that join after genesis should not produce immediate switch block for genesis and nodes that join after upgrades should not produce immediate switch blocks after upgrade. They will get the via historical sync, as it's already currently does.

**Comment by EdHastingsCasperAssociation** [comment]
im running a bit behind on this; should finish it tomorrow
