### ISSUE TITLE
Metric Issue: contract_runtime_run_execute_count

### ISSUE THREAD

**Issue by cspramit** [casper-network/casper-node#3432]
metric value mismatch seen between a 'validator' and 'non-validator' ex. deploy of 30000 correct on validator was showing 32500 on non-validator

**Comment by thamps-casp** [comment]
![image.png](https://images.zenhubusercontent.com/609dad3f043883f0a6f76785/de0aa28f-8942-444e-a192-78a0276b11c9)

This is regards to this contract_runtime_run_execute_count being different for the validators and non-validators at a point in time. attached is a snapshot of the metric across all the nodes after 30k, 60k and 90k deploys were sent to network.

As seen in the snapshots, validators are showing correct number of deploys executed while non-validators showing a higher number (even though they do not actually execute deploys? ). shouldn't the counts be same across all nodes?

grafana URL: https://grafana.casperlabs.io/goto/hggtjLKVk?orgId=1
prometheus metric:
``` contract_runtime_run_execute_count{server_group="$casper_environment", node_type=~"$casper_node_type", hostname=~"$casper_hostname"}```

**Comment by piotr-dziubecki** [comment]
@thamps-casp could you please check on this again?

**Comment by cspramit** [comment]
Logs to be provided by @thamps-casp and looked by @georgepisaltu but not be worked right now as there are other priorities

**Comment by thamps-casp** [comment]
Performed similar run in two parallel networks (rti-fsync2a and rti-fsync2b), and observed that one network showed correct `contract_runtime_run_execute_count` values across all validating and non-validating nodes while the other had a higher count for non-validating nodes.

Network: 10 validating + 2 non-validating (all nodes started at network genesis)
Commit: `ae4a12f1d9a2fb07d5c5601a2c048a3e4614cc9e`
Deploys: 33600 (transfers + wasm)

*rti-fsync2a ( debug log run )*
http://genesis.casperlabs.io/rti-fsync2a/casper-node-dumps/rti-fsync2a/06012023_1243/dump_download_list.txt
![image](https://user-images.githubusercontent.com/74213253/211018340-19172417-8bdd-44b1-8b9a-b87d7d693b2f.png)

*rti-fsync2b ( info log run ) *
http://genesis.casperlabs.io/rti-fsync2b/casper-node-dumps/rti-fsync2b/06012023_1250/dump_download_list.txt
![image](https://user-images.githubusercontent.com/74213253/211018271-2f93621b-b237-44a6-8063-b782c859d0ce.png)

**Comment by georgepisaltu** [comment]
After looking at the logs with @alsrdn , we found the problem to be a bug which would ultimately cause a block to be executed twice when in keep up mode at the tip of the chain.

The flow of the code when the bug manifests is as follows:
- the buggy node is a non-validator keeping up with the rest of the network and is at the tip (let's say block at height X)
- the node has blocks at height [0, X-1] in storage, marked complete
- the accumulator receives a new block, getting the necessary components like signatures etc.
- the synchronizer is asking the accumulator what its next sync instruction should be, telling it the synced identifier is the block at height X-1
- the accumulator tells it to sync block at height X
- the synchronizer gets the necessary pieces and finally enqueues the block for execution
- the synchronizer transitions to `BlockAcquisitionState::HaveStrictFinalitySignatures`, which means its `is_finished` function will return `true` and from its perspective, it has synced the block and is done with it
- before the block can complete its execution and, through `contract_runtime`, trigger a hot block announcement, the synchronizer is looking for its next keep up instruction
- the next `BlockSynchronizer::progress` call will yield `Synced` as the block builder is finished
- this means the `keep_up_process` will end up calling `keep_up_idle`, which purges the block builder
- next, in `keep_up_idle`, the block synchronizer is looking for the next block and is looking in storage for the highest complete block, which is still the block at height X-1
- this means the sync identifier will be block at height X-1
- it asks the accumulator what the next step should be, which is the same as the previous time it asked: sync block at height X
- at some point, the execution will finish and the block will be marked complete, thus breaking the loop we found ourselves in

**Comment by georgepisaltu** [comment]
Will come up with a PR later today to address this.
