### ISSUE TITLE
Metric Issue: pending_deploy

### ISSUE THREAD

**Issue by cspramit** [casper-network/casper-node#3433]
this metric is missing. is there an alternative metric to view number of incoming deploys to network?

**Comment by alsrdn** [comment]
For deploys we have now some metrics for the deploy buffer of each node (`deploy_buffer_total_deploys`, `deploy_buffer_held_deploys` and `deploy_buffer_dead_deploys`). So `pending_deploy` would mean `deploy_buffer_total_deploys` - `deploy_buffer_dead_deploys` and would give the number of deploys that are in flight and newly received.
