### ISSUE TITLE
Sync Metrics

### ISSUE THREAD

**Issue by cspramit** [casper-network/casper-node#3436]
- sequential hi/lo as gauges
- histogram

This metric maybe missing or named something else? -
is there a or group of Prometheus metrics to evalauate historical sync progress?

**Comment by alsrdn** [comment]
Added `forward_block_sync_duration_seconds` and `historical_block_sync_duration_seconds` histogram metric to track the progress of block synchronization, `lowest_available_block_height` and `highest_available_block_height` to report the highest and lowest height of the blocks that were synchronized and available on the node.
