### ISSUE TITLE
Copy inject_gas inject_limiter and optimize functions from pwasm-utils into our codebase

### ISSUE THREAD

**Issue by piotr-dziubecki** [casper-network/casper-node#3496]
Copy inject_gas inject_limiter and optimize functions from pwasm-utils into our codebase, and remove the crate
pwasm-utils is deprecated, unmaintained and archived and since we invested a lot of effort into making sure it’s usage is safe, we can copy it rather than migrate to suggested wasm-instrument. New suggested crate is not a drop in replacement and causes couple of integration tests to fail due to internal changes. There’s also externalize_mem function to be moved which is very small function that inserts a memory import. 

For overview of issues with wasm-instrument see 
https://github.com/casper-network/casper-node/issues/3228#issuecomment-1346838583

**Comment by RitaMAllenCA** [comment]
@Boiethios if you pull this in, start with @mpapierski

**Comment by RitaMAllenCA** [comment]
3.20.23 Fork repo and release our own version of the crate - change the name to something unrelated to the original and casper.  Give credit to the original developer in the readme, prominently.   

Will require a small SRE ticket to create the new repo.

**Comment by real-felix** [comment]
I started vendoring the crate in the node repo, first. Now that the plans have changed and that the crate has been forked, I'm back to port the changes to that new `wasm-utils` crate so that we can publish that changes.

**Comment by real-felix** [comment]
Related PR: https://github.com/casper-network/casper-wasm-utils/pull/1

**Comment by real-felix** [comment]
Related PR: https://github.com/casper-network/casper-wasm-utils/pull/2
