### ISSUE TITLE
Investigate "unused block capacity"

### ISSUE THREAD

**Issue by cspramit** [casper-network/casper-node#3502]
after upgrade blocks are not fully saturated (probably not a bug, but let's track it until we confirm)

**Comment by thamps-casp** [comment]
in-flight deploys = (deploy_buffer_total_deploys - deploy_buffer_dead_deploys)
block fill rate = counts the number of transfers and deploys recorded in each finalized block
deploys dispatched to 5 validators in random only

results with another test run today as suggested

1. 30k native transfers only
dispatch rate: 5000/s
transfers per block: 1250
result: fully saturated

![image](https://user-images.githubusercontent.com/74213253/208592743-c3c76687-8461-46b8-a7f3-f9ccc29c6d31.png)

**Comment by thamps-casp** [comment]
2. 2.6k wasm transfers only
dispatch rate: 300/s
deploys per block: 50
result: fully saturated

![image](https://user-images.githubusercontent.com/74213253/208592989-8bfdfcfa-38e2-445f-b136-d25dbe9b8ee6.png)

**Comment by thamps-casp** [comment]
3. mixed - 30k native transfers and 2.6k wasm deploys
dispatch rate transfers - 5000/s
dispatch rate wasm transfer deploys - 600/s
result: variance in saturation for available transfer and deploys in block. 

grafana: https://grafana.casperlabs.io/goto/1tAjwQc4k?orgId=1

note - the block file rate bar graphs show stacked values of both transfer and deploys in finalized block

![image](https://user-images.githubusercontent.com/74213253/208594162-e336eb35-0630-4dad-8df5-e65dbf4dc59c.png)
![Screenshot from 2022-12-20 17-05-33-1](https://user-images.githubusercontent.com/74213253/208596054-e02d91cf-3cbb-45ac-952e-74e3885d96cc.png)

**Comment by cspramit** [comment]
@thamps-casp what duration or # of blocks we awaited for time to inclusion, is it possible we could have awaited longer for the mixed scenario for full block fills?

**Comment by thamps-casp** [comment]
this above is full duration if deploy dispatch to nodes and its execution. Time to inclusion is a node behaviour i would expect. 

In the above results, they are 1 full batch of transfers and deploys (refer in-flight deploys metric).

**Comment by cspramit** [comment]
From what I understand these deploys would eventually fill subsequent blocks to be included - meaning extending the period of observation

**Comment by cspramit** [comment]
Also for the mixed case i did expect it to be Wasm 300/s - same as single case instead of 600/s

**Comment by thamps-casp** [comment]
the more the deploys dispatched, the more gets added to the buffer. The chainspec limits 50 wasm deploys per block, so number of deploy dispatched shouldn't make a difference. 

The mixed load results were to point out that something was limiting full block capacity saturation, when both transfers and wasm deploys are avaialble in the storage buffer.

**Comment by cspramit** [comment]
12/21/2022 - Aj to rerun exact same on 148 and 150

**Comment by thamps-casp** [comment]
As recommended - running 2 parallel networks for 1.4.8 (`b94c4f79ac4ca00e996c418dcc3a98607779a193`) and 1.5.0RC (`c6c1c8cd516c1728d87bc22a9259991f515c07b7`)

Network: 5 + 2 
Test Load - run mixed deploy count `33600` like-for-like in both networks (at Era 0 Block 15)
- 30k transfers
- 3.6k wasm deploys

**rti-fsync2a (1.4.8)**
![image](https://user-images.githubusercontent.com/74213253/209025623-92768703-3ef7-4a53-bc07-0b29b6f62b3f.png)
![image](https://user-images.githubusercontent.com/74213253/209025691-9190b83a-58c0-4d1d-9910-844baa35f85c.png)

**rti-fsync2b (1.5.0RC)**
![image](https://user-images.githubusercontent.com/74213253/209025755-e74fb93e-330b-4d9f-b02b-8a9e95da29ec.png)
![image](https://user-images.githubusercontent.com/74213253/209025779-a7962d60-ed8a-4c2e-b96c-7e27960a3839.png)
![image](https://user-images.githubusercontent.com/74213253/209025858-fc00fd1f-fe57-4661-bc29-424f93f6b2e1.png)

Dumps: http://genesis.casperlabs.io/rti-fsync2b/casper-node-dumps/rti-fsync2b/21122022_2357/dump_download_list.txt

deploy buffer limits in logs:
```
{"timestamp":"2022-12-21T23:43:57.454134Z","level":"INFO","fields":{"message":"DeployBuffer: a block limit has been reached","deploy_hash":"DeployHash(d5c159fb3e5ac57d6fd96ca591919afee131d905fcd13b516c53ba03f373fa90)","error":"would exceed maximum deploy count per block"},"target":"casper_node::components::deploy_buffer"}
{"timestamp":"2022-12-21T23:43:57.454776Z","level":"INFO","fields":{"message":"produced AppendableBlock(50 non-transfers with 50 approvals, 461 transfers with 461 approvals, total of 511 deploys with 511 approvals, total gas 500000000000, total size 371600), buffer has 511 held, 31417 dead, 33600 total"},"target":"casper_node::components::deploy_buffer"}
```
