### ISSUE TITLE
Fix empty_block_validation_regression test

### ISSUE THREAD

**Issue by piotr-dziubecki** [casper-network/casper-node#3513]
The changes in fast sync v2 have made this test no longer meaningful.  It needs to be updated to ensure that a BlockPayload with accusations containing _everyone_else is created by the malicious runner.

**Comment by piotr-dziubecki** [comment]
@Fraser999 to ping @afck about it

**Comment by piotr-dziubecki** [comment]
@afck : Well, it's a regression test. So it's fine to delete it as long as nobody reintroduces the bug. :smile:
In this case I actually think it's fine to remove it. In fact, I'd remove the optimization from the code that allows skipping validation for blocks that are both empty and contain accusations. If all blocks are always getting validated without exception there's no danger of bringing back this bug.
So maybe just remove ConsensusValueT::needs_validation, and assume it's always true.

**Comment by Fraser999** [comment]
As discussed in standup today, we'll instead implement a fix for the test and retain the original optimisation in the code.
