### ISSUE TITLE
Update MetaBlock state

### ISSUE THREAD

**Issue by piotr-dziubecki** [casper-network/casper-node#3611]
The meta block state should be changed to an enum with three variants representing the source of the block: consensus, forward-sync or historical-sync.  The states should only contain the subset of flags which make sense for that type of block, and  handle_meta_block can be split into three flows, one per state variant

**Comment by RitaMAllenCA** [comment]
@georgepisaltu If you pull this into the sprint, please start with Fraser

**Comment by RitaMAllenCA** [comment]
close as won't do
