### ISSUE TITLE
Upgrade 6/7 test failing

### ISSUE THREAD

**Issue by piotr-dziubecki** [casper-network/casper-node#3619]

**Comment by TomVasile** [comment]
latest dev

Dump: 
- 06: [06_dump.tar.gz](https://github.com/casper-network/casper-node/files/10538045/06_dump.tar.gz)
- 07: [07_dump.tar.gz](https://github.com/casper-network/casper-node/files/10538051/07_dump.tar.gz)


Repro CI:
```
1. edit ./ci/nightly-test.sh to make only the single test run
    1.a comment out `skip_setup=true` as well
2. bash -i ./ci/nctl_compile.sh
3. bash -i ./ci/nightly-test.sh
```

Notes: The two nodes left behind purposely ( node 1 and 10 ) don't seem to come up as 2.0.0 there. Logs are spewing initializing and minimum_peers. Not sure if thats the cause or a symptom. Only difference between the two tests is the amount of eras (1 and 10) that we wait until restarting node 1 and 10.
