### ISSUE TITLE
Fix Broken link in rpc doc

### ISSUE THREAD

**Issue by piotr-dziubecki** [casper-network/casper-node#3632]
A broken link has been reported in the #docs channel. The link is here: https://github.com/casper-network/ceps/blob/master/text/0009-client-api.md#rpcs.   Fixing the link must be done in L1 as it is autogenerated.

**Comment by RitaMAllenCA** [comment]
2/3/23 - we will discontinue doing this as it is not easily maintained.  Please submit a PR to remove this code generation.
