### ISSUE TITLE
Update branding and company name

### ISSUE THREAD

**Issue by piotr-dziubecki** [casper-network/casper-node#3660]
We should update any images in READMEs and in links (e.g. html_favicon_url and  html_logo_url).  We should also update the name "CasperLabs" to "Casper Labs" throughout the code (e.g. in doc comments, READMEs, Cargo.toml files)

**Comment by RitaMAllenCA** [comment]
closing as a duplicate of https://github.com/casper-network/casper-node/pull/4150
