### ISSUE TITLE
Implement reward data surfacing to the event stream

### ISSUE THREAD

**Issue by piotr-dziubecki** [casper-network/casper-node#3666]
Zug-compatible rewards are written to EraInfo structs (at least for block rewards)
each block, but not otherwise surfaced; we should make it easier for users to consume this data
(also see https://github.com/casper-network/casper-node/pull/3420#discussion_r1038191549)

**Comment by fizyk20** [comment]
@MParlikar There is a slight lack of clarity about what specifically we have to do regarding this ticket.

1.5 code only emits rewards data in `EraEnd`s in switch blocks, and it is not quite rewards there, but "reward factors", which are proportional to rewards.

With the new 2.0 rewards, we could put the actual rewards there, as we calculate them already in the node (to be specific, we would put the total reward per validator: this is still split later between the validator and their delegators). The question is: do we want that, or do we want them reported in some other way? Also, do we want anything else? (The linked comment by Andreas mentions storing `ExecutionResult`s related to rewards distribution, for example.)

**Comment by fizyk20** [comment]
Per the call, we will just emit the rewards per validator in `EraEnd`, analogously to how this was being done before, without splitting the rewards into the validator's and delegators' parts.

**Comment by real-felix** [comment]
After running a NCTL network and listening to the events, I can confirm that during a switch block production, the rewards information is correctly streamed as a part of the block information.
