### ISSUE TITLE
Revisit EraInfo, empty rewards struct and casper-client compatibility: discovery

### ISSUE THREAD

**Issue by piotr-dziubecki** [casper-network/casper-node#3668]
Re-design and clean-up empty reward structs that currently remain to
maintain compatibility with casper-client (see https://github.com/casper-network/casper-node/pull/3420#pullrequestreview-1200624759)

See also https://github.com/casper-network/casper-node/issues/1936 and https://github.com/casper-network/casper-node/issues/3088

UPDATE: Given that we are consolidating the rewards issuance back in the switch blocks, this is now a discovery ticket to find out whether any serious changes are needed to any part of the pipeline surfacing rewards for users

8.18.23 
As for now, the plan is that we will compute everything upfront in the node, and send a map of PublicKey -> U512 to the step function, to distribute them (mint & transfer). As I see things we may split that task that way:

We need the total supply to compute the "reward pots". We will:

- [ ] 1. store the current total supply and the last 2 historical ones in the global state;
        - [ ] a. add a way to fetch this piece of data with a contract runtime request;
        - [ ] b. update this piece of data from within the step function.
        - [ ] c. That means that we won't distribute signature rewards for more than 2 eras in the past, but such a situation where blocks cite other blocks from the 3rd era in the past should not happen anyway.
- [ ] 2. We don't have any historical validator data, which is used to compute the signature rewards of past eras. We need to figure out a way to retrieve them.
- [ ] 3. Rollback of the reward code to use the per-era distribution mechanism again, like in dev.
- [ ] 4. Implement the formula to transfer the full reward (including the signatures) to the step function: [here](https://drive.google.com/file/d/1EldXEYcZR2cBLerOjSkWUJkK-CLa_atC/view?usp=drive_link)

**Comment by AlexanderLimonov** [comment]
Reminder: don't forget to look at the mentioned tickets!

**Comment by AlexanderLimonov** [comment]
@rafal-ch, updated with new description, blocker and points

**Comment by rafal-ch** [comment]
@RitaMAllenCA this was closed due to being split into smaller tickets, right?
