### ISSUE TITLE
Share code between chainspec in testing framework and node’s chainspec

### ISSUE THREAD

**Issue by piotr-dziubecki** [casper-network/casper-node#3677]
Testing framework implements subset of ‘real’ chainspec in the node to be able to run test with a chainspec settings. This causes duplication of code, which gets harder to maintain in consistent manner. I.e. one validation step we have to add on the node side, we’d have to duplicate in testing framework. We should share as much code as possible between EE, testing framework and node. Follow up for https://github.com/casper-network/casper-node/pull/3665#discussion_r1102827436

**Comment by RitaMAllenCA** [comment]
@rafal-ch I know Karan made some changes to have the test support crate read from a chainspec.   I wonder if his work makes this more straightforward? I assigned this to you, but please assign to someone else if appropriate. Thanks

NO - this has not been done

**Comment by RitaMAllenCA** [comment]
Best to do this in casper_types or other crate.  "Decouple our types"

**Comment by devendran-m** [comment]
Won't do.
