### ISSUE TITLE
Ensure we have a test for carrying unbonds across an upgrade

### ISSUE THREAD

**Issue by devendran-m** [casper-network/casper-node#3695]
We need a test which ensures that withdraws created before an upgrade to current dev are correctly actioned after the upgrade.  This means not only checking that the pre-upgrade withdraws have been migrated to post-upgrade unbonds immediately after the upgrade, but also running the test until the unbonds are actioned at the appropriate step.  Probably worth initially seeking 
Karan[@darthsiroftardis] ’s input to see if such a test already exists, and if not, the test should be created.

**Comment by alsrdn** [comment]
We already have a test for this here: https://github.com/casper-network/casper-node/blob/3c6a3dcb6d4f3e35cc3a7ad4acad060b7b43444d/execution_engine_testing/tests/src/test/system_contracts/auction/bids.rs#L3519

It would however be useful to add a NCTL test that check unbonds post-upgrade after a validator changing emergency upgrade.

**Comment by TomVasile** [comment]
Branch: https://github.com/casper-network/casper-node/tree/cn-3695 (unfinished due to issue I'm seeing described below). Someone can pick this up for casper-node, pushed it there.

**Comment by rafal-ch** [comment]
Moved back to "In progress" as I'll try to extend the test scenario accordingly to this suggestion: https://github.com/casper-network/casper-node/pull/3835#pullrequestreview-1381205187

**Comment by rafal-ch** [comment]
Covered by [this test](https://github.com/casper-network/casper-node/blob/3eff557a95e2a8208577f9acb193303d8be49ec8/execution_engine_testing/tests/src/test/system_contracts/auction/bids.rs#L3541).

@RitaMAllenCA - we can close this.
