### ISSUE TITLE
casper client rs deployhash is conflicting with node's deployhash

### ISSUE THREAD

**Issue by RitaMAllenCA** [casper-network/casper-node#3715]
running into an issue with the casper-client-rs. During development for checkpoint charlie I ran into type conflicts between the nodes DeployHash and clients DeployHash.

**Comment by RitaMAllenCA** [comment]
The immediate issue that generated this request was resolved but is this relevant otherwise?  Seems like we "should" be keeping the rust client up to date with the node????

**Comment by Fraser999** [comment]
I think this can get closed.  The client is generally kept up to date with the node.  The `main` branch works with the latest published version of the node, while the `dev` branch works with the node's `dev` branch.
