### ISSUE TITLE
Investigate operator issue

### ISSUE THREAD

**Issue by piotr-dziubecki** [casper-network/casper-node#3718]
see discussion at https://casper-labs-team.slack.com/archives/CDX4YAHNW/p1676982897077559

**Comment by piotr-dziubecki** [comment]
https://casper_user:CaSpErPaSsWoRd123@cnm.casperlabs.io/view_debug_info/018fb709e6a4f9076fab0445a6b0cb4cf7dee6c6711c279ede1ebcbac3c3c7f0ac/1676982059

**Comment by georgepisaltu** [comment]
Upon inspecting the attached logs, I couldn't find anything abnormal in the node's behavior. The only node exit codes are 143, which correspond to process termination with `SIGTERM`. This would be the case when the user intentionally kills the process. A `SIGKILL` would be sent if it was the OOM killer which stopped the process, and there are no other suspicious logs which would point to a bug in execution.

Ultimately this seems like a setup issue and there is nothing that would point to a bug. For additional information, we would need some memory metrics/information from the operator and the state and setup of the machine.

**Comment by RitaMAllenCA** [comment]
I will bring it up at grooming

**Comment by RitaMAllenCA** [comment]
@rafal-ch to get back to the slack channel and see if @Jiuhong-casperlabs can get more logs.

**Comment by rafal-ch** [comment]
It is not possible to get more logs
https://casper-labs-team.slack.com/archives/CDX4YAHNW/p1678748281938609?thread_ts=1676982897.077559&cid=CDX4YAHNW

**Comment by ghost** [comment]
> see discussion at https://casper-labs-team.slack.com/archives/CDX4YAHNW/p1676982897077559

This is a closed resource.

Could you please provide the relevant information within the issue text?
