### ISSUE TITLE
Create a migration that moves the current era info to a stable key, and delete era info objects in trie tip

### ISSUE THREAD

**Issue by piotr-dziubecki** [casper-network/casper-node#3719]
We need to remove the current Key::EraInfo() objects in the trie. There are currently 1 per era that has passed, and this has caused a significant amount of bloat to the tip of the trie.
To do this we need to expose delete trie (done in my branch of the node at r1.4.13-era-info-bloat). We should do this on upgrade and we'll also need to route requests for the old era info to the old switch blocks' state_roots.

**Comment by RitaMAllenCA** [comment]
Fraser's change - block validator fetch bug (new ticket) #3740
