### ISSUE TITLE
Increase max_memory and max_stack_height chainspec values.

### ISSUE THREAD

**Issue by RitaMAllenCA** [casper-network/casper-node#3734]
Currently max_memory is set to 64 wasm pages which represents ~4MB of memory, and max_stack_height is set to 188 which at that time were very safe choices in terms of security. Certain uses such as using non-trivial 3rd party crypto libraries requires more memory to operate, and also larger stack height to work.

max_stack_height increase should be safe (within reasonable values), since we’re charging a lot for control flow operations anyway. For increasing max_memory we may consider properly charging per extra pages allocated if the new limit is much higher than current, or find different method.

**Comment by RitaMAllenCA** [comment]
@mpapierski please provide an estimate

**Comment by RitaMAllenCA** [comment]
needs a spike to research properly.

**Comment by mpapierski** [comment]
It seems halo2 (which was inspiration for this ticket) doesn't need more heap than we currently support; but max_stack_height is too small, seems like 443 is the minimum that makes on-chain proof verification work. Analysing security impact of such large increase of stack height.

**Comment by zie1ony** [comment]
In our DAO implementation https://github.com/odradev/dao-odra our most complex buisness logic needs 350 stack height. At the moment we are working on decreasing the complexity, but it is a huge problem...

@RitaMAllenCA could you please share what is CasperLabs' stand here? Are you prioritizing Michał's research of security of increasing the stack height? This is implacting all future DAO-based projects like XPrice.
