### ISSUE TITLE
remove k/v generics from the trie

### ISSUE THREAD

**Issue by RitaMAllenCA** [casper-network/casper-node#3743]
Removes much incidental complexity arising from making K and V arguments to trie methods generic, when in reality we rarely use this generality, and moreover only in unit tests.

In addition, we now make use of DataAccessLayer, which uses ScratchGlobalState, which wraps LmdbGlobalState. This is an intermediate refactoring step to reduce the unnecessary complexity in the trie implementation.

Going forward, we can build on this work by collapsing LmdbGlobalState and ScratchGlobalState together into a cache-aware type.

This PR also integrates cache/scratch semantics into exec/commit.

Execute + commit is now replaced by exec + apply (commits to cache), + commit_to_disk.

Also refactors WasmTestBuilder to remove it's generality related to tries and EngineState, and also integrates ScratchGlobalState more closely.

**Comment by dwerner** [comment]
#3327 - it's going to need to be rebased on latest from dev if we keep this around

**Comment by ghost** [comment]
> This PR

I don't understand.

This here is an issue, not a PR.
