### ISSUE TITLE
Long running test with Mainnet snapshot - sync_to_genesis node stuck at Block 332914 

### ISSUE THREAD

**Issue by cspramit** [casper-network/casper-node#3747]
Network: 5 + 2
Name: ajith-mainnet-clone-1
Commit: 13344921cbe90a18be1c64663f68f8f1f5f7fa37 (3+ weeks old)
Mainnet Bootstrap (1034499) + Joining Node
Long Running Network ( progressing with a Sync_to_Genesis Joining node.)
Observations:
sync_to_genesis node stuck at Block 332914 with hash 3e2fc29f3efd9417479e1fb79bd67f3f2f402c6e76631e977b1f2def72681a49
assuming multiple missing finality sigs ?
{"timestamp":"2023-03-08T04:29:30.748303Z","level":"INFO","fields":{"message":"BlockAcquisition: registering finality signature for: block hash 3e2f..1a49","signature":"finality signature for block hash 3e2f..1a49, from PubKey::Ed25519(1117..4957)","ret":"Some(NeededIt)"},"target":"casper_node::components::block_synchronizer::block_acquisition"}
...
{"timestamp":"2023-03-08T04:29:31.123354Z","level":"INFO","fields":{"message":"BlockAcquisition: registering finality signature for: block hash 3e2f..1a49","signature":"finality signature for block hash 3e2f..1a49, from PubKey::Ed25519(3eb6..3844)","ret":"None"},"target":"casper_node::components::block_synchronizer::block_acquisition"}
Grafana: https://grafana.casperlabs.io/goto/OBcBMeb4k?orgId=1
Dumps: http://genesis.casperlabs.io/ajith-mainnet-clone-1/casper-node-dumps/ajith-mainnet-clone-1/09032023_0012/dump_download_list.html

**Comment by rafal-ch** [comment]
https://casper-labs-team.slack.com/archives/C01ULKL8G8J/p1678320865527179

**Comment by rafal-ch** [comment]
**Observations:**

The node has correctly synced back through block `332820`.
The previous one `332819` was synced up to the `HaveAllDeploys` state and then got stack on the loop:
```
BlockSynchronizer: need next for block hash 0d4b..e8e3: finality signatures at era 2828 (51 validators)
BlockSynchronizer: need next for block hash 0d4b..e8e3: peers
```
which indicates that the node couldn't get the `Strict` finality for this block.

However, after restart, it was able to complete the sync flow for `332819` flawlessly, i.e. it was able to pass through the:
```
"BlockSynchronizer: need next for block hash 0d4b..e8e3: finality signatures at era 2828 (51 validators)"
```
down to 
```
"BlockSynchronizer: need next for block hash 0d4b..e8e3: finality signatures at era 2828 (45 validators)"
```
and then marked block complete:
```
"BlockSynchronizer: need next for block hash 0d4b..e8e3: mark complete (height 332819)"
```

Inspecting logs from other nodes shows that they **did not** ban the node who got stuck.

Possibly, we exhausted peers from "our" list and were unable to get awareness of any other peer?

There are the following warnings in the log for the problematic block:
```
"failed to apply execution results","error":"attempt to apply execution results for already completed block_hash: block hash 0d4b..e8e3"
"BlockAcquisition: invalid attempt to register deploy for: block hash 0d4b..e8e3"
```
but neither of them leads to the peer being classified as dishonest.

For "correct" blocks we have:
```
BlockSynchronizer: need next for block hash e777..d5ab: finality signatures
BlockAcquisition: registering finality signature for: block hash e777..d5
```

But for the problematic one it seems like we can't fetch the sigs:
```
BlockSynchronizer: need next for block hash 0d4b..e8e3: finality signatures
BlockSynchronizer: need next for block hash 0d4b..e8e3: finality signatures
BlockSynchronizer: need next for block hash 0d4b..e8e3: finality signatures
need next for block hash 0d4b..e8e3: peers
```

Maybe we don't have peers [here](https://github.com/casper-network/casper-node/blob/dev/node/src/components/block_synchronizer.rs#L566) and don't really go into the loop.

I added [a PR](https://github.com/casper-network/casper-node/pull/3749) that will extend our debug logging.

**Comment by rafal-ch** [comment]
The stuck block is now `283608` (`d1e4..e4a3`). Again, there is trouble getting strict finality.

The node cannot fetch required finality signatures from any of the peers. The flow:
* node is in `need next for block hash d1e4..e4a3: finality signatures at era 2601 (37 validators)`
* it runs out of peers and refreshes the list
* it gets 5 peers from the network component
* all 5 peers are asked for the finality signature but fail to deliver (`BlockSynchronizer: failed to fetch finality signature","err":"could not fetch item with id FinalitySignatureId`)

Node tried all 7 peers multiple times, indicating that the `BlockSynchronizer` flow is correct.

```
NodeId(443c4544172d63527605ef255ee1e35b813d2a786d73d547c58f50a82274b389a1f5efdb8fd704477e8b4b2d5614ad70dacb215004751e806598e7d6e5ebf8e4)
NodeId(4b350f8f37a9221f217dc7a01d48b5109e3c7e5a26db1f69c7f0d925a835355bbc55df2efb488124c9c48e503524edc9c0f745d7d2f34b5f5d8237b7de28e5e3)
NodeId(6b4501278e8f2d5ab508de4077db392f3d9d2be844d4ed9d6aaf17fd60f046719f4ea1a7e1ddb952a40e23db927beeaf816670758f5da88bfd8af467428ec354)
NodeId(8a733029ecb6360c00dd297ac470bdd758113b11763ccb2554065e6cbcd3272809580f3d9d4ae15988d0597b400198393bbd1151f0be27e654dbc88d018e459b)
NodeId(caad6afef03479181c33beb6b27d74b38304d8b367a66ba346690888875e72f79bcd63ce2df6b02ae1a409361aab0427b7336825851089b512f8e1798ecdec54)
NodeId(eddeebf481ef48df43f1c9b9ee774e1e6d2962cd1197bdb8ab148fd07b82408bfb2157b72afbaaf0ae56bb8a5152b910b9672180466170ddfffc330a4ccc845a)
NodeId(f90ff348010df7b81ad3662be7a77b740c472381275e29c37ef0ffa7680037d5e601f96438044b480a21a2767c400715af32987969b1cb7ab9e6f8e005dcc24b)
```

`could not fetch item with id FinalitySignatureId` actually means `Error::Absent`, so the `opt_item` [here](https://github.com/casper-network/casper-node/blob/dev/node/src/components/storage.rs#L709) must be `None`, which means that other peers can't get it from local storage.

After restarting the stuck node, it is again in `need next for block hash d1e4..e4a3: finality signatures at era 2601 (37 validators)`, it starts asking for signatures and demotes some peers, including `8a73...459b`. However, shortly after we have a success:
```
BlockSynchronizer: fetched finality signature finality signature for block hash d1e4..e4a3, from PubKey::Ed25519(2bac..e69b) from peer tls:8a73..459b
```
peer is promoted and block is marked complete.

**Comment by rafal-ch** [comment]
The suspicion is that the code around [this place](https://github.com/casper-network/casper-node/blob/dev/node/src/components/block_synchronizer.rs#L568-L587) doesn't guarantee that we'll eventually try to ask every peer for a finality signature for particular block from specific validator.

The peer who was able to finally deliver us the signature after restart was:
```
NodeId(8a733029ecb6360c00dd297ac470bdd758113b11763ccb2554065e6cbcd3272809580f3d9d4ae15988d0597b400198393bbd1151f0be27e654dbc88d018e459b)
```
and the validator id was:
```
PubKey::Ed25519(2bac..e69b)
```

It could be either that request for this finality signature was stuck in `pending` (hence supposedly never issued again) or that the linked `for` loop, which is limited to `max_simultaneous_peers` never issues a required combination of `peer` and `validator`.

cc: @Fraser999 @georgepisaltu
