### ISSUE TITLE
Improve error reporting for wasms code produced with compilers supporting proposals we don’t currently support

### ISSUE THREAD

**Issue by RitaMAllenCA** [casper-network/casper-node#3762]
We could improve error reporting of such wasm code, so instead of Wasm preprocessing error: Deserialization error: Unknown opcode 252 we could say Wasm preprocessing error: Bulk memory proposal not supported . We can do the same for other proposals: atomics, simd, sign_ext, multi_value. It seems parity-tech supports parsing these proposals with a feature flag https://github.com/paritytech/parity-wasm/blob/master/Cargo.toml so we need a preprocessing step to raise error if an opcode is found.
We should first double check if parity-wasm supports parsing all widely supported proposals, and if wasmi would pick up parity-wasm with non-default flags.

**Comment by RitaMAllenCA** [comment]
@mpapierski please provide an estimate

**Comment by rafal-ch** [comment]
It's ready on the branch.

Todo:
- wait for 1.4.15 to dev merge (done)
- wait for dev to 1.6 merge (@georgepisaltu is working on this rn)
- open PR against 1.6

**Comment by rafal-ch** [comment]
@mpapierski as agreed, please have a second look at the changes
