### ISSUE TITLE
Need to bump wasmi to 0.13.2 

### ISSUE THREAD

**Issue by RitaMAllenCA** [casper-network/casper-node#3766]
We need to bump wasmi to 0.13.2 (aka "battle tested") as it gives the most performance benefit with little work

linked the related ticket: #3575 

There are just a few minor code changes required, and there are some depreciations introduced. We should collectively review the diff from 0.9.1 to 0.13.2 to ensure we understand all the changes involved since 0.9.

**Comment by rafal-ch** [comment]
As agreed, keep this in 1.6.
