### ISSUE TITLE
Can't put deploy via `casper_client` crate.

### ISSUE THREAD

**Issue by zie1ony** [casper-network/casper-node#3840]
It is not possible to construct `casper_node::types::Deploy` and send it via `casper_client` crate. This is due to `RpcCall` from `casper_client` is `pub (crate)`.
I also think it make sense to move `Deploy` and all elements needed for its construction to `casper_types`.

**Comment by RitaMAllenCA** [comment]
@zie1ony we are doing some extensive types restructuring in 2.0, which we are currently planning.  I have added this to the epic capturing that work.

**Comment by RitaMAllenCA** [comment]
@zie1ony this will be addressed when we move the deploy to casper_types.  It will require and update to casper_client to point to casper_types. Closing it as a duplicate.
