### ISSUE TITLE
Speed up some UTs thanks to configurable latch reset interval

### ISSUE THREAD

**Issue by RitaMAllenCA** [casper-network/casper-node#3844]
Some of our UTs (for example, global_state_sync_wont_stall_with_bad_peers) need to wait for latch to reset, so there are hardcoded sleeps for 6 seconds. Thanks to [#3810](https://github.com/casper-network/casper-node/pull/3810) we now have the ability to configure latch interval, hence we can make the tests to run faster.

**Comment by alsrdn** [comment]
Fixed by: https://github.com/casper-network/casper-node/pull/3878
