### ISSUE TITLE
Fix flaky block synchronizer test

### ISSUE THREAD

**Issue by RitaMAllenCA** [casper-network/casper-node#3845]
When using `CL_TEST_SEED=ae607eb2e2365c32fa839cf963495d46` the `registering_block_body_transitions_builder_to_have_block_state `test [fails](https://drone-auto-casper-network.casperlabs.io/casper-network/casper-node/8035/1/3) and `fwd_having_block_body_for_block_without_deploys_requires_only_signatures `seems to be stack when running for more than 2 minutes.

1.5 (release blocker until we find out that the reason is bad test, not bad code)

**Comment by rafal-ch** [comment]
Here's another run where the `fwd_having_block_body_for_block_without_deploys_requires_only_signatures` test got stuck:

https://drone-auto-casper-network.casperlabs.io/casper-network/casper-node/8056/1/3

cc: @alsrdn @Boiethios
