### ISSUE TITLE
Extend the upgrade_scenario_11.sh test to check existence of unbonding purse

### ISSUE THREAD

**Issue by RitaMAllenCA** [casper-network/casper-node#3846]
Part of the upgrade_scenario_11.sh has been delivered in https://github.com/casper-network/casper-node/pull/3835. It doesn't, however, cover all requirements described in [the ticket](https://github.com/casper-network/casper-node/issues/3695). Hence we still need some work on this test, according to the comments [here](https://github.com/casper-network/casper-node/pull/3835#pullrequestreview-1381205187) and [here](https://github.com/casper-network/casper-node/pull/3835#issuecomment-1508172340).

**Comment by RitaMAllenCA** [comment]
5.4.23 Star Wars day.....   @Karan to follow up - this may be done

**Comment by rafal-ch** [comment]
Covered by [this test](https://github.com/casper-network/casper-node/blob/3eff557a95e2a8208577f9acb193303d8be49ec8/execution_engine_testing/tests/src/test/system_contracts/auction/bids.rs#L3541).

@RitaMAllenCA - we can close this.
