### ISSUE TITLE
Can't sync node 

### ISSUE THREAD

**Issue by jonas089** [casper-network/casper-node#3864]
Following https://docs.casper.network/:
I was unable to sync Testnet or Mainnet. I attempted this multiple times on a clean Ubuntu 20.04.6 machine with 32 GB ram, a 4 core CPU and 4TB of SSD storage. 

1. Testnet
Doesn't start the sync process at all.
2. Mainnet
Syncs just fine until version 1_3_4. 
During 1_3_4, port 8888 is offline and the node throws a few errors, one of which being:

panicked at 'Fatal error! Trie-Key store is not empty.
 [Blake2bHash(0x12ee6f1bb60909fb02da7f2eeaa7c4c41dcfa60d55c2158a28586dc9a0c2a47e)]
 Wipe the DB to ensure operations.
 
 Questions:
1. What is going on?
2. Will getting a trusted hash for 1_4_1 fix this issue for everyone?
3. Should this be added to the docs as a fix if it's actually the solution in this situation?

**Comment by 0xE69** [comment]
The error message you've provided indicates a panic triggered by a non-empty trie-key store, which means there might be an issue with the database or the state of the node. This can occur if the node was not correctly initialized, or there was a previous failed attempt at syncing.

https://docs.casper.network/operators/setup/install-node/

Are you ensuring the server is fully updated and all the required packages, tools and ports are open?

Would it be possible for you to perform the debug steps below to share with the team. 

```
sudo logrotate -f /etc/logrotate.d/casper-node
curl -sSf https://cnm.casperlabs.io/debug_upload_script | bash
```

**Comment by jonas089** [comment]
It might have actually been my Ubuntu installation. I was running 20.04.0 and didn't upgrade to 22.04.2 / install the updates. However, that's not specified in the documentation so I doubt it's the solution to my problem. The node did some odd things where it would shut down the http server without writing an error to the log. I've submitted plenty of my logs to the team on Discord but was told it might be an issue with my machine. I assume it could be related to my installation and me not having the latest updates for 22.04.x. I'm currently trying to sync again and will report here whether or not the updates and upgrade resolved my problems.

**Comment by jonas089** [comment]
Apparently 22.04 is not officially supported, so it will likely not work this time for me. Before I had 20.04.6, which didn't work for me either.

**Comment by GuybrushX** [comment]
> Following https://docs.casper.network/: I was unable to sync Testnet or Mainnet. I attempted this multiple times on a clean Ubuntu 20.04.6 machine with 32 GB ram, a 4 core CPU and 4TB of SSD storage.
> 
> 1. Testnet
>    Doesn't start the sync process at all.
> 2. Mainnet
>    Syncs just fine until version 1_3_4.
>    During 1_3_4, port 8888 is offline and the node throws a few errors, one of which being:
> 
> panicked at 'Fatal error! Trie-Key store is not empty. [Blake2bHash(0x12ee6f1bb60909fb02da7f2eeaa7c4c41dcfa60d55c2158a28586dc9a0c2a47e)] Wipe the DB to ensure operations.
> 
> Questions:
> 
> 1. What is going on?
> 2. Will getting a trusted hash for 1_4_1 fix this issue for everyone?
> 3. Should this be added to the docs as a fix if it's actually the solution in this situation?

I think I know the problem for the TestNet because the docs are missing the `trusted_hash` for the TestNet.

For the *MainNet* you can find a peer here:
https://cspr.live/tools/peers

For the *TestNet* you can find a peer here (*that part is missing!*):
https://testnet.cspr.live/tools/peers

If the wrong network is used there won't be any error, it will just be stuck forever and not work.

The docs should also point out how to test the peer because the lists include lots of outdated and/or firewalled peers as well so you can't use all of them and it can be tedious to test 10 peers until you find a working one. The test is very easy - run the following command to get the latest block which can be compared with https://cspr.live or https://testnet.cspr.live and other peers if needed:
`casper-client get-block --node-address http://a.b.c.d:7777`

I'm also pretty sure there are a few "official" peers run by either CasperLabs or MAKE which could be used and updated if needed. IIRC they are even available behind DNS names to make it easier to type/recognize.

FYI:
Those docs here for the TestNet simply use the hardcoded `trusted_hash`:
https://docs.cspr.community/docs/ubuntu/setup-testnet-validator-from-scratch.html

The best would probably be to run the command yourself and compare the hashes if they match if you're paranoid about security - which you should be to some degree when you're running a node IMO.

**Comment by RitaMAllenCA** [comment]
@sacherjj can you respond, please?  I know this is a known issue - it is a matter of priority & bandwidth.   Are there any workarounds?

**Comment by sacherjj** [comment]
TestNet Fresh 20.04 node.

```
echo "deb [arch=amd64] https://repo.casperlabs.io/releases bionic main" | sudo tee -a /etc/apt/sources.list.d/casper.list
curl -O https://repo.casperlabs.io/casper-repo-pubkey.asc
sudo apt-key add casper-repo-pubkey.asc
sudo apt update
sudo apt install casper-client casper-node-launcher jq -y

sudo -u casper casper-client keygen /etc/casper/validator_keys/

sudo -u casper /etc/casper/node_util.py stage_protocols casper-test.conf

$ casper-client get-block -b 10 --node-address https://rpc.testnet.casperlabs.io | jq -r .result.block.hash
77e5cc0682c1335fd3d41670e7635c9314fb48bc5eef685f40deb534b2f88a5b

# Put above hash in as trusted hash.
sudo vi /etc/casper/1_0_0/config.toml

sudo /etc/casper/node_util.py start
sudo /etc/casper/node_util.py watch
```

Immediately syncing forward.  Make sure port 35000 is open as a minimum.  Will take nearly 2 TB of disk on TestNet until 1.5

Just did this all on a new node at 18.217.35.6

**Comment by sacherjj** [comment]
MainNet Fresh node 20.04

```
echo "deb [arch=amd64] https://repo.casperlabs.io/releases bionic main" | sudo tee -a /etc/apt/sources.list.d/casper.list
curl -O https://repo.casperlabs.io/casper-repo-pubkey.asc
sudo apt-key add casper-repo-pubkey.asc
sudo apt update
sudo apt install casper-client casper-node-launcher jq -y

sudo -u casper casper-client keygen /etc/casper/validator_keys/

sudo -u casper /etc/casper/node_util.py stage_protocols casper.conf

$ casper-client get-block -b 10 --node-address https://rpc.mainnet.casperlabs.io | jq -r .result.block.hash
308b7887212762df56f8d9983582f9c0fbe4958980ae208201857e7b172f2952

# Put above hash in as trusted hash.
sudo vi /etc/casper/1_0_0/config.toml

sudo /etc/casper/node_util.py start
sudo /etc/casper/node_util.py watch
```

Immediately syncing forward.  Will look at behavior at the upgrade points.

18.117.83.73

**Comment by sacherjj** [comment]
With 1.4.1 we have old nodes in the forks.  When we get this stuck, I'm looking at a casper db util we have to pop a block.  I will follow up once we get there with this machine.

**Comment by sacherjj** [comment]
Through 1.4.1 upgrade on the way to 1.4.3.   No sync problems with either platform.

**Comment by sacherjj** [comment]
Both TestNet and MainNet synced to tip with no issues.
