### ISSUE TITLE
Prune Unbond entries from global state when the queue for a validator is empty.

### ISSUE THREAD

**Issue by RitaMAllenCA** [casper-network/casper-node#3869]
At the end of processing all unbond requests we should also prune value under Key::Unbond if length of queue reaches zero. Not doing it means we’ll keep a lot of entries with empty queues, and due to the design we’ll always iterate over empty queues when processing unbonding requests. Pruning also decreases time for fast-sync as it doesn’t need to go through effectively empty values. We’re introducing a new keyspace as part of 1.5 and with pruning we won’t end up with bloat if we do pruning. We should also prune Withdraw entries when copying data into Unbond keyspace.

**Comment by rafal-ch** [comment]
Unassigning @alsrdn since @mpapierski is back.
