### ISSUE TITLE
Investigate potential race conditions related to builder purge in synchronizer

### ISSUE THREAD

**Issue by RitaMAllenCA** [casper-network/casper-node#3872]
In the block synchronizer, when register_marked_complete is called on the builder in the historical flow, it transitions to the Complete state, then it creates effects to get the execution results to which a meta block announcement is chained with a .then(). The block needed to create a meta block announcement is obtained by calling maybe_block, which luckily clones the block and then captures the clone in the closure context inside the created future, which prevents a race condition where the builder would transition to Complete, which from the control logic perspective would mean it's done and ready to be purged, even though it's still trying to get execution results and then announce a meta block. Thanks to the capture in the closure through the move keyword (which was probably required by the compiler which realized something was wrong), we are safe in this particular scenario. We should, however, investigate whether there are any other race conditions of this nature in our structures, particularly in the block synchronizer since a similar investigation was done on the block accumulator a while back.

**Comment by RitaMAllenCA** [comment]
spend no more than 1/2 sprint looking into this before moving to 2.0 work

**Comment by georgepisaltu** [comment]
The deep dive into the existing 1.5 code did not reveal any other unsafe purges, mainly due to our inefficient `.clone()` habit. Once the optimizations come in, the compiler should alert us about most such cases and we should do another review then. Closing this for now.
