### ISSUE TITLE
Introduce bytesrepr_derive and replace manual implementations where applicable

### ISSUE THREAD

**Issue by RitaMAllenCA** [casper-network/casper-node#3873]
The PR at <https://github.com/casper-network/casper-node/pull/3799>, (currently pointing at 30593f0) contains a working derive macro for bytesrepr implementations. The goal of this ticket is to separate it from the closed PR, introduce it in a separate PR that also replaces most (if not all) manual implementations of ToBytes/FromBytes.
Snapshot-testing (or something similar) should be added (ideally by modifying the common testing function), ensuring that a before-snapshot is stored before the replacements are made.

**Comment by marc-casperlabs** [comment]
Partial work stemming from the WONTDO of #2944 can be found in https://github.com/marc-casperlabs/casper-node/tree/3873-bytesrepr-derive, which has already been cleaned up (non-relevant work to this ticket has been reverted).

**Comment by devendran-m** [comment]
Won't do.
