### ISSUE TITLE
Factor out additional networking logic from networking component

### ISSUE THREAD

**Issue by RitaMAllenCA** [casper-network/casper-node#3874]
Ensure that most of the core networking logic is removed from the networking component, allowing for reuse. In the end, the low-level inner networking code should end up in muxink (or whatever it is named), whereas more node-specific code should end up in a second crate. The networking component itself, in the end, should be fairly thin as a result.

**Comment by marc-casperlabs** [comment]
Closing this in favor of juliet (see 3bf4de589 and following on `nt-juliet` branch). Once said branch is completed and merged, this will essentially be done.
