### ISSUE TITLE
Change the config behaviour of public_address to better support automated deployment solutions

### ISSUE THREAD

**Issue by RitaMAllenCA** [casper-network/casper-node#3891]
See this slack discussion: https://casper-labs-team.slack.com/archives/CDXBCHB6W/p1682322669186599

**Comment by RitaMAllenCA** [comment]
extract into a separate file.  There are several ways to address this - SRE to discuss internally.

**Comment by rob-casper** [comment]
@RitaMAllenCA - I'd prefer address discovery logic to become part of the casper-node initialisation (in rust) and not a seperate file / SRE maintained thing. 

This would eliminate the need for config templating, and our current 'launcher' pattern means ~16 config files need to be updated on public address change (if the logic was internal to the node, Zero config files to be updated every time the public address changes)

eg. 

if public_address is unset/commented out in config file - default behaviour is for node to perform public address discovery during init
if public_address is set in config file - use this address, don't perform discovery

**Comment by RitaMAllenCA** [comment]
@rob-casper @sacherjj said he would discuss this internally with SRE.   Probably not going to do much at the moment given the SRE team is short-handed right now.   Up to the team.

**Comment by sacherjj** [comment]
This would be a node change not an SRE change to allow on config for the whole node. Backlog until post 2.0.

**Comment by RitaMAllenCA** [comment]
6.20.23 standup:  This is doable and we need to show SRE what has been put in place to support it.   Given it is a low priority nice-to-have, I will defer work for now while the SRE team is short staffed.  Check in at 1.7 or later.
