### ISSUE TITLE
[spike] Research minimum amount of protocol state needed to reinitialize after down-time

### ISSUE THREAD

**Issue by RitaMAllenCA** [casper-network/casper-node#3904]
research if we need the entire graph. Want to understand why are are not keeping consensus state data.   What is the minimum amount of protocol state needed for a validator to be able to resume participation after a restart for (highway).   
what data is needed to reinitialize, how big is it and what is needed to store it?

Protocol state for Zug: echos and votes sent in different rounds (multiple rounds in each era).   Protection against "amazon" down-time.   Only kept in memory.  Need to keep some on disk in order to persist through node down-time.   

Will need implementation to store info to disk for both Highway and Zug.

**Comment by fizyk20** [comment]
A summary of the findings: https://hackmd.io/6RSUz7vSSki9tZFicDZSdw

**Comment by fizyk20** [comment]
A section about Zug should be added to the document before this is reviewed.

**Comment by MParlikar** [comment]
Simply stated, the protocol state needs to be written to disk.

**Comment by devendran-m** [comment]
@fizyk20 - Ed thinks you did this. Can you confirm please?

**Comment by fizyk20** [comment]
@devendran-m This has been done for Highway, but never quite finished for Zug. I think we did decide to close this issue at some point, though (but I'm not 100% sure).

**Comment by devendran-m** [comment]
As per the discussion in the L1 Daily on 17-Sep-24;
- Check if the Highway mechanism is implemented and the scope required to finish for Zug.
