### ISSUE TITLE
Finality signature tracking field in blocks

### ISSUE THREAD

**Issue by RitaMAllenCA** [casper-network/casper-node#3910]
To ensure that all validators calculate the same rewards for a particular block, signatures should be treated somewhat similarly to deploys, in the sense that a list of identifiers (public keys) should be part of the block payload. These identifiers would correspond to a source block determined by the rewards lag, or the last switch block. Once a proposed block is received, the non-proposing validator should fetch and validate missing finality signatures as part of block validation.

**NOTE: Please read the design doc for additional details on potential implementation choices, e.g., only rewarding last era switch block and abstracting public keys as a vector of booleans or similar if certain structures are changed to implement sorting by public key.**

Design doc: https://docs.google.com/document/d/1S00ehCnX9fjEHb2L3kBgDcoN_Q3Xb3IhuovQieMT6Lc

We must be able to prove decentralized agreement of blockchain validity for archival purposes. In order to ensure this, when proposing a switch block it must include sufficient finality signatures of the previous switch block. To prevent censorship, we allow all proposers to include finality signatures of the previous switch block in their proposals, and the switch block contains all finality signatures that were proposed during the era.

E.g. every proposed block in era 6 is allowed to contain any number of valid finality signatures for the switch block at the end of era 5, but only if they haven't already been included in an earlier proposed block.

Subject Matter Expert: @fizyk20, @AlexanderLimonov

**Comment by AlexanderLimonov** [comment]
Completed
