### ISSUE TITLE
Validate finality signature payload & fetch missing signatures

### ISSUE THREAD

**Issue by AlexanderLimonov** [casper-network/casper-node#3913]

**Comment by rafal-ch** [comment]
13 points, depending on the outcome of the discussion about the `ValidatorMatrix` and reactor context, this may turn out to be quite big

**Comment by AlexanderLimonov** [comment]
I can try to break this down into an epic and multiple issues once next week's talks about the architecture are concluded

**Comment by rafal-ch** [comment]
For now, we use `ValidatorMatrix` as is (meaning: we add it to the places where it's needed) and continue with the ticket.
