### ISSUE TITLE
Modify chainspec to include relevant parameters

### ISSUE THREAD

**Issue by AlexanderLimonov** [casper-network/casper-node#3915]
We need to introduce three new parameters into the chainspec, and make the following readable from the Mint contract,

**f** – finder’s fee, indicating the split in finality signature rewards between block producer and participating signers

**Finality signature proportion**, or the proportion of baseline rewards going to reward finality signatures specifically

**Rewards lag** is a parameter that would need to be introduced only for the rewards with a fixed height lag, and need not be readable from the Mint contract.

**Comment by real-felix** [comment]
I'll add the parameters with the default mainnet values:
- `finders_fee` with value 0.2
- `finality_signature_proportion` with value 0.5
- `rewards_lag` with value 3
