### ISSUE TITLE
Casper-execution-engine fails to build

### ISSUE THREAD

**Issue by ghost** [casper-network/casper-node#3921]
I'm trying to build Casper-db-utils, but it's failing while building the casper-execution-engine

The error is this repeated:
```
error[E0004]: non-exhaustive patterns: `casper_types::Key::EraSummary` not covered
   --> /home/lanadmin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/casper-execution-engine-2.0.1/src/core/runtime_context/mod.rs:252:15
    |
252 |         match self.base_key() {
    |               ^^^^^^^^^^^^^^^ pattern `casper_types::Key::EraSummary` not covered
    |
note: `casper_types::Key` defined here
   --> /home/lanadmin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/casper-types-1.6.0/src/key.rs:132:5
    |
107 | pub enum Key {
    | ------------
...
132 |     EraSummary,
    |     ^^^^^^^^^^ not covered
    = note: the matched value is of type `casper_types::Key`
help: ensure that all possible cases are being handled by adding a match arm with a wildcard pattern or an explicit pattern as shown
    |
321 ~             },
322 +             casper_types::Key::EraSummary => todo!()
    |

```

I've tried building against Rust Stable (which fails on the unarray crate for using unstable features)
As well as Nightly and Beta, which produce this error

**Comment by georgepisaltu** [comment]
Hey, it seems there's a version mismatch between `casper-types` and `casper-node`. Can you please try to edit your `Cargo.toml` in `casper-db-utils` to use `casper-types = "1.5"` specifically and try to build with that while we try to fix this upstream?

**Comment by ghost** [comment]
> Hey, it seems there's a version mismatch between `casper-types` and `casper-node`. Can you please try to edit your `Cargo.toml` in `casper-db-utils` to use `casper-types = "1.5"` specifically and try to build with that while we try to fix this upstream?

Just tried that, same errors, bumped the casper-execution-engine in the Cargo.toml to 3.1, which cleared the other errors, but gave me a new one!

```
error[E0432]: unresolved import `casper_node::types::Timestamp`
  --> src/subcommands/latest_block_summary/block_info.rs:11:50
   |
11 | use casper_node::types::{BlockHash, BlockHeader, Timestamp};
   |                                                  ^^^^^^^^^ no `Timestamp` in `types`
   |
   = help: consider importing this struct instead:
           casper_types::Timestamp

For more information about this error, try `rustc --explain E0432`.
```

**Comment by Liam-LAN** [comment]
Okay, Building with Casper-types=1 and casper-execution-engine=3.1 with BETA instead of Nightly, seems like it's working.

**Comment by georgepisaltu** [comment]
> > Hey, it seems there's a version mismatch between `casper-types` and `casper-node`. Can you please try to edit your `Cargo.toml` in `casper-db-utils` to use `casper-types = "1.5"` specifically and try to build with that while we try to fix this upstream?
> 
> Just tried that, same errors, bumped the casper-execution-engine in the Cargo.toml to 3.1, which cleared the other errors, but gave me a new one!
> 
> ```
> error[E0432]: unresolved import `casper_node::types::Timestamp`
>   --> src/subcommands/latest_block_summary/block_info.rs:11:50
>    |
> 11 | use casper_node::types::{BlockHash, BlockHeader, Timestamp};
>    |                                                  ^^^^^^^^^ no `Timestamp` in `types`
>    |
>    = help: consider importing this struct instead:
>            casper_types::Timestamp
> 
> For more information about this error, try `rustc --explain E0432`.
> ```

You can solve that error locally to make it build while we fix the underlying problem with the dependencies. All you have to do is go in `src/subcommands/latest_block_summary/block_info.rs` and import `Timestamp` from `casper_types` instead of `casper_node::types`, as the error suggests.

**Comment by ghost** [comment]
Perfect, I've built it, I'll leave this issue open for tracking,

Thanks!

**Comment by RitaMAllenCA** [comment]
I have scheduled this to be addressed in an upcoming release.   The types-mismatch is a known inconvenience we expect to remove in the next couple of sprints.

**Comment by alsrdn** [comment]
`casper-db-utils` now has a stable set of dependencies on the `dev` branch. The issue that was tracking the problem in `casper-db-utils` is now fixed: https://github.com/casper-network/casper-db-utils/issues/37
