### ISSUE TITLE
Move era end data from block header to block body

### ISSUE THREAD

**Issue by RitaMAllenCA** [casper-network/casper-node#3925]
NOTE: this issue was originally to do an analysis of what is in the block header vs block body and possibly reorganize. Some changes were made in 2.0, but one field that probably should be in the body remains in the header...the era end field which is only populated on switch blocks and is load bearing to auction and consensus.

Due to reasons, the field will remain on the header in 2.0. 

A future 3.0 could revisit this, as it would definitely be a breaking change unsuitable to a minor or patch release, so leaving this on the backlog.

**Comment by devendran-m** [comment]
Ed and Karan to review the choices made by the prev. engineers about the new bloc struct and determine if the changes needs to be made.

**Comment by EdHastingsCasperAssociation** [comment]
The state of block header / body at time of writing is, the body contains rewards and transaction hashes and the header contains everything else. 

Of the fields in the header, the one that stands out as questionable is 

    /// The `EraEnd` of a block if it is a switch block.
    pub(super) era_end: Option<EraEndV2>,

In my opinion, given the size when populated, this field should be in the body. 

However, the current block includes this in the header, and there is a dependency in the era_supervisor `create_new_era` that expects to get that info from switch block headers. While it could be rewritten to use the body instead, there are a series of ripples that such a refactor would cause. 

Given the available resources, including time, and the fact that this is the same as current block, my conclusion is that its not currently worth pursuing moving the era end data off the header.

**Comment by devendran-m** [comment]
Won't do.
