### ISSUE TITLE
Rework the finality signature rewards design to minimized disk use

### ISSUE THREAD

**Issue by AlexanderLimonov** [casper-network/casper-node#3947]
https://docs.google.com/document/d/1S00ehCnX9fjEHb2L3kBgDcoN_Q3Xb3IhuovQieMT6Lc/edit?pli=1

**Comment by RitaMAllenCA** [comment]
6.5.23 Remaining work is to document what will be done.

**Comment by rafal-ch** [comment]
> 6.5.23 Remaining work is to document what will be done.

@RitaMAllenCA @AlexanderLimonov is this documented now? Can we close this one?

**Comment by AlexanderLimonov** [comment]
We're still working towards a final determination of whether the calculation should be done in one go in the switch block, or whether the era supervisor should maintain "incremental" reward calculations in memory (there's also a ticket missing for implementing this, for this reason)

**Comment by AlexanderLimonov** [comment]
See comments in linked design doc
