### ISSUE TITLE
Fix stale sync leaper activity that affects recovery code.

### ISSUE THREAD

**Issue by RitaMAllenCA** [casper-network/casper-node#3958]
Sometimes the sync leaper leap activity is not correctly reset and causes the node to fail to recover later when it gets out of sync. This happens due to a race condition that appears when we update the validator matrix with the validators for a block after an upgrade. This happens because the validator matrix update is delayed because the validators need to be read from global state but by doing so the update can interleave within the normal determination of the keep up sync instruction. If the update comes after a leap request is sent, the leap activity will not be reset since the keep up look may not need to check the leap status again if it starts to sync a block and then finishes historical sync.

https://casper-labs-team.slack.com/archives/C01ULKL8G8J/p1683555641063689?thread_ts=1683532289.461419&cid=C01ULKL8G8J

**Comment by alsrdn** [comment]
Fixed in https://github.com/casper-network/casper-node/pull/3950
