### ISSUE TITLE
When a node loses all peer connections, it should fall back to ReactorState::Initialize

### ISSUE THREAD

**Issue by RitaMAllenCA** [casper-network/casper-node#3986]
To avoid tight looping in the BlockSynchronizer in the case of having no peers, we should instead fall back to Initialize state, which should cause the node to start waiting for sufficient fully connected peers again.

**Comment by RitaMAllenCA** [comment]
@rafal-ch assigned this to you, but please reassign as cycles allow

**Comment by rafal-ch** [comment]
Let's not switch back to Initialize, cause the node is already initialized.
After the ban is lifted, the block synchronizer will get new peers to talk to and resume syncing.
The original issue which caused peers to be banned is solved (fetch of legacy deploy) and in case there is yet another problem that causes banning, we should only make sure that we're not asking for new peers very quickly (= spam logs).

Don't add new latch please :)

@Fraser999 @EdHastingsCasperLabs
