### ISSUE TITLE
Fix flaky nightly test: upgrade_scenario_13

### ISSUE THREAD

**Issue by RitaMAllenCA** [casper-network/casper-node#4000]
Test failed in this nightly build: https://drone-auto-casper-network.casperlabs.io/casper-network/casper-node/8367/1/4
It was checked locally against dev and worked correctly, so flakiness is suspected here.

**Comment by rafal-ch** [comment]
This looks like the same issue that is addressed in [this PR](https://github.com/casper-network/casper-node/pull/3971) (should_validate queue_depth keeps growing after node comes up after upgrade).

The mentioned PR should merge soon, we'll keep observing nightly runs to see if this issue resurfaces.

@RitaMAllenCA I propose to close this issue for now.

**Comment by rafal-ch** [comment]
Fixed by https://github.com/casper-network/casper-node/pull/3971
