### ISSUE TITLE
Revisit the BlockSynchronizerProgress::Stalled added in here

### ISSUE THREAD

**Issue by RitaMAllenCA** [casper-network/casper-node#4029]
During the recent discussion about OOM problems we stumbled upon this change. The [linked ticket](https://github.com/casper-network/casper-node/issues/3815) doesn't tell anything about the problem we've been trying to fix - it just gives a solution. Because the justification of the new state `Stalled` is not clear, we should revisit this code

**Comment by rafal-ch** [comment]
Just for the record, this is not the actual release-blocker, it more of an improvement of the design.

**Comment by EdHastingsCasperAssociation** [comment]
Alex and I put up a PR that addresses this which merged; it will go into the next rc (whichever ver that may be)

**Comment by alsrdn** [comment]
It seems like the PR didn't actually merge because the bors test didn't pass. Reopening this ticket.
