### ISSUE TITLE
Deactivate and reactivate consensus when entering/leaving the Validate state

### ISSUE THREAD

**Issue by RitaMAllenCA** [casper-network/casper-node#4037]
Currently when the node transitions from Validate state to CatchUp or KeepUp it doesn't deactivate consensus, which might cause it to propose blocks when it shouldn't. We should call deactivate_validator on the latest era when we leave the Validate state and activate_validator when we re-enter that state and the latest required era already exists.

**Comment by devendran-m** [comment]
Housekeeping: Removed the redundant `rc-blocker` tag
