### ISSUE TITLE
Investigate failure in emergency_upgrade_test_balances.sh

### ISSUE THREAD

**Issue by RitaMAllenCA** [casper-network/casper-node#4043]
Nodes are expected to have no errors in logs, yet two of them reported the "historical block should not be executed".
Link to the failed build: https://drone-auto-casper-network.casperlabs.io/casper-network/casper-node/8466/1/4.

**Comment by rafal-ch** [comment]
@RitaMAllenCA

This is not a release-blocker, as the the network was able to recover and continue operating normally.

There is a PR that should prevent errors from appearing in logs in this particular scenario.

If this test happens to fail again in the future, as an alternative to further update the control logic, we might consider loosening the asserts and allowing a single error message in the log (or reducing the log message to warn).

**Comment by RitaMAllenCA** [comment]
6.15.23 - AJ to rerun on 1.5.1 RC to see if the logs report what was addressed in the PR is what IS happening.   NO new release candidate expected either way.
