### ISSUE TITLE
Recent accident on Test-Net

### ISSUE THREAD

**Issue by matsuro-hadouken** [casper-network/casper-node#4059]
### Overview

Around `2023-06-14`, on a dedicated Telegram chat, someone reported an abnormal log size on their instance. This situation led to the expected _"no more space left on server"_ error. I was curious and asked this person to do some checks on their server.

After a couple of minutes, the issue was clear - the hardware was not properly configured. The problem was, that the nofile limit was set to default.

I did some more research on how we actually run the node process, and these lines caught my attention:

`cat /lib/systemd/system/casper-node-launcher.service | grep -A 4 Service`
```sh
[Service]
Type=simple
# Uncomment the below line to increase hard file limit from default 4096
# Note: better to edit /etc/security/limits.conf (see README.md)
#LimitNOFILE=64000
```
This is popular opinion across many devops, but practically not always works and usually doesn't, secondly, we don't have anything that alerts users to pay attention in this configuration area. There are no adjustments related to any installation scripts _(at least I can't see anything, forgive me if I'm worng)_.

Logs on these misconfigured instances grow at a speed of light, and as a result, nodes cannot operate without any space left.

### Idias on prevetion

```sh
sudo bash -c "cat >/etc/sysctl.d/20-fs-file-max.conf <<EOF
fs.file-max=600000
fs.nr_open=600000
EOF"
```
```sh
sudo sysctl -p /etc/sysctl.d/20-fs-file-max.conf
```
```sh
sudo bash -c "cat >/etc/sysctl.d/20-mmaps.conf <<EOF
vm.max_map_count = 600000
EOF"
```
```sh
sudo sysctl -p /etc/sysctl.d/20-mmaps.conf
```

* Edit `/etc/security/limits.conf`  and add before `# End of file`

```
* soft nofile 600000
* hard nofile 600000
```
Open `/etc/systemd/system.conf`

Uncomment and edit this line

`DefaultLimitNOFILE=600000`

We still need to edit `/lib/systemd/system/casper-node-launcher.service` and remove the comment on LimitNOFILE=.

Set to `LimitNOFILE=600000`

`systemctl daemon-reload`

_Nofile limits are very esoteric subject. There is a lot of debate on how they should be set and adjusted. The above information is from my personal notes and provides a 100% working solution. There can be a lot of problems removing some of these steps. If we want to be sure that required resources are dedicated to our process, this is how to do it._

Additionally, it is always a good idea to reboot the server. Even though many will advocate that the nofile limit can be set on the fly, from what I see in production, restarting is the best way to avoid any errors.

## Edit: 

As I'm running multiple nodes on mainnet and testnet for development and validation reasons, just checked one of the mainnet node and there is `casper hard nofile 64000` inside `/etc/security/limits.conf` however on testnet node which run from the genesis I didn't found anything like this. Just thoughts for now, something been configured later after genesis and on some instances it present and on some not. This need to be investigated. In any case, to provide process with required resources is not enough to edit `/etc/security/limits.conf`, it will not work. We do need to adjust this system-wide for best results as well as provide limit in systemd service config all together.

## Edit 2
64000 also is not enough to keep node safe

**Comment by RitaMAllenCA** [comment]
@rob-casper @sacherjj Please take a look so we can respond, thanks

**Comment by sacherjj** [comment]
We are not heavy handed with server configuration when installed the node as this is NOT how packages should be.  We do more things than normal, but most is server configuration.

In the docs: https://docs.casper.network/operators/
There is info on setting files limit properly: https://docs.casper.network/operators/setup/open-files/

For the TestNet even we need more data on how firewalls are configured and if this is still getting past a proper limit setting.  The solution might require putting an Nginx reverse proxy or similar to DoS/DDoS protection.

**Comment by matsuro-hadouken** [comment]
> 

On testnet, instead of Nginx, it will be more easy approach to completely filter RPC and assign to only longevity tracking services _( if they need actual RPC for score collection )_ For developers porpoise, can set up load balancer with round robin across trusted nodes or add volunteers end-points on top _( I'm aware of ongoing ufw tricks suggestions, but this doesn't looks robust enough, someone who have access to a lot of proxies can easily shut endpoint down. And there is many)_. However, before complete investigation process on why limits excite expected values, maybe just ask participants to increase numbers from 64000 to something around 300k to avoid unexpected cluster collapse. 

We run multiple RPC for Polygon, Avalanche, Etherium, Celo, Arbitrum, Optimism, Gnosis, Solana and more chains. In this servers, there is no chance to survive below 300k. As for Polygon safe numbers play around 2 millions. Better safe then sorry.

Additionally,  assume Casper Node is the only application deployed on the machine _( reasonable strategy )_, then better increase limits on all system and not a particular process it self. For example allow 100k systemwide and 80k in systemd service config, practically this ensure resources availability in any case.

Thank you !
