### ISSUE TITLE
Test the handling of unbonds in global-state-update-gen and fix it if there is a bug

### ISSUE THREAD

**Issue by RitaMAllenCA** [casper-network/casper-node#4066]
The [failure of a mainnet-clone test](https://casper-labs-team.slack.com/archives/C01ULKL8G8J/p1686900907536319) means that t[here](https://casper-labs-team.slack.com/archives/C01ULKL8G8J/p1686916818083009?thread_ts=1686900907.536319&cid=C01ULKL8G8J) is a possible bug in the global-state-update-gen tool. The possible explanation is outlined here. Write tests that will confirm or disprove this explanation and fix the bug if it is confirmed.

**Comment by real-felix** [comment]
I have written 2 tests showing there is a problem with the handling of unbonding: as Bart wrote it in the chat, when there is already an ongoing unbonding, the validator still tries to unbond the whole stake. In that case, the sum of the unbonding purses is higher than the stake.
