### ISSUE TITLE
Investigate gh_3710 EE test failure on feat-1.6

### ISSUE THREAD

**Issue by RitaMAllenCA** [casper-network/casper-node#4096]
Description: We found out feat-1.6 had another test failure in a test test::regression::gh_3710::gh_3710_commit_prune_should_delete_values . We should fix it.

**Comment by rafal-ch** [comment]
[This](https://github.com/casper-network/casper-node/commit/ac5e3955d955940d34635f6f843ea4c40b3c2484) commit seems to be causing it.
