### ISSUE TITLE
merge 1.5.3 back to dev

### ISSUE THREAD

**Issue by RitaMAllenCA** [casper-network/casper-node#4112]

**Comment by RitaMAllenCA** [comment]
@cspramit @sacherjj @mpapierski  I will be out next week, but I hope we can "do the needful" to get this release created.   It was my understanding that it would be somehow included with 1.5.2 (i.e. not from Dev).    That being said, THIS ticket will merge all changes in (1.5.3, thus 1.5.2 and 1.5.1) into dev.    We will need this complete for 1.6 so as soon as 1.5.3 is "ready" in whatever shape that takes, please prioritize this.   I will put in in the upcoming sprint.

**Comment by cspramit** [comment]
After 1.5.3 on Mainnet needs to be merged @SaiProServ

**Comment by devendran-m** [comment]
Housekeeping: Removed the duplicate/redundant `release-blocker` tag.
