### ISSUE TITLE
Extend the synced_to_ttl condition to include signature_rewards_max_delay

### ISSUE THREAD

**Issue by RitaMAllenCA** [casper-network/casper-node#4123]
Currently, a node has to have the blocks reaching at least max_ttl into the past in order to switch to Validate. This condition has to be extended, so that the node also has the knowledge of validators reaching at least signature_rewards_max_delay into the past - this is required for validating finality signatures included in proposed blocks.

**Comment by RitaMAllenCA** [comment]
@fizyk20 need an estimate

**Comment by rafal-ch** [comment]
There is an internal discussion on how to proceed with this; unable to start at the moment.
cc: @fizyk20
