### ISSUE TITLE
discovery: Implement finality signature & reconsolidate block production rewards in step

### ISSUE THREAD

**Issue by AlexanderLimonov** [casper-network/casper-node#4134]
- could loosely follow the block reward pattern already implemented in that branch

- make sure it's upstream of any slashing currently in the code

**Comment by real-felix** [comment]
Questions related to that issue:
- How is the impact of the serialization/deserialization of arguments on the time that a switch block takes to execute the distribution contract?
- Closely linked to the previous one: what is the boundary between what we compute in the component(s) and what we compute in the contract. If the serialization/deserialization of a big map is impactful, we may try and have a "boundary" with as less data passed as possible.

**Comment by real-felix** [comment]
To answer the previous question, we shall compute everything in the node components, then pass around the rewards distribution scores as a parameter. If the serialization/deserialization is too slow, we can still do something about that specific issue.

**Comment by real-felix** [comment]
While writing the algorithm, I forgot about the fact that the lookback window of a block will sometimes cover 2 different eras.

Because of that, I think I'll have to pass 2 sets of validator -> score to the reward distribution contract: one for the current era, one for the previous one. The only uncertainty is the algorithm I must use to take into account the not yet finalized signatures for an era.

**Comment by rafal-ch** [comment]
@AlexanderLimonov @fizyk20 @Boiethios 
We're waiting for the update to the design document for the updated rewards scheme.

In the meantime, Felix has figured out the solution and only needs a confirmation from Alex L.

Also, there is a regular meeting scheduled between the "consensus team", so this will be discussed on the next opportunity.

**Comment by real-felix** [comment]
As for now, the plan is that we will compute everything upfront in the node, and send a map of `PublicKey` -> `U512` to the step function, to distribute them (mint & transfer). As I see things we may split that task that way:

1. We need the total supply to compute the "reward pots". We will:
    - store the current total supply and the last 2 historical ones in the global state;
    - add a way to fetch this piece of data with a contract runtime request;
    - update this piece of data from within the step function.
    That means that we won't distribute signature rewards for more than 2 eras in the past, but such a situation where blocks cite other blocks from the 3rd era in the past should not happen anyway.
2. We don't have any historical validator data, which is used to compute the signature rewards of past eras. We need to figure out a way to retrieve them.
3. Rollback of the reward code to use the per-era distribution mechanism again, like in dev.
4. Implement the formula to transfer the full reward (including the signatures) to the step function: https://drive.google.com/file/d/1EldXEYcZR2cBLerOjSkWUJkK-CLa_atC/view?usp=drive_link

**Comment by RitaMAllenCA** [comment]
@Boiethios I will close this ticket as I captured the next steps in a different epic.
