### ISSUE TITLE
Replace muxink with juliet in feat-1.6 branch

### ISSUE THREAD

**Issue by RitaMAllenCA** [casper-network/casper-node#4137]
Use juliet instead of muxink as the underlying multiplex protocol implementation leverage by the networking component.

**Comment by marc-casperlabs** [comment]
The current tip for this is 12fcdd69f -- however, the merge may be deferred until the branch is green again.

**Comment by devendran-m** [comment]
Housekeeping: Removed the duplicate/redundant `release-blocker` tag.
