### ISSUE TITLE
Find Changes to metrics in 1.5 in addition to the ones in current changelogs

### ISSUE THREAD

**Issue by RitaMAllenCA** [casper-network/casper-node#4146]
Find Changes to metrics in 1.5 in addition to current changelogs , which involves 1) new way of using an old metric in 1.5 , breaking and non-breaking and/or 2) involves a calculation to get a value eg: Pending deploy count.
We will provide the complete list of changes to community

**Comment by alsrdn** [comment]
Summary of metrics changes for 1.5:
[Metrics changed in 1.5.csv](https://github.com/casper-network/casper-node/files/12109549/Metrics.changed.in.1.5.csv)
[Metrics removed in 1.5.csv](https://github.com/casper-network/casper-node/files/12109550/Metrics.removed.in.1.5.csv)
[New metrics added in 1.5.csv](https://github.com/casper-network/casper-node/files/12109551/New.metrics.added.in.1.5.csv)
