### ISSUE TITLE
Rename allow_unrestricted_transfers = true to restricted_transfers = false

### ISSUE THREAD

**Issue by RitaMAllenCA** [casper-network/casper-node#4164]
As follow up for https://github.com/casper-network/casper-node/pull/4109#discussion_r1265170319 discussion renaming makes it less confusing

**Comment by devendran-m** [comment]
Todo: @devendran-m - Sidebar for L1 daily

**Comment by devendran-m** [comment]
Follow-ups from the L1 Daily on 17-Sep-24;
-  Please clarify that this is a transfer between administrators and non-administrators and describe the behaviour, such as what the actual behaviour is. 
-  Describe the behaviour in detail: i.e. if it is true, what it means and if it's false what does that mean.
