### ISSUE TITLE
rename the FFI methods

### ISSUE THREAD

**Issue by RitaMAllenCA** [casper-network/casper-node#4168]
Changing the names of the methods within the FFI (runtime string bindings). This is where WASM/host exchange takes place. Also removing account specific methods and other methods (record era info) no longer relevant. Adding new methods (get immediate caller). Underlying types being invoked are renamed making this necessary. public facing changes an be listed by Fraser's tool (Karan to send info so it can be attached to this ticket)

**Comment by devendran-m** [comment]
Closed as won't do as part of review on 13th Sep.
