### ISSUE TITLE
Restructure MetaBlock to use VersionedBlock or don’t use MetaBlock for announcing historical blocks synced by the Block Synchronizer

### ISSUE THREAD

**Issue by RitaMAllenCA** [casper-network/casper-node#4177]
We use `MetaBlock` to send the synchronized block to the deploy buffer and consensus when a historical block is marked complete by the Block Synchronizer component. Since `MetaBlock` currently keeps track only of blocks created with the latest version, it can’t track a `VersionedBlock`. We can either make `MetaBlock` work with `VersionedBlock` or we can remove the usage of meta block from the Block Synchronizer and announce the block directly to the deploy buffer and consensus. Explore and implement the appropriate solution.

**Comment by alsrdn** [comment]
Implemented in https://github.com/rafal-ch/casper-node/pull/19
