### ISSUE TITLE
Extensions to the contract factory MVP

### ISSUE THREAD

**Issue by RitaMAllenCA** [casper-network/casper-node#4180]
This is a place-holder ticket for updates to the factory contract work done for the MVP.   Notes will be added as we identify additional functionality needed to support installing and calling contracts using this design pattern.

**Comment by cspramit** [comment]
add description

**Comment by devendran-m** [comment]
@mpapierski , Ed thinks the contract factory work is complete. Can we close this?

**Comment by devendran-m** [comment]
This is complete.
