### ISSUE TITLE
Implementation of a new VM for the contract runtime that will execute WebAssembly

### ISSUE THREAD

**Issue by cspramit** [casper-network/casper-node#4185]

**Comment by mpapierski** [comment]
@RitaMAllenCA @rafal-ch 

Yesterday's meeting notes:
- Good progress so far, we have basic input passing, calling exports
- On contract SDK there are macro-based exports hiding all the unnecessary boilerplate, and basic compile-time schema generator.
- There's an established convention for passing inputs (previously: named arguments "late bind" that allows you to ask for specific arg, now early bind "chunk of bytes" that you have to parse)
- Abstract key-value storage makes it possible to hook up the `casper-storage` trie.

Further steps:

- Contract Versioning is a core feature, we should keep it in the new VM
- Keep in mind backwards compatibility RuntimeArgs (we think it will work out of the box by passing serialized RuntimeArgs)
- Next, focus on creating smart contracts, and calling into smart contracts. 
- Keep in mind backward compatibility and upgrade story for 1.x contracts with regards to named keys etc.
