### ISSUE TITLE
Breaking API change: remove TransferTargetMode

### ISSUE THREAD

**Issue by cspramit** [casper-network/casper-node#4192]
As a follow up after merging https://github.com/casper-network/casper-node/pull/4109 type TransferTargetMode is unused in the codebase (superseded by a private type of similar purpose) and we should remove it before next major release of the crate

Note: plan release before next major release of casper-execution-engine

**Comment by devendran-m** [comment]
Remove TransferTargetMode enum. Rename NewTransferTargetMode to TransferTargetMode
