### ISSUE TITLE
Post 1.5.2 , dev branch joining nodes issue(ooming)

### ISSUE THREAD

**Issue by cspramit** [casper-network/casper-node#4202]
100+20 network has a change in behavior after 1.5.2 was released, where most of the non-validating joiner nodes were ooming, when using the dev branch to test

Following are the test results
Network: 100  + 20
Name: ajith-dev-big (HIGHWAY)
Branch: dev
Commit: 9b14e264fa660e4fd7492477dca00f40ebcaedfc
Config: {"config":{}, "chainspec":{"era_duration": \"60minutes\", "minimum_block_time": \"32768ms\", "consensus_protocol": \"Highway\" }}
Test: Native Transfer Load Testing
Highway Consensus
running at 32s block time
12k Native Transfers Periodically
Observations:
network behaviour has degraded since 1.5.2 release
Occasionally hitting 'Invalid Deploy' because of timestamp validation checks using casper-client 2.0.0
KeepUp nodes consuming all memory and OOMing
majority of KeepUp nodes OOMing and transitioning to 'CatchUp'
instance becomes unresponsive due to OOMing
node recovers once it re-starts
contract_runtime_run_execute_count metrics on some KeepUp nodes show extremely high count for executed deploys. (729425 (keepUp) vs 9048 (validate))
a lot of Warning/errors observed continuously
{"timestamp":"2023-08-08T06:52:58.585604Z","level":"WARN","fields":{"message":"failed to apply execution results","error":"attempt to apply execution results for already completed block_hash: block hash 6027..c015"},"target":"casper_node::components::block_synchronizer::block_acquisition"}
{"timestamp":"2023-08-08T06:41:40.469691Z","level":"WARN","fields":{"message":"BlockAcquisition: invalid attempt to register deploy for: block hash 6027..c015","deploy_id":"Id { deploy_hash: DeployHash(3d9a7a4c73eb361ec128104b61f3e4b08c9aec1b4ab23da594e03e509bd24893), approvals_hash: ApprovalsHash(7e51b6ee2a97aab4794b1e857704cb8cfc2f4a405bb8593c601b0bf3d1f8002f) }"},"target":"casper_node::components::block_synchronizer::block_acquisition"}
{"timestamp":"2023-08-08T06:41:40.455503Z","level":"WARN","fields":{"message":"invalid attempt to start block execution","block_hash":"block hash 6027..c015"},"target":"casper_node::components::block_synchronizer::block_builder"}
{"timestamp":"2023-08-08T07:07:25.442171Z","level":"WARN","fields":{"message":"dropped outgoing message, lost connection","our_id":"tls:9a0e..6171","dest":"tls:e9e6..4dca","msg":"SendError((Ping { nonce: Nonce(5719887388720792088) }, None))"},"target":"casper_node::components::network","span":{"addr":"172.142.65.140:35000","peer_id":"tls:e9e6..4dca","state":"connected","name":"outgoing"},"spans":[{"addr":"172.142.65.140:35000","peer_id":"tls:e9e6..4dca","state":"connected","name":"outgoing"}]}
{"timestamp":"2023-08-08T07:07:25.740336Z","level":"WARN","fields":{"message":"dropped outgoing message, lost connection","our_id":"tls:9a0e..6171","dest":"tls:e9e6..4dca","msg":"SendError((Payload(FinalitySignatureGossiper(Gossip(FinalitySignatureId { block_hash: BlockHash(f54923b6a917fe55bc29cb89504287941cf91684f600eb12e9b729cd8d2e9c37), era_id: EraId(5), public_key: PublicKey::Ed25519(527f461cb635a529df4bb049810d5aa1642752b9c7a91aec3749f050487bbc87) }))), None))"},"target":"casper_node::components::network"}
Dumps:  http://genesis.casperlabs.io/ajith-dev-big/casper-node-dumps/ajith-dev-big/08082023_0707/dump_download_list.html
Grafana: - https://grafana.casperlabs.io/d/NtiRElLMg/release-test-metrics-overview-v3-1?orgId=1&refresh=30s&var-casper_environment=ajith-dev-big&var-casper_version=casper-ajith-dev-big&var-casper_node_type=All&var-casper_hostname=All&from=1691467983241&to=1691478783241

**Comment by alsrdn** [comment]
Should be fixed now by: https://github.com/casper-network/casper-node/pull/4205
