### ISSUE TITLE
Retrieve historical validator data

### ISSUE THREAD

**Issue by RitaMAllenCA** [casper-network/casper-node#4224]

**Comment by fizyk20** [comment]
I think this issue was about implementing a way of retrieving historical validator data - which no longer makes sense, now that we realized we can just use state root hashes from past blocks. It might not be relevant anymore because of that.

**Comment by RitaMAllenCA** [comment]
will be done as part of #4226https://app.zenhub.com/workspaces/engineering-l1-60953fafb1945f0011a3592d/issues/gh/casper-network/casper-node/4226
