### ISSUE TITLE
Add TrackingMap to make Arc/Weaks used more robust

### ISSUE THREAD

**Issue by RitaMAllenCA** [casper-network/casper-node#4232]
In some places in the node we currently shuffle Arcs and Weaks around, with manual cleanup. This functionality, if not replaced, should be replace with a tested data structure that tracks these things by itself and ideally removes the Weak on Drop, or garbage collects them when prompted.

**Comment by marc-casperlabs** [comment]
This has been made obsolete with the addition of the new connection manager.
