### ISSUE TITLE
Remove its03 and it11 from the commit tests runs

### ISSUE THREAD

**Issue by RitaMAllenCA** [casper-network/casper-node#4235]
remove the named tests in this directory: [utils/nctl/sh/scenarios-upgrades](url) from commit tests 
after [https://github.com/casper-network/casper-node/issues/4234](url) is determined

**Comment by rafal-ch** [comment]
By the fact that there is the `scenarios_upgrades` directory mentioned, I assume we're referring to `upgrade_scenario_3.sh` and `upgrade_scenario_11.sh`. These two are currently disabled on `feat-2.0` by [this commit](https://github.com/rafal-ch/casper-node/commit/3be057c46ffa9a2f43d7a4dd52380e8cf1fba580) as part of [this PR](https://github.com/casper-network/casper-node/pull/4196).

I'd rather keep them commented for now, as we might reconsider re-enabling them as per https://github.com/casper-network/casper-node/issues/4234
