### ISSUE TITLE
Fix validator broadcast efficiency in feat-1.6

### ISSUE THREAD

**Issue by RitaMAllenCA** [casper-network/casper-node#4247]
The validator broadcast based on the ValidatorMatrix in feat-1.6 is currently not fixed and was recently tested with a workaround, causing the broadcast to reach all nodes:
rust
      for peer_id in self.outgoing_manager.connected_peers() {
            total_outgoing_manager_connected_peers += 1;

            if !self.validator_matrix.has_era(&era_id)
                || self.outgoing_limiter.is_validator_in_era(era_id, &peer_id)
            {
                total_connected_validators_in_era += 1;
                self.send_message(peer_id, msg.clone(), None)
            }
        }
(in the workaround, the if condition is prefixed with true ||)
The root cause for this code not working is that it does not check adjacent eras (past and future), causing it to break during switch blocks.
The code needs to be reexamined and reengineered to efficiently send at least to current and previous era validators, as well as potential future validators, all without introducing quadratic copies of validator IDs on every message send.

**Comment by marc-casperlabs** [comment]
The feature (selecting nodes based on their validator status) needs to be cleanly readded to the networking component, quick fixes are not going to cut it here.
