### ISSUE TITLE
Fix potential arithmetic overflow during highway rewards calculation

### ISSUE THREAD

**Issue by RitaMAllenCA** [casper-network/casper-node#4283]
There is a potential for arithmetic overflow at [https://github.com/casper-network/casper-node/blob/f7d8228de3cb56a3fe705f5a787d3db[…]/components/consensus/highway_core/finality_detector/rewards.rs](https://github.com/casper-network/casper-node/blob/f7d8228de3cb56a3fe705f5a787d3dbf03ff7998/node/src/components/consensus/highway_core/finality_detector/rewards.rs#L73) if the quorum weight is u64::MAX.  This can happen if e.g. we have two stakes of a*u64::MAX and b*u64::MAX where each stake is divisible by a+b.  Examples of pairs for a and b are (514, 771) or (668, 614).

**Comment by devendran-m** [comment]
Housekeeping: Removed the duplicate/redundant `release-blocker` tag.
