### ISSUE TITLE
Fix query_balance JSON-RPC

### ISSUE THREAD

**Issue by RitaMAllenCA** [casper-network/casper-node#4284]
This RPC needs to be updated after the AddressableEntity changes, since the request fails if a public key or account-hash is provided.  This is due to the RPC server expecting an account to be stored under Key::Account whereas for recent global state, it is actually a pointer to an AddressableEntity

**Comment by devendran-m** [comment]
Housekeeping: Removed the duplicate/redundant `release-blocker` tag.
