### ISSUE TITLE
Investigate Highway exponent step down sensitivity 

### ISSUE THREAD

**Issue by RitaMAllenCA** [casper-network/casper-node#4288]
Joe to provide information to start the investigation.   Highway is designed to address low performing nodes by metaphorically moving them to a slower lane.   It would appear this is happening, but not as effectively as it could.   Please review and provide information. 

The objective is to increase confidence that the network is sufficiently self-healing or if a tweak is necessary

**Comment by fizyk20** [comment]
Findings: the algorithm for changing the round exponent seems to be too dependent on the performance of the network as a whole, as opposed to individual performance of the nodes. We might need to tweak it, but first we need to have adequate test coverage for the behavior of the nodes in this regard. This is now captured as #4306 and #4307 .
