### ISSUE TITLE
Part Deux: Design & implement unit + reactor-style tests for finality signature payload tracking & validation

### ISSUE THREAD

**Issue by RitaMAllenCA** [casper-network/casper-node#4289]
Split up the ticket into two or more parts (unit, end-to-end) if necessary

Taking into account that this is likely to roll since issues found with mainnet after 1.5 take priority

**Comment by rafal-ch** [comment]
@fizyk20 @Boiethios please specify the test scenarios for the new rewards that we want to implement as a part of this ticket.
