### ISSUE TITLE
The 1.5.3 upgrade took longer than expected and hung after the immediate switch block for some time

### ISSUE THREAD

**Issue by SaiProServ** [casper-network/casper-node#4308]
Slow startup of DB was observed:

{"timestamp":"2023-09-28T14:37:27.897899Z","level":"INFO","fields":{"message":"initializing block metadata database"},"target":"casper_node::components::storage"}
{"timestamp":"2023-09-28T14:43:31.623125Z","level":"INFO","fields":{"message":"block metadata database initialized"},"target":"casper_node::components::storage"}

**Comment by cspramit** [comment]
Are we fixing this in 1.5.3?
