### ISSUE TITLE
1.5.4 test unspent fund scenarios 

### ISSUE THREAD

**Issue by cspramit** [casper-network/casper-node#4353]
( we may need to write unit tests)
For the release of 1.5.4 - we need to ensure via tests that the unspent funds are refunded to users via a setting in the configurations
- Test boundaries of the configuration setting, as in 0 - 50 -100 % refund and assert the correct amount is refunded
- Test the setting when the user does not have any eligible refunds to start with
Scenarios to test are not limited to above

**Comment by rafal-ch** [comment]
As explained by @MParlikar:
"_Let's set the refund to 99%_"
