### ISSUE TITLE
Assess possible upgrade path for wasmi 0.31.0+

### ISSUE THREAD

**Issue by SaiProServ** [casper-network/casper-node#4366]
We’re stuck to 0.13.2 (called “rock solid” release by Parity) and invested lot’s of resources into patching related parity crates that are left unmaintained otherwise. Newer versions (0.14.0) have completely different API, may have unexpected side effects, but it is about time we should assess upgradability of it. 

Benefits: supports multiple widely used Wasm extensions out of the box, should be noticably faster (recently register based ISA is merged), doesn’t require gas injector anymore (has “fuel consumption” API). And most importantly it should be safer as it’s using a proper Bytecode Alliance’s maintained parser, rather their (buggy) inhouse one. Other benefits may include possible retiring our forks of all parity crates.

Outcome of this ticket should be a list of tasks to be done to allow for smooth transition to new Wasmi.

**Comment by rafal-ch** [comment]
Decision to be made if this is 2.0.

**Comment by cspramit** [comment]
@rafal-ch @mpapierski can target this for 1.6, as it is asses, if it is a smooth one we can include in 1.6 and if not then push it for a later release than 1.6

**Comment by cspramit** [comment]
Ask @Ed

**Comment by SaiProServ** [comment]
Closed as per the last meeting between Ed, Michal, Sai, Alex S and Mo.
