### ISSUE TITLE
Add new communication endpoint to node- RPC Sidecar

### ISSUE THREAD

**Issue by SaiProServ** [casper-network/casper-node#4389]
Node should be able to serve raw data from storage.

**Comment by rafal-ch** [comment]
Requirements:
* Binary protocol for speed and possible avoidance of reserialization
* Binary protocol as a hint that the interface is not for general consumption
* Allow "raw" reading, client is responsible for implementing "higher level" read operations
  * for example: there's not gonna be a "GetBlock" operation, client will need to ask node for all the details it needs to provide external caller with the block data (block header, transfers, etc.)
* Writing limited to: put_deploy (put_transaction) - no "raw" writing, hence no risk of corruption of the data
* Speculative execution "service"
* Backpressure (per client, allow fixed number of requests at a time + allow for limited number of clients)
* Access control is on the IP level

cc: @marc-casperlabs @Fraser999

**Comment by rafal-ch** [comment]
Node side:
* [x] Juliet server in node (mvp)
* [x] Add some kind of connection limiter
* [x] Respect config
* [x] Add metrics
* [x] Take care of `node_startup_instant`
* [x] Cover with tests
* [x] Support queries that are handled by in-memory data, not storage (/status, /peers, ...)
* [x] Support `PutTransaction` and `PutDeploy`
* [x] Support `GetAuctionInfo` request which accesses the tracking copy

Sidecar side:
* [x] Extract RPC interface from node to sidecar
* [x] Rip RPC from node
* [x] Sidecar needs to use juliet instead of `effectbuilder`
* [x] Work on a single RPC call (get_deploy) / fix issues and edge cases
* [x] Continue with other `Get` endpoints
* [x] Add support for `put_transaction` & `speculative_exec`
* [x] Support for legacy (bincode-encoded) data - cover with test
* [ ] Update `GetAccountInfo` (deprecate and change to `GetAddressableEntityInfo` or smth)

**Comment by rafal-ch** [comment]
Regarding the in-memory data that is used in the RPC queries, here's the summary from @jacek-casper: https://gist.github.com/jacek-casper/9dce32c2e4b0282efd497f6e7abffaba

**Comment by rafal-ch** [comment]
Updated todo list:
* [x] support binary port config
* [x] add metrics
* [x] implement event system in binary port component
* [x] add some kind of connection limiter
* [x] add bytesrepr tests
* [x] add tests coverage
* [x] cleanup (especially, remove all remaining references to RPC server from node docs, comments, etc.)
* [x] update changelog
* [x] update NCTL and `casper-test` to use sidecar
* [ ] Review types moved to `casper-types` - maybe we don't want to expose all of them and can find some alternative representation
* [x] Support fallback to legacy DB
* [ ] Fix `GetAccountInfo` (it's not working on `feat-2.0`: `Account` -> `AddressableEntity`)
* [x] Fix `GetAuctionInfo` requests
* [x] Implement `info_get_trie` in sidecar
* [x] move `sidecar_module` to event stream sidecar (integrate with ecosystem team)
* [x] Versioning of RPC protocol (separate from node protocol version, can stay as semver, but it can be a single integer as well)
* [x] fix `casper-test` issue related to "early block return"

Additional TODOs after the first review meeting:
* [x] Response should be enveloped and self-describing - it should contain the copy of the request, payload type and error information
```
// Something like...
enum PayloadType {
    GetX,
    GetY,
    BlockV1, // Versioning
    BlockV2,
    TryAccept,
    Etc,
    Error,
}

struct BinaryResponse {
    request: BinaryRequest,
    payload_type: PayloadType,
    payload: Vec<u8>,
}
```
* [x] `AllValues` and `Trie` variants of `GetRequest` should be disabled by default (via appropriate config settings)
* [ ] `completed_blocks` vs `complete_blocks` - use consistent naming (across the node, not only binary port)
* [x] Each request that take a block as an input should use `BlockIdentifier` and not be limited to either `BlockHeight` or `BlockHash`
* [x] Add a `Status` request that will deliver all data needed for the `/status` endpoint at once
* [x] NCTL, casper-test **and** casper-client-rs should talk to sidecar in the initial release - then we can consider modifying them to talk directly to the binary port
* [x] Rework `TrySpeculativeExec` and `TrySpeculativeExec` - speculative execution should require only a single call to `TrySpeculativeExec` (unlike right now, when it first needs to do `TrySpeculativeExec`. 
* [x] Create new "upgrade scenario" to test upgrade from a node without sidecar
* [x] Create test that verifies that RPC sidecar is able to process legacy data (pre 1.5)
* [x] BinaryRequest two-pass parse
* [ ] Proptest for `TryAcceptTransaction` and `TrySpeculativeExecution`
* [x] Write binary protocol specification
* [x] bytesrepr roundrip tests
* [x] component tests for `Db`, `TrySepculativeExec` and `TryAcceptTransaction`
