### ISSUE TITLE
Production Issue 

### ISSUE THREAD

**Issue by SaiProServ** [casper-network/casper-node#4391]
Production Issue

Reported by : Jiuhong [here](https://casper-labs-team.slack.com/archives/CDXBCHB6W/p1698202048912619)

A user reported a strange behavior for this account.
It redelegated all the stake from 2 different validators to 1 new validator.
https://cspr.live/deploy/2711052308f14d784a265db2c8d9cd1948d5620b39c997126a46b9180a781330
https://cspr.live/deploy/1803906f8987900dae08582b438d1b075bface503bb8d0d9ccaaed541a97ddbd
But one of the old validators(Speedy Staking) still kept some stake (1222973704 motes) and continuously got rewards.
In contrast, the other old validator has no such phenomenon .
What is the reason please?

The user is back with the following info:
Here are all details on 1 page so hopefully someone will investigate this in more detail please because the reply and also the on-chain data doesn't make sense to me: 
# Public Key using 2x the redelegate feature within the same era and both previous validators having the same commission rate of 3%:
010c8d605867276b07b425f357ab50488d5e8d66361e13e7e9998192e85fa3df69

# Era first block - switch block:
2_157_896 - 2_158_113

# Deploy 1 (NO dust):
https://cspr.live/deploy/2711052308f14d784a265db2c8d9cd1948d5620b39c997126a46b9180a781330

# Timestamp:
2023-10-23T18:44:15.664Z

# Block Hash:
https://cspr.live/block/4f53b77f82c1f0d46f19dd6f775c72ea540df96dd3bbf9118c2e7f94978bed71

# Block (Era):
2_158_031 (11216)

# Amount in previous era 11215/:
8_645_630_786_826 (~8645 CSPR))

# Amount Redelegated (slightly higher than in the previous era above!):
8_645_824_663_842 (~8645 CSPR)

# Delta (1 reward?):
193_877_016

# Old Validator (Ghost Staking, 3% Commission Rate):
01c60fe433d3a22ec5e30a8341f4bda978fa81c2b94e5a95f745723f9a019a3c31

# New Validator (Casper Delegation):
01c377281132044bd3278b039925eeb3efdb9d99dd5f46d9ec6a764add34581af7

### SECOND DEPLOY ###
# Deploy 2 (~3.66 CSPR dust, which looks like 3x rewards):
https://cspr.live/deploy/1803906f8987900dae08582b438d1b075bface503bb8d0d9ccaaed541a97ddbd

# Timestamp:
2023-10-23T18:42:56.032Z

# Block Hash:
https://cspr.live/block/c6a520f317c7b9781e48b73966d5d37ead6e09b140beae8c112feaed17be32ce

# Block (Era):
2_158_029 (11216)

# Amount in previous era 11215:
54_536_526_958_794 (~54536 CSPR)

# Amount Redelegated (identical to previous amount):
54_536_526_958_794 (~54536 CSPR)

# Delta:
0

# Old Validator (Speedy Staking, 3% Commission Rate)):
0111b3519efa63942e57a9470f55b62d9c4a59ff44df7c65eaefbd1489b7a93a5b

# New Validator (Casper Delegation):
01c377281132044bd3278b039925eeb3efdb9d99dd5f46d9ec6a764add34581af7
I just discovered something interesting: I've also looked up the amounts in the previous era from the Auction-Info and added them above. The deploy without dust had a different stake than the redelegated amount. That makes it even more weird because the other deploy has the dust, not that one. Could the following scenario have an effect: 
User goes to cspr.live, looking up his stuff, logging in, going to redelegate but is NOT signing it yet
He drinks coffee, answers 2 phone calls, maybe navigates around on cspr.live in another tab
15 minutes later he is signing his already initiated redelegate -> more blocks, maybe even a new era
Can anyone take a look and help explain?

**Comment by devendran-m** [comment]
Housekeeping: Removing the automated sprint assignments.

**Comment by devendran-m** [comment]
Reviewed in sprint planning on 30/10/24 and closing it.
