### ISSUE TITLE
Fixing a bug in the rewards calculation

### ISSUE THREAD

**Issue by cspramit** [casper-network/casper-node#4410]
There is a bug in the rewards implementation where the last block (the one being currently executed) isn't taken into account.

**Comment by fizyk20** [comment]
This has been fixed back in #4400, in commit bc16bef36ca8935b13477fd2a1258a4f14b8d794

**Comment by devendran-m** [comment]
Housekeeping: Removed the obsolete `release-blocker` tag and added the correct `release blocker` tag.
