### ISSUE TITLE
in_flight counter sometimes attempts to drop below 0 in BlockValidator

### ISSUE THREAD

**Issue by cspramit** [casper-network/casper-node#4413]
When fetching finality signatures that are cited in a block, the BlockValidator keeps count of the requests that are in flight, in order not to declare the block invalid prematurely. We observed attempts to decrease this counter even when it hits 0. We should find a reason for that and fix it

**Comment by fizyk20** [comment]
No longer relevant with the changed `BlockValidator` on `feat-2.0`.
