### ISSUE TITLE
Second VM: calling contracts part 2

### ISSUE THREAD

**Issue by cspramit** [casper-network/casper-node#4424]
With #4248 new host functions were introduced with a new method of passing a “manifest” from wasm to host. Need to still continue work on calling already stored contracts.

**Comment by mpapierski** [comment]
- casper_create -> Maybe upgrade can be merged into create
- casper_call -> call smart contract aka the entity
- casper_transfer -> transfer of tokens to an account

**Comment by rafal-ch** [comment]
Closing now, follow-up tickets have been created:
* https://app.zenhub.com/workspaces/core-protocol-60953fafb1945f0011a3592d/issues/gh/casper-network/casper-node/4450
* https://app.zenhub.com/workspaces/core-protocol-60953fafb1945f0011a3592d/issues/gh/casper-network/casper-node/4451
* https://app.zenhub.com/workspaces/core-protocol-60953fafb1945f0011a3592d/issues/gh/casper-network/casper-node/4452
* https://app.zenhub.com/workspaces/core-protocol-60953fafb1945f0011a3592d/issues/gh/casper-network/casper-node/4453
* https://app.zenhub.com/workspaces/core-protocol-60953fafb1945f0011a3592d/issues/gh/casper-network/casper-node/4454

cc: @SaiProServ
