### ISSUE TITLE
juliet violates single-multiframe-transfer by not holding large messages long enough

### ISSUE THREAD

**Issue by SaiProServ** [casper-network/casper-node#4436]
The “final boss” test run at https://drone-auto-casper-network.casperlabs.io/casper-network/casper-node/9706/1/4 revealed multiple failures with the following error.
{"message":"connection dropped","err":"error sent to peer: 86040300"}
According to the RFC, error code 06 is
6    IN_PROGRESS    A new request or response was sent without completing the previous one
This should not happen under normal operation and is indicative of a bug in the library. This needs to be replicated and fixed (and the Display for Header impl made to be more readable).

**Comment by marc-casperlabs** [comment]
The problem has no longer occured since `juliet` release `0.2.1`, neither in SRE testing nor in the nightly torture test.
