### ISSUE TITLE
Fix panic in performance meter

### ISSUE THREAD

**Issue by SaiProServ** [casper-network/casper-node#4444]
There is a failed nightly test run ([link](https://drone-auto-casper-network.casperlabs.io/casper-network/casper-node/9719/1/4)). The failure reason is a node-1 crashing due to out-of-bounds panic in performance meter.

**Comment by fizyk20** [comment]
This is fixed by #4441

**Comment by devendran-m** [comment]
Housekeeping: Removed the obsolete `release-blocker` tag and added the correct `release blocker` tag.
