### ISSUE TITLE
Check exertion of chunked transfers in large deploy transfer test

### ISSUE THREAD

**Issue by SaiProServ** [casper-network/casper-node#4448]
The test found in join_with_big_trie.rs has recently been fixed to actually test the condition it is supposed to test, it was giving false positives before. However, ultimate verification still relies on manual log reading.
The functionality should be enhanced to determine the outcome from the logs automatically, similar to how it is done in network_soundness.py.

**Comment by rafal-ch** [comment]
PR: https://github.com/casper-network/casper-test/pull/145
