### ISSUE TITLE
Add missing test cases for a map type in the deploy generator

### ISSUE THREAD

**Issue by SaiProServ** [casper-network/casper-node#4455]
Need to add a few test cases for a map type here [(https://github.com/casper-ecosystem/casper-deploy-generator/blob/98f4b13194c5cbe89177b579e2b5277eda1a5c3f/src/test_data/generic.rs#L118)]

**Comment by mpapierski** [comment]
Code: https://github.com/casper-ecosystem/casper-deploy-generator/pull/66

**Comment by devendran-m** [comment]
Housekeeping - Moving it to new issues for triage.

**Comment by devendran-m** [comment]
Michal confirmed that this issue is addressed by the deploy generator PR [#66](https://github.com/casper-ecosystem/casper-deploy-generator/pull/66). Therefore closing it.
