### ISSUE TITLE
Increase configurability of networking layer

### ISSUE THREAD

**Issue by SaiProServ** [casper-network/casper-node#4457]
Currently, a lot of possible tweaks in the networking layer configuration are hardcoded. Specifically, all values used in create_rpc_builder are fixed, this should be changed at least as follows:
Channel configuration of in-flight limits should use a one-size fits all, but instead allow configuration on a per-channel basis (for with_request_limit). This needs to be *chainspec* value, as mismatched values will otherwise result in a peer ban.
Similarly, the value passed to with_default_buffer_size should be configurable on a per-channel basis, although these should be configuration values, not chainspec ones.
max_in_flight_demands should as a result be removed from the networking configuration.
maximum_net_message_size should be replaced by per-channel values and split into request/response as well, also supplied via chainspec, for the same reasons as above.
max_incoming_message_rate (from network::config::Config) should probably be removed

**Comment by marc-casperlabs** [comment]
Updating this to reflect also the finding of boundary values for message sizes, which are required.
