### ISSUE TITLE
Merge sidecar binaries into one

### ISSUE THREAD

**Issue by SaiProServ** [casper-network/casper-node#4497]
The sidecar binaries were separated soon after a PR was opened in the event-sidecar repo, but the original plan was to distribute event stream and RPC sidecar as a single binary, so the PR should be adjusted to build a single binary instead of two. This will involve changing the app entry-point and merging the configs.

**Comment by jacek-casper** [comment]
implemented in https://github.com/zajko/event-sidecar/pull/6

**Comment by jacek-casper** [comment]
the underlying changes have been merged into the main sidecar pull requests:
https://github.com/CasperLabs/event-sidecar/pull/231
https://github.com/casper-network/casper-node/pull/4491
