### ISSUE TITLE
Improve switch block reporting

### ISSUE THREAD

**Issue by SaiProServ** [casper-network/casper-node#4504]
Two complementary changes:

1. Add field to status for last_switch_block_hash, which for a given node displays the block hash of the switch block for that node's local tip.

2. Era summary info request / response currently requires the caller to provide the block hash of a switch block to function properly. if no block hash is provided, it gets local tip and reports the era summary from that block...however that field is only populated on switch blocks. instead, if no block hash is provided it should use the block hash of the switch block of that node's local tip which does contain the desired info.

**Comment by cspramit** [comment]
needs to be included in a sprint @SaiProServ
