### ISSUE TITLE
High frequency of warnings in test run

### ISSUE THREAD

**Issue by SaiProServ** [casper-network/casper-node#4505]
The 1.6 branch is currently showing a lot of warnings, specifically:

`BlockSynchronizer: global state sync is processing another request`

A run from 2024-01-23 had 57830 warnings, with > 99% of these being those specifically.
Either this is normal operation and the warning frequency needs to be reduced, or an assumption in the syncing code has been invalidated and it needs to be updated.

**Comment by marc-casperlabs** [comment]
Note: This is not a 1.6 issue, the problem has been present in 1.5 before as well: https://casper-labs-team.slack.com/archives/C01ULKL8G8J/p1695876773605519
