### ISSUE TITLE
Part 2 : Update Gossipers

### ISSUE THREAD

**Issue by SaiProServ** [casper-network/casper-node#4512]
- The current FinalitySignature struct should be renamed to FinalitySignatureV1
- We should provide a new FinalitySignatureV2 struct being similar to the first one, but with the following changes:
- add field block_height: u64 immediately after block_hash
- add field chain_name_hash: ChainNameDigest immediately after era_id, where ChainNameDigestis a newtype wrapper of Digest (similar to BlockHash) and is the hash of chain name (serialized via ToBytes) as specified in chainspec.network_config.name
- change the bytes to sign over to (&self.block_hash, self.block_height, self.era_id, &self.chain_name_hash).to_bytes()
- FinalitySignature should be updated to an enum with V1 and V2 variants, each wrapping the appropriate struct
- ensure FinalitySignature::random and ::random_for_block are updated to produce a V1 or V2 type with 50% probability
- mirror these changes for the BlockSignatures type
- update Storage to handle this by changing block_metadata_db to be a VersionedDatabases<BlockHash, BlockSignatures>
- ensure validators when creating new signatures are only producing FinalitySignatureV2 type by updating ValidatorMatrix::create_finality_signature to return Option<FinalitySignatureV2>

**Comment by jacek-casper** [comment]
implemented in this PR: https://github.com/casper-network/casper-node/pull/4517

**Comment by jacek-casper** [comment]
this has been approved, but not merged yet due to build issues on feat-2.0
