### ISSUE TITLE
Extend binary protocol with GetSignedBlock, GetBlockHeader and GetTransaction requests and some refactoring

### ISSUE THREAD

**Issue by SaiProServ** [casper-network/casper-node#4520]
- add an envelope type for GetRequest that has a type tag that can be parsed independently of the body
- multiple changes to GetRequest
  - get rid of the concept of a Db in the protocol, instead name it Record
  - change request categories to
    - Information which would contain existing NonPersistedDataRequest and a few additional requests, all of which would be used in the sidecar instead of existing logic:
      - GetBlockHeader thats gets just a header by BlockIdentifier
      - GetSignedBlock that retrieved a complete SignedBlock by BlockIdentifier
      - GetTransaction that retrieves a transaction with approvals and execution info by TransactionHash
    - Record which would contain existing Db requests
    - State which would contain existing State, AllValues and Trie requests
    - all requests that deal with the global state should accept GlobalStateIdentifier

**Comment by jacek-casper** [comment]
Implemented in 2 PRs:

https://github.com/jacek-casper/casper-node/pull/17
https://github.com/zajko/event-sidecar/pull/15

**Comment by jacek-casper** [comment]
These have been merged into main sidecar branches, any further reviews will happen there:
https://github.com/casper-network/casper-node/pull/4491
https://github.com/CasperLabs/event-sidecar/pull/231
