### ISSUE TITLE
Joining nodes have intermittent connection issues

### ISSUE THREAD

**Issue by SaiProServ** [casper-network/casper-node#4525]
As of now, in 5+2 network settings, joining nodes (and only those apparently) seem to erroneously assume an error in the outgoing connection, causing a termination and reconnection. This is turn is causing a lot of already buffered messages to be discarded, which results in slow or failed joins.

This is prominent in 1.6, but the underlying problem seems to have been introduced in 1.5, possibly earlier already, as we are seeing some reports of this in testnet during load testing.

**Comment by marc-casperlabs** [comment]
This will hopefully be addressed in a80dab68e and onwards.

**Comment by marc-casperlabs** [comment]
Seems to be fixed with the new conman implementation.
