### ISSUE TITLE
Block header reception incorrectly subject to per-peer rate limiting

### ISSUE THREAD

**Issue by SaiProServ** [casper-network/casper-node#4533]
The block synchronizer imposes a rate limit for received block headers per peer which unfortunately is also engaged during historical syncing. As a result, the forward sync can be blocked by too much progress being made from the same peer during backwards syncing.

The warning exhibited in this case is
- rejecting block hash from peer who sent us more than 6 within 1m

The likely fix is to not run historically synced blocks past the rate limiter and block accumulator.

This bug is likely present both in 1.6 and 1.5.

**Comment by marc-casperlabs** [comment]
After further discussion, the consensus is to remove the rate limiting from the block synchronizer altogether, letting networking level mechanisms protect against spam attacks.
