### ISSUE TITLE
An operator reported finalization time spikes on mainnet.

### ISSUE THREAD

**Issue by SaiProServ** [casper-network/casper-node#4541]
Original report received from the operator.

"Ever since 1.5.6 went live on mainnet, I've seen weird reward degradation on our (and other's) nodes."

I can also see finalisation spikes outside of ERA switches. This behaviour is only visible on our 2 mainnet nodes, not on our testnet node.

**Comment by fizyk20** [comment]
Closing as the issue was due to an underperforming node.
