### ISSUE TITLE
CSPR Burning feature

### ISSUE THREAD

**Issue by SaiProServ** [casper-network/casper-node#4548]
Node enhancement proposal to enable native token burning feature.  The proposal objective is to make the existing internal CSPR token burn mechanism accessible to Smart Contract developers to let our community limit the Total Supply of CSPR tokens. This will allow us to introduce the deflationary mechanism to Casper Network.
Please find the detailed proposal in the CEP request [here](https://github.com/casper-network/ceps/pull/92/files)

**Comment by devendran-m** [comment]
The linked PRs are;
https://github.com/casper-network/casper-node/pull/4573
https://github.com/casper-network/casper-node/pull/4640
And the related CEP is https://github.com/casper-network/ceps/pull/92

**Comment by devendran-m** [comment]
Completed, therefore closing.
