### ISSUE TITLE
Cleanup configuration for networking in 1.6

### ISSUE THREAD

**Issue by SaiProServ** [casper-network/casper-node#4554]
The node networking configuration needs to be updated, as it has changed significantly in capabilities with the introduction of conman.
This change should be made to the conman branch (see #4551).
Should include configurability for conman and juliet parameters (as long as they are not required to be part of the chainspec) and include a method turning ACK-bubbling on and off.

**Comment by marc-casperlabs** [comment]
This has been completed and merged in https://github.com/marc-casperlabs/casper-node/pull/9 and  #4607
