### ISSUE TITLE
Update metrics to include conman and juliet related metrics and diagnostics

### ISSUE THREAD

**Issue by SaiProServ** [casper-network/casper-node#4556]
The two new networking parts are not well reflected in the networking metrics as-is. Specifically, since the number of pending requests is bounded by juliet itself, the additional memory buffer that exists as a temporary measure until post 1.6 needs to be measured instead. Another good thing to add is a histogram of ACK times.

Additionally, some information on how conman operates should be added, also reflected in metrics as well as the diagnostics port.

**Comment by marc-casperlabs** [comment]
The diagnostics ports changes are already added.
