### ISSUE TITLE
Close connection on ban

### ISSUE THREAD

**Issue by SaiProServ** [casper-network/casper-node#4559]
The conman branch (see #4551) currently lacks the capability to terminate an active connection, making bans severely lack in bite.

To add this functionality, the juliet RPC interface will need to be extended to allow for clean error injection on the JulietRpcClient. The io layer should have this capability already, so it is hopefully only a matter of exposing it.

**Comment by marc-casperlabs** [comment]
PR open at https://github.com/marc-casperlabs/casper-node/pull/11

**Comment by marc-casperlabs** [comment]
Done as of https://github.com/casper-network/casper-node/pull/4604
