### ISSUE TITLE
The DeployConfig chainspec setting for max dependencies should be removed along with all mentions of same.

### ISSUE THREAD

**Issue by SaiProServ** [casper-network/casper-node#4567]
Deploy dependencies are not supported (they were not supported earlier as well), and legacy deploys citing dependencies are no longer considered valid. 

The deploy header is a valid function and has been changed to the following:

<img width="1031" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNVdXQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b4cfeaf0e205480550b1e8f3128ef4644b000675/image%20%281%29.png" alt="image (1).png" />

The excessive dependencies error variant has been changed to this:

<img width="1287" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNWVXQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--766158de287b6099be880edae52496061a6153de/image%20%282%29.png" alt="image (2).png" />

**Comment by devendran-m** [comment]
Karan to describe and check for volunteers.
