### ISSUE TITLE
Add a test validating a block without any deploys, but with a signature that cannot be fetched

### ISSUE THREAD

**Issue by SaiProServ** [casper-network/casper-node#4571]
There is a potential bug in BlockValidator on feat-2.0 that will incorrectly declare a block with missing signatures valid if it contains no deploys. Add a test exercising this scenario, and fix the bug if the test fails.

**Comment by fizyk20** [comment]
The test was introduced in a7da1d016c643d190f3cf2229004c4f399d39bee and included in `feat-2.0` in 9e94ec302eb337952bad870689620ab7e2062ff6
