### ISSUE TITLE
Fix Juliet test

### ISSUE THREAD

**Issue by SaiProServ** [casper-network/casper-node#4575]
The test run_large_volume_test_with_default_values_10_channels fails on the error-log branch (see e.g. [this CI run](https://github.com/casper-network/juliet/actions/runs/8086642836/job/22096837971))

**Comment by marc-casperlabs** [comment]
A subset Fraser's changes sufficient to fix the issue has been merged in https://github.com/casper-network/juliet/pull/8, and subsequently `juliet` 0.3 was released.
