### ISSUE TITLE
Review max_request_size_bytes and max_response_size_bytes binary port config

### ISSUE THREAD

**Issue by SaiProServ** [casper-network/casper-node#4580]
The request and response sizes are hardcoded in the binary port to 4 megabytes.

It is necessary to come up with a better limit based on the size of actual messages.

**Comment by devendran-m** [comment]
Hi @zajko , As advised by Ed in the backlog review on 13th Sep, assigning this issue to you.

**Comment by devendran-m** [comment]
Per the offline triage with @zajko , the requirement specified in this ticket will be covered in https://github.com/casper-network/casper-node/issues/4629. Therefore closing 4580.
