### ISSUE TITLE
Joiner issue for 1.6

### ISSUE THREAD

**Issue by cspramit** [casper-network/casper-node#4586]
Network: 100  + 20
Name: ajith-dev-big (16s)
Branch: feat-1.6
Commit: dece69dcc00037b0c2be385081743ea284e3a4b2
Config: '{"config":{}, "chainspec":{"era_duration": \"30minutes\"}}'
Genesis: feat-1.6 (dece69dcc00037b0c2be385081743ea284e3a4b2)
Test: Release Candidate Testing
Mixed Load - CEP78, Delegation, Un-delegation, Bid, Withdraw, Multi-sig
Native Transfers
Multiple Upgrades
Sync_to_Genesis and Sync_to_TTL Joining Nodes
Node Restarts
Deploy Cost Refund Validation
Large CEP78 Contract and Mint Deployments
Large CEP78 mints (same deploy_hash) and large wasm transfers(diff deploy_hash)
Observations:
network stable throughout
multiple 30k native transfers
nodes looking healthy with no impact on finalisation times
650 transfers per block
multiple wasm transfers
25 deploys per block
run multiple CEP78, Multi-Sig, Add Bid, Remove Bid WASM
successful execution as expected
joiner nodes successful
9 sync_to_ttl
1 joiner node failed to initialise from start
"message":"fatal error via control announcement","file":"node/src/reactor/main_reactor/utils.rs","line":"23","msg":"network failed to initialize"
20 sync_to_genesis
all nodes sync through to genesis
warnings and counts on joiner
a lot of "BlockAcquisition: invalid attempt to register deploy for: block hash f623..b18a"
a lot of "cannot register un-stored deploy(deploy-id(deploy-hash(317a..6a63), approvals-hash(b1bf..9cd7)))"

Dump - [http://genesis.casperlabs.io/ajith-dev-big/casper-node-dumps/ajith-dev-big/04032024_1002/dump_download_list.html](url)

Nodes of Interest: 172.44.51.45 (TTL - initialise failed), 172.44.53.214 (sync_to_genesis)

**Comment by marc-casperlabs** [comment]
IIRC this was a testing environment issue, not a code one. If it pops up again, please re-open!
