### ISSUE TITLE
Distributing rewards for signatures sometimes fail if the validator dropped from the validator list

### ISSUE THREAD

**Issue by SaiProServ** [casper-network/casper-node#4611]
While investigating the itst13 nightly test failure we may have discovered a bug in the new rewards logic.
In this test one of the 5 nodes (node 5 which is supposed to also be a validator) is being shut down in era 1 and is being started again in era 3.
Node 5 is getting evicted as expected from the validator set and is not part of the validator set of era 4 (although it is a validator in era 3).
When trying to execute the switch block at the end of era 4 the network stalls because the block fails execution because it cannot distribute the rewards correctly.
The rewards that the auction is trying to distribute is for node-5 for signing the last couple of blocks from era 3.
node-5 was started during era 3 and never switched to Validate (since it was syncing back to genesis in KeepUp), though it was in the list of validators for era 3.
The actual failure is in the distribute() auction function which takes the seigniorage recipients for era 4 and doesn’t find the validator (since it was evicted)
Because the auction distribute function fails, the block cannot be executed on any of the nodes so the network stalls.

**Comment by devendran-m** [comment]
Housekeeping: Removed the obsolete `release-blocker` tag and added the correct `release blocker` tag.
