### ISSUE TITLE
Move values that can affect size of the BinaryPort request to chainspec

### ISSUE THREAD

**Issue by SaiProServ** [casper-network/casper-node#4629]
There are some hardcoded values in the node that should be moved to chainspec. Even though there are probably many others, this ticket should focus on the values that may affect the size of the binary port request, these include, but are not limited to MAX_NAMED_KEY_NAME_LENGTH and DEFAULT_MAX_QUERY_DEPTH. To get the full list one need to review possible variants of binary request.

**Comment by devendran-m** [comment]
Confirm with Jakub to get a summary and ask Teonite if they could pick this up. (alternatively Igor or Gregory) - @devendran-m

**Comment by zajko** [comment]
Also include these:
Review max_request_size_bytes and max_response_size_bytes binary port config

**Comment by devendran-m** [comment]
Per the offline triage with @zajko , the requirement specified in #4580 will be addressed in this ticket/story. This supersedes 4580 and therefore 4580 is closed.

**Comment by zajko** [comment]
I went through the properties of binary_port and couldn't find any properties that would be hard-coded. I'm closing the ticket
