### ISSUE TITLE
Create a tool for direct communication with binary port

### ISSUE THREAD

**Issue by SaiProServ** [casper-network/casper-node#4630]
In short term, such tool would make it easier to develop changes to binary port as it will eliminate the necessity to use the casper-sidecar for simple requests. In long term, it could be used in tests (both NCTL and casper-test) to talk directly to node instead of going through the RPC layer. Currently we're focusing on a short-term goal, hence it doesn't need to be a full-fledged tool, but something we can use internally.

**Comment by gRoussac** [comment]
@devendran-m isn't it https://github.com/casper-ecosystem/casper-binary-port-client ?

**Comment by devendran-m** [comment]
Hi @gRoussac , It may be the case and you may be right. However, I would like to run it past a triage. 
As there are no assignees and sprints attached to this, so I am moving it back to the New Issues column for triage.

**Comment by gRoussac** [comment]
@devendran-m Probaly linked to #4581 #4832 on node with possible downstream on this binary client

**Comment by devendran-m** [comment]
To do:
- Perhaps it was done but never assessed.
- Close this and create a discussion topic for next sprint entry.
