### ISSUE TITLE
Write reactor tests for checking transaction payments

### ISSUE THREAD

**Issue by SaiProServ** [casper-network/casper-node#4632]
Write one or more reactor tests that set up sending transactions and check payment logic.

**Comment by alsrdn** [comment]
- https://github.com/EdHastingsCasperAssociation/casper-node/pull/20
- https://github.com/EdHastingsCasperAssociation/casper-node/pull/21
- https://github.com/EdHastingsCasperAssociation/casper-node/pull/25
- https://github.com/EdHastingsCasperAssociation/casper-node/pull/26
- https://github.com/EdHastingsCasperAssociation/casper-node/pull/27
- https://github.com/EdHastingsCasperAssociation/casper-node/pull/29
