### ISSUE TITLE
Bug report: The state_get_entity response does not include a method to retrieve the named keys of an addressable entity.

### ISSUE THREAD

**Issue by SaiProServ** [casper-network/casper-node#4675]
The state_get_entity endpoint should be changed to offer some method of retrieving the named keys of an addressable entity

**Comment by jacek-casper** [comment]
This is implemented here: https://github.com/casper-network/casper-sidecar/pull/296, in review right now

**Comment by devendran-m** [comment]
Housekeeping: Removed the obsolete `release-blocker` tag and added the correct `release blocker` tag.
