### ISSUE TITLE
Final pass on contract self payment

### ISSUE THREAD

**Issue by SaiProServ** [casper-network/casper-node#4685]
In feat-2.0 we’re adding functionality that allows contracts to pay for themselves (see operations.rs, execute_finalized_block()). Once this functionality is ready we need to test that it’s working correctly by writing new reactor tests that validate this functionality. So far all payment related tests have been grouped in the node/src/reactor/main_reactor/tests/transactions.rs file. Write a few more test cases for the contract paying for itself functionality.

**Comment by EdHastingsCasperAssociation** [comment]
blocked by https://github.com/casper-network/casper-node/pull/4897

**Comment by EdHastingsCasperAssociation** [comment]
As discussed there is a PR up on the blocking issue, so in the interests of time even tho the PR is still in review I will code this against that PR. This may result in some rework but probably not and its less worse than losing more days waiting.
