### ISSUE TITLE
Modify the addressable entity RPC endpoint to return an aggregate response containing named keys and entry points

### ISSUE THREAD

**Issue by SaiProServ** [casper-network/casper-node#4686]
The addressable entity structure no longer contains named keys and entry points after recent changes, and that results in our get_entity RPC endpoint no longer surfacing that data. The sidecar should retrieve and expose this data by issuing 2 additional binary requests to get named keys and entry points by a key prefix containing the entity address. This will require some additions in GlobalStateRequest to make it possible to query the global state by a key prefix (we might want to limit this to specific prefix types in order to prevent callers from making queries that are too broad, like a querying with a prefix that matches all addressable entities in the database).

**Comment by devendran-m** [comment]
Related PR is #4689
