### ISSUE TITLE
Failed to start network with Mainnet DB snapshot

### ISSUE THREAD

**Issue by cspramit** [casper-network/casper-node#4698]
RC Testing:

Network: 5 + 2
Name: ajith-mainnet-clone
Branch: feat-2.0
Commit: 47cd7d31c38f51bd1c646d7a2948fec5f12749d9
Switch Block: 2163794
Test: Mainnet DB Snapshot
:red_circle: Issue: Failed to start network with Mainnet DB snapshot
Observations:
used the feat-2.0 global-state-update-gen tool
used db snapshot from era 11242 and height 2163794
getting error with commit upgrade
{"timestamp":"2024-05-06T11:34:03.487763Z","level":"ERROR","fields":{"message":"fatal error via control announcement","file":"node/src/reactor/main_reactor/control.rs","line":"125","msg":"failed to commit upgrade: Value not found"},"target":"casper_node::reactor","span":{"ev":1572,"name":"dispatch"},"spans":[{"ev":1572,"name":"dispatch"}]}
Grafana: [link](https://grafana.casperlabs.io/d/rpvdF91Sk/release-test-metrics-overview-condor?orgId=1&var-casper_environment=ajith-mainnet-clone&var-casper_version=casper&var-casper_node_type=All&var-casper_hostname=All&from=1714994563898&to=1714995401346)
Dumps: http://genesis.casperlabs.io/ajith-mainnet-clone/casper-node-dumps/ajith-mainnet-clone/06052024_1130/dump_download_list.html

**Comment by cspramit** [comment]
cc: @SaiProServ @thamps-casp

**Comment by devendran-m** [comment]
Housekeeping: Removed the obsolete `release-blocker` tag and added the correct `release blocker` tag.
