### ISSUE TITLE
Add RPC endpoint to return rewards for a specific validator or a specific delegator for a specific era

### ISSUE THREAD

**Issue by piotr-dziubecki** [casper-network/casper-node#4713]
The existing auction info endpoint returns all of the auction info (including rewards) for a given era. As this contains all validators and all of their respective delegators, the returned data can be arbitrarily large. For consumers (such as the requesting party, BitGo) who are only concerned with a specific validator or delegator, this is inconvenient and inefficient. The new endpoint should support a request for reward info for a specific era, and specific PublicKey. The backing logic would filter the full set of rewards data for the imputed data, including records matching the imputed PublicKey and excluding all other records.

**Comment by jacek-casper** [comment]
I think this has already been covered in https://github.com/casper-network/casper-node/pull/4736
