### ISSUE TITLE
Casper 2.0 - LmdbWasmTestBuilder filesizes and test threads

### ISSUE THREAD

**Issue by kubaplas** [casper-network/casper-node#4727]
Hi,
I am currently implementing the support for Casper 2.0 (using feat-2.0 branch) in Odra and have a hiccup when running the tests: 
As I understood, `InMemoryWasmTestBuilder` was removed in favor of `LmdbWasmTestBuilder`. However, when I use it to run the tests, it refuses to work without the `RUST_TEST_THREADS=1` flag. Otherwise, I get a bunch of errors like this:

```
thread 'features::handling_errors::tests::test_owner_error' panicked at /home/kuba/.cargo/git/checkouts/casper-node-dd1233ff78032163/879c244/execution_engine_testing/test_support/src/wasm_test_builder.rs:581:17:
TrackingCopy(Storage(Lmdb(CursorFull)))

...

thread 'features::access_control::test::deploy_works' panicked at /home/kuba/.cargo/git/checkouts/casper-node-dd1233ff78032163/879c244/storage/src/global_state/trie_store/operations/mod.rs:396:25:
No trie value at key: 112982333fd1fb0b3d3e15554311cf1e7c657948bf57728aa39fa0cd213de4fd (reading from path: [6, 209, 36, 161, 69, 255, 83, 55, 140, 255, 247, 151, 12, 161, 99, 178, 172, 238, 119, 87, 12, 108, 104, 82, 252, 113, 125, 229, 6, 124, 50, 93, 182])
```

Furthermore, I noticed that it creates a folder in my project called `global_state`, which would be fine, but the size of the `data.lmdb` file is 977GB...

Can you help me with those?

**Comment by mpapierski** [comment]
As discussed the issue was that multiple writers were sharing the same global state LMDB file and the solution was to use `new_temporary_with_config` constructor present in feat-2.0.
