### ISSUE TITLE
In RC1, an account hash and its Entity Address had the same hash:

### ISSUE THREAD

**Issue by cspramit** [casper-network/casper-node#4763]
Description
Edit Description
In RC1, an account hash and its Entity Address had the same hash:
account-hash-989ca079a5e446071866331468ab949483162588d57ec13ba6bb051f1e15f8b7
entity-account-989ca079a5e446071866331468ab949483162588d57ec13ba6bb051f1e15f8b7

It’s not the case with RC2:
entity-account-1316e1C5C58924E473AcA84e5574Ec11548921590cA16827C7657FCc1bE92bE4"
"entity_kind": {

          "Account": "account-hash-9fa1fc0808d3a5b9ea9f3af4ca7c8c3655568fdf378d8afdf8a7e56e58abbfd4"

        },

Is it expected?

**Comment by gRoussac** [comment]
Forge track https://casperlabs.atlassian.net/browse/EXT-7
