### ISSUE TITLE
Fix an issue with rewards distribution

### ISSUE THREAD

**Issue by SaiProServ** [casper-network/casper-node#4776]
An issue with rewards distribution has revealed itself in multiple nightly tests, e.g. itst13. The node fails to execute a block after an upgrade with an error: distribute block rewards failed due to auction error ValidatorNotFound.

**Comment by devendran-m** [comment]
Check with AJ if it's fixed or not? - @devendran-m

**Comment by thamps-casp** [comment]
Attempted multiple upgrade scenarios with load to the network

Network: 5 + 2 (8s)
genesis: `0432614a8e7ec8f048eac0c850508fec3049e15e`
upgrade1: `a44f882afa7f401ea55361ec26fbb8ef9bd4fbbc`
upgrade2: `a44f882afa7f401ea55361ec26fbb8ef9bd4fbbc`

Test:
- multiple 30k transfers in v2
- multiple wasm transfers in v2


Observations:
- network upgraded at activation point.
- no panic with auction error was able to be replicated
- note - rewards evaluation not done

To test with larger 100 + 20 networks

**Comment by thamps-casp** [comment]
Network: 100 + 20 (8s)
genesis: 0432614a8e7ec8f048eac0c850508fec3049e15e
upgrade1: 1848e2e1b3da0591bfd34de8c5a150acc37bc3ac
upgrade2: 1848e2e1b3da0591bfd34de8c5a150acc37bc3ac

Test:

multiple 30k transfers in v2
multiple wasm transfers in v2
Observations:

network upgraded at activation point.
no panic with auction error was able to be replicated
note - rewards evaluation not done

**Comment by thamps-casp** [comment]
Closing ticket as cannot be re-produced. Will re-open if issue is observed in future tests.
