### ISSUE TITLE
Fix an issue with nodes failing to keep in sync

### ISSUE THREAD

**Issue by SaiProServ** [casper-network/casper-node#4777]
An issue has been discovered where nodes fail to keep in sync to tip and fail with a storage error: duplicate entries for blocks for transaction transaction-v1-hash(c3ec..b97f): block-hash(166a..3432) / block-hash(33ec..ba52). This error indicates that we are finding a pre-existing block already containing one of the transactions from a block or execution results that we're writing to LMDB. Initially raised here: [ https://casper-labs-team.slack.com/archives/C01ULKL8G8J/p1718878384870639.](url)

**Comment by devendran-m** [comment]
Extract the content from the Slack message - @devendran-m

**Comment by devendran-m** [comment]
Dev to check with Joe S - https://casper-labs-team.slack.com/archives/C01ULKL8G8J/p1718878384870639.

**Comment by devendran-m** [comment]
Thank you very much @sacherjj for sharing the Slack chat log with me. I have consolidated the chat log in the document [here](https://docs.google.com/document/d/1gajMEh-ljb8TFUyX2JGHR-T93ATkYhTmNRuPQrkLl-Q/edit?usp=sharing) for reference.
cc : @EdHastingsCasperAssociation , @darthsiroftardis

**Comment by zajko** [comment]
I wasn't able to reproduce and after analyzing the code I suspect that this is related to rc-4. If this issue reoccurs please create another bug ticket.
