### ISSUE TITLE
Casper-node should return error message if a transaction has BalanceIdentifier::PenalizedAccount

### ISSUE THREAD

**Issue by SaiProServ** [casper-network/casper-node#4782]
When a transaction is sent to the node there is a check in the execution engine if the balance is OK. This happens around here [https://github.com/casper-network/casper-node/blob/release-2.0.0-rc2/node/src/components/contract_runtime/operations.rs#L224](url)

If the outcome of that is  BalanceIdentifier::PenalizedAccount the transaction is not errored-out. So the execution info for that transaction has no error_message and the end user has no knowledge that there was a problem with execution.

**Comment by EdHastingsCasperAssociation** [comment]
It should now be the case that in the case of bogus custom payment logic the payment result error is retained instead of being cleared by later successful post-processing results.

**Comment by EdHastingsCasperAssociation** [comment]
The logic originally referred to was previously changed.

**Comment by devendran-m** [comment]
Related PR is [#4912](https://github.com/casper-network/casper-node/pull/4912)
