### ISSUE TITLE
casper-node should handle calling endpoints on stored contracts for Version1 transactions

### ISSUE THREAD

**Issue by SaiProServ** [casper-network/casper-node#4783]
Currently if I try to call an endpoint for a stored contract using the Version1 variant of Transaction I will get a silent error which originates here [https://github.com/casper-network/casper-node/blob/release-2.0.0-rc2/node/src/components/contract_runtime/operations.rs#L290](url)

When doing finalized block execution and the Transaction is an EntryPoint call the node needs to check for EntryPointPayment of that EntryPoint prior to BalanceIdentifier handling. And if the EntryPointPayment is "Caller"  - it shouldn't penalize.

**Comment by EdHastingsCasperAssociation** [comment]
Working on this

**Comment by EdHastingsCasperAssociation** [comment]
The logic referred to was removed in rc4. This should be working in dev net already.

**Comment by EdHastingsCasperAssociation** [comment]
@Jiuhong-casperlabs can you re-test this on dev net to determine if it can be closed or if I need to spend time digging into it?

**Comment by Jiuhong-casperlabs** [comment]
> @Jiuhong-casperlabs can you re-test this on dev net to determine if it can be closed or if I need to spend time digging into it?

It was fixed.
[Transaction hash](https://devnet.make.services/transactions/f37878ee57de9f7ddc4a7a0445d1088b1014683d9fd3f51bf997a26c777c113e) for your reference.
