### ISSUE TITLE
"Remove revert on deser in try_get_named_arg"

### ISSUE THREAD

**Issue by SaiProServ** [casper-network/casper-node#4790]
This removes a false positive revert "it fixes try_get_named_arg method to return correctly"

**Comment by devendran-m** [comment]
@gRoussac , Please provide more context.

**Comment by gRoussac** [comment]
@devendran-m teonite introduced a new helper function in a PR on casper node that was reverting in contract runtime. 

https://github.com/casper-network/casper-node/pull/4569#discussion_r1662435826

We removed this revert call in try_get_named_arg in https://github.com/casper-network/casper-node/pull/4786/files

this ticket should be closed already I guess
