### ISSUE TITLE
A Wasm based transaction that errors should not apply effects

### ISSUE THREAD

**Issue by SaiProServ** [casper-network/casper-node#4791]
For example, in [this transaction](https://gist.githubusercontent.com/davidatwhiletrue/a3e3c554dd4d2e66eaf9bb007e5dacb8/raw/8a73d40cd2c2da0dfe9777e4fa0d2850329703ca/tx_cep18install.json) to install a cep18 instance, the result is out of gas error ("error_message": "Out of gas error"). However, named keys are `[written to the account](https://gist.github.com/davidatwhiletrue/a3e3c554dd4d2e66eaf9bb007e5dacb8#file-account-json)`, and the [contract entity](https://gist.github.com/davidatwhiletrue/a3e3c554dd4d2e66eaf9bb007e5dacb8#file-contract-json) is created (the transaction is successful executed?).

**Comment by devendran-m** [comment]
There are no assignees and sprints attached to this, so moving it back to the New Issues column for triage.

**Comment by devendran-m** [comment]
To do: Fix to be applied.

**Comment by devendran-m** [comment]
Related PR is [#4912](https://github.com/casper-network/casper-node/pull/4912)
