### ISSUE TITLE
Create new mode for casper-node to pull global state and shutdown.

### ISSUE THREAD

**Issue by SaiProServ** [casper-network/casper-node#4799]
Create a mode in casper-node to sync the tip global state and shut down.  This would be used to have the minimal possible DB that has as little block and deploy data stored. This could be used to accelerate the initial sync process to allow faster node startup from clean without extra block information.
Ed mentioned that it should be just an early exist of the initial sync.  Trusted hash triggers a sync leap to current tip.  Then state is synced. At the point where it would do the next sync leap, instead it exits.

**Comment by EdHastingsCasperAssociation** [comment]
This is relatively easy to do. I would estimate at around 5pts, including tests. It does not required a breaking change.

**Comment by devendran-m** [comment]
@wojcik91 has picked this up in the ongoing sprint.
