### ISSUE TITLE
SRE Testing: Emergency upgrade with mainnet snapshot network stall

### ISSUE THREAD

**Issue by cspramit** [casper-network/casper-node#4811]
Performed emergency upgrade with latest TTL snapshot and network was able to load up  and create around 20 blocks - but then all nodes went into CatchUp and network stalled.
continous messages: event took very long to dispatch - StorageRequest, ReactorCrank
Dumps (TTL Snapshot): [(http://genesis.casperlabs.io/ajith-mainnet-clone-1/casper-node-dumps/ajith-mainnet-clone-1/18072024_0156/dump_download_list.html)]

Slack: https://casper-labs-team.slack.com/archives/C01ULKL8G8J/p1721268082469159?thread_ts=1720821743.218009&cid=C01ULKL8G8J

**Comment by devendran-m** [comment]
Received the following update from @fizyk20 ;

> I'm still doing some work that came out of this ticket, but it's not really directly related to it (I'm porting some changes I made to the `global-state-update-gen` tool over to the `feat-2.0` branch).

As per the chat with Bart and based on his above updates, closing this issue.
