### ISSUE TITLE
SRE Testing: Slash instead of unbonding true gives errors

### ISSUE THREAD

**Issue by cspramit** [casper-network/casper-node#4812]
set slash_instead_of_unbonding = true  got global_state.toml generation, we are getting the Unbond too Large errors as previous runs.
Dumps (lazy): [http://genesis.casperlabs.io/ajith-mainnet-clone/casper-node-dumps/ajith-mainnet-clone/18072024_0505/dump_download_list.html]

Slack: https://casper-labs-team.slack.com/archives/C01ULKL8G8J/p1721268082469159?thread_ts=1720821743.218009&cid=C01ULKL8G8J

**Comment by devendran-m** [comment]
PR merged. Closing.
