### ISSUE TITLE
Add binary port requests for package, contract and account

### ISSUE THREAD

**Issue by SaiProServ** [casper-network/casper-node#4832]
We should add binary port requests for package, contract and account. Each request should contain a field that can be populated with either a legacy or a v2 key for the corresponding entity (Key::Hash/Key::AddressableEntity, Key::Account vs Key::AddressableEntity etc.). When receiving a v2 key we should always be able to find a match through a direct global storage lookup. For legacy keys, the entity in question might be migrated, in which case we must follow it up with another lookup for a migrated entity. The response of each request should be an enum that can contain either a legacy or v2 variant of the corresponding entity (Account vs AddressableEntity, Contract vs AddressableEntity). In the contract request specifically we should additionally support a flag for retrieving the bytecode together with the contract.

**Comment by devendran-m** [comment]
Housekeeping - Moving it back to New Issues for triage.

**Comment by devendran-m** [comment]
PR is https://github.com/casper-network/casper-node/pull/4845
