### ISSUE TITLE
Fix flaky "node_should_rejoin_after_ejection" test

### ISSUE THREAD

**Issue by devendran-m** [casper-network/casper-node#4859]
This test fails occasionally, for example in [this build](https://drone-auto-casper-network.casperlabs.io/casper-network/casper-node/12754/1/3). It also failed locally for me, but sporadically. This could be some timing issue, since this test does not use RNG.

Additional information from @fizyk20 ;

> The test itself might not use the RNG, but I think some underlying components still do. I reproduced the issue with CL_TEST_SEED=08f498218291e7059a207a4a4ff0a78a twice, and it passed for me twice without a set seed, so it is likely that the seed does play a part in this.

**Comment by fizyk20** [comment]
This should now be fixed.
