### ISSUE TITLE
Clean up pass on TODO's

### ISSUE THREAD

**Issue by zajko** [casper-network/casper-node#4918]
Prior to cutting the release, we should do a top down pass on TODO comments in the code and for each determine if:

- TODONE - remove the TODO because we did do the thing
- TOWONT - remove the TODO because we're not going to do the thing 
- TOWHAT - remove elderly TODOs left by developers of prior times for which the context has been lost
- TODID - do any TODO's which are easily accomplished / low hanging fruit
- TONO - remove TODO's that 1) were never valid / relevant 2) are no longer valid / relevant
- TODO - leave behind any TODO's which are still valid for future work

Also, while doing the clean up pass, fix up any minor things observed along the way, such as comments, bad-wrong names, println!'s, commented out junk, disabled tests, etc.

**Comment by devendran-m** [comment]
The scope of the ticket increased to include clean-up of public contract API to not dependent on addressable entity being on.
