### ISSUE TITLE
Verify QPS throttling and ensure it's appropriately configured

### ISSUE THREAD

**Issue by devendran-m** [casper-network/casper-node#4939]
Verify the QPS throttling settings for both the node and sidecar JSON RPC instances to ensure they are appropriately configured and compatible.

**Background Context:** Throttling configurations on the DevNet environment, specifically for the binary port and JSON RPC on the node and sidecar.

**Issue:** Throttling issue reported by @thamps-casp as part of his testing.

**Current Status:**
- **Binary Port (RC Versions):** Earlier RC versions (up to RC4) lacked throttling on the binary port due to prior dependency on a library (Juliet) that provided built-in throttling. Throttling for the binary port was reintroduced in RC5 with custom settings to manage query-per-second (QPS) limitations.
- **JSON RPC on Sidecar:** JSON RPC on the sidecar currently has QPS throttling, managed through instance-specific settings.

**Potential Bottlenecks:** It was noted that bottlenecks could arise if throttling is stricter on one port than the other, potentially limiting capacity if the sidecar or node becomes constrained at different rates.

**Action Items:** 
Hi @zajko , please correct if these actions are correct from the discussion yesterday.
- [ ] Verify the QPS throttling settings for both the node and sidecar JSON RPC instances to ensure they are appropriately configured and compatible.
- [ ] Documentation: A clarification will be made for testing on the DevNet, specifying which versions support throttling and any differences between configurations on the binary port and JSON RPC.

**Additional Context:** Originally, the use of Juliet library provided built-in throttling, which led to some earlier assumptions about throttling behavior on the binary port. With Juliet removed, throttling had to be re-implemented in RC5 for consistency.

**Comment by zajko** [comment]
Bump up QPS on node to ~110. Dial down concurrent open connections to ~5
