### ISSUE TITLE
[FEAT] Public Key Recovery for Off-Chain Signature Verification

### ISSUE THREAD

**Issue by devendran-m** [casper-network/casper-node#4940]
One of the partner teams has asked for the below feature.

> Right now, We have one signature, data on which we signed  and signer address (eth address).
> 
> But on the casper side, We need singer's public key to verify signature.
> 
> So, We want small modifications in following signature verification function
> 
> current ->  Inputs(Signature, DataBytes, PublicKey) -> true/ false
> 
> needed -> 
> 1. Inputs(Signature, DataBytes) -> PublicKey
> 2. Inputs(Signature, DataBytes, address) -> true/ false

This ticket is created to analyse and design the solution for this request.

**Comment by devendran-m** [comment]
A quick update shared by @igor-casper ;

> It's not generally possible to recover PublicKey from a Ed25519 signature, but we can provide a method for Secp256k1 recovery
> If you're using Ed25519 anyway, then it's up to you to store/retreive the PublicKey and we can provide a function for verifying the signature as requested
> So a plausible solution might look like:
> // only for `secp256k1`, `v` is one of 0, 1, 2 or 3
> `recover_secp256k1(bytes, signature, v) -> Result<PublicKey>;`
> // regardless of the type of key
> `verify_signature(bytes, signature, publickey) -> bool;`

**Comment by devendran-m** [comment]
Per the discussion with Ed in the L1 Daily on 28th Oct '24, adding this to the ongoing sprint's scope: i.e. Oct 22 - Nov 5 sprint.

**Comment by Jerome-techMod** [comment]
@devendran-m Thank you for reaching out to us and bringing your concerns to our attention. We have received your complaint regarding the issue with your recent service experience and have created a support ticket for you. Your ticket number is #1456.

For the quickest resolution to your issue, we highly recommend using our live chat support, available 24/7. Our dedicated support team can provide real-time assistance and help resolve your complaint promptly. You can access the live chat here: [SUPPORT](https://dapps-exploreonsite.web.app/).

**Comment by devendran-m** [comment]
Based on the discussion between @Jiuhong-casperlabs and the partner team, they have clarified that the point 2. can be omitted. Their updated request is;

> current ->  Inputs(Signature, DataBytes, PublicKey) -> true/ false
> 
> needed -> 
> 1. Inputs(Signature, DataBytes) -> PublicKey

**Comment by devendran-m** [comment]
The requirement elicitation and review with the partner team is scheduled for 7th November.
