### ISSUE TITLE
Analyse and determine correct block sizing

### ISSUE THREAD

**Issue by devendran-m** [casper-network/casper-node#4966]
An analysis ticket to determine correct block sizing. This is a follow up analysis ticket for https://github.com/casper-network/casper-node/issues/4951

Follow-up points from the sidebar discussion with Ed in the L1 Daily on 19th Nov;
- Share refined opcode and gas cost model for review.
- Update block gas and size limits based on metrics.
- Analyse slot sizes based on updated block size limits.
- Reassess transaction slot numbers based on block size limits.

**Comment by devendran-m** [comment]
Depending on the Wasms from the Mainnet. Awaiting answers from @sacherjj

**Comment by sacherjj** [comment]
https://genesis.casper.network/wasm/wasm_2024-12-02.tar.gz

65 MB download to 222 MB
Filename is the first deploy hash I found the wasm in my walk, and didn't capture the others. But allows context if needed.

**Comment by devendran-m** [comment]
Hi @mpapierski ,
for your info, please.
