### ISSUE TITLE
[BUG] `add-bid` transaction fails due to exceeding Block Gas Limit/high Gas cost

### ISSUE THREAD

**Issue by devendran-m** [casper-network/casper-node#4968]
Auction `add-bid` transaction fails due to high gas cost exceeding the network's block gas limit.

An add-bid transaction using casper-client fails with an error indicating that the transaction exceeds the network's block gas limit. The issue arises during execution with the following parameters:

The transaction fails with an error message, despite the gas parameters appearing valid on the surface. The network's block gas limit (`block_gas_limit = 3_300_000_000_000`) is exceeded.

Reported by : @thamps-casp 

```bash
casper-client put-transaction add-bid \
  --node-address http://172.31.13.154:7777 \
  --chain-name casper-ajith-dev-small \
  --payment-amount 10000000000 \
  --secret-key /tmp/ajith-dev-small/cluster/pre-validator/172.31.26.180/secret_key.pem \
  --delegation-rate 33 \
  --minimum-delegation-amount 500000000000 \
  --maximum-delegation-amount 1000000000000 \
  --public-key 01b16a56d07107ae9882685440813aeb3b0e1c8317602000ffa7017714582a2590 \
  --transaction-amount 500000000000 \
  --gas-price-tolerance 5 \
  --pricing-mode fixed

```

Error returned;
```json
{
  "code": -32016,
  "message": "Invalid transaction",
  "data": "the transaction was invalid: The transaction sent to the network exceeds the network's block gas limit"
}
```

**Comment by devendran-m** [comment]
Hi @thamps-casp , please share the chainspec you used for the above testing.

**Comment by thamps-casp** [comment]
Here with attaching the chainspec.toml used for test run.
[chainspec.zip](https://github.com/user-attachments/files/17836665/chainspec.zip)
