### ISSUE TITLE
Dictionary Item Tests

### ISSUE THREAD

**Issue by devendran-m** [casper-network/casper-node#4991]
Ticket to;
- Create a test to validate dictionary key access permissions across multiple contracts.
- Verify whether non-owner contracts with appropriate Uref permissions can access dictionary items.

**Comment by darthsiroftardis** [comment]
Update on this ticket, it would seem we already have these tests present in the EE test suite, as such I am marking this as done since the work is already present 

The tests in question are present in `dictionary.rs` in the contract_api folder of the EE test suite
